package com.orange.goldgame.system.dao;

import java.sql.SQLException;
import java.util.List;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.orange.goldgame.domain.AppellationConfig;
import com.orange.goldgame.domain.AppellationConfigExample;

public class AppellationConfigDAOImpl implements AppellationConfigDAO {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table appellation_config
     *
     * @ibatorgenerated Mon Aug 26 10:43:53 CST 2013
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table appellation_config
     *
     * @ibatorgenerated Mon Aug 26 10:43:53 CST 2013
     */
    public AppellationConfigDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table appellation_config
     *
     * @ibatorgenerated Mon Aug 26 10:43:53 CST 2013
     */
    public int countByExample(AppellationConfigExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("appellation_config.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table appellation_config
     *
     * @ibatorgenerated Mon Aug 26 10:43:53 CST 2013
     */
    public int deleteByExample(AppellationConfigExample example) throws SQLException {
        int rows = sqlMapClient.delete("appellation_config.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table appellation_config
     *
     * @ibatorgenerated Mon Aug 26 10:43:53 CST 2013
     */
    public int deleteByPrimaryKey(Integer id) throws SQLException {
        AppellationConfig key = new AppellationConfig();
        key.setId(id);
        int rows = sqlMapClient.delete("appellation_config.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table appellation_config
     *
     * @ibatorgenerated Mon Aug 26 10:43:53 CST 2013
     */
    public Integer insert(AppellationConfig record) throws SQLException {
        Object newKey = sqlMapClient.insert("appellation_config.ibatorgenerated_insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table appellation_config
     *
     * @ibatorgenerated Mon Aug 26 10:43:53 CST 2013
     */
    public Integer insertSelective(AppellationConfig record) throws SQLException {
        Object newKey = sqlMapClient.insert("appellation_config.ibatorgenerated_insertSelective", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table appellation_config
     *
     * @ibatorgenerated Mon Aug 26 10:43:53 CST 2013
     */
    public List selectByExample(AppellationConfigExample example) throws SQLException {
        List list = sqlMapClient.queryForList("appellation_config.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table appellation_config
     *
     * @ibatorgenerated Mon Aug 26 10:43:53 CST 2013
     */
    public AppellationConfig selectByPrimaryKey(Integer id) throws SQLException {
        AppellationConfig key = new AppellationConfig();
        key.setId(id);
        AppellationConfig record = (AppellationConfig) sqlMapClient.queryForObject("appellation_config.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table appellation_config
     *
     * @ibatorgenerated Mon Aug 26 10:43:53 CST 2013
     */
    public int updateByExampleSelective(AppellationConfig record, AppellationConfigExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("appellation_config.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table appellation_config
     *
     * @ibatorgenerated Mon Aug 26 10:43:53 CST 2013
     */
    public int updateByExample(AppellationConfig record, AppellationConfigExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("appellation_config.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table appellation_config
     *
     * @ibatorgenerated Mon Aug 26 10:43:53 CST 2013
     */
    public int updateByPrimaryKeySelective(AppellationConfig record) throws SQLException {
        int rows = sqlMapClient.update("appellation_config.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table appellation_config
     *
     * @ibatorgenerated Mon Aug 26 10:43:53 CST 2013
     */
    public int updateByPrimaryKey(AppellationConfig record) throws SQLException {
        int rows = sqlMapClient.update("appellation_config.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table appellation_config
     *
     * @ibatorgenerated Mon Aug 26 10:43:53 CST 2013
     */
    private static class UpdateByExampleParms extends AppellationConfigExample {
        private Object record;

        public UpdateByExampleParms(Object record, AppellationConfigExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}