package com.orange.goldgame.system.dao;

import java.sql.SQLException;
import java.util.List;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.orange.goldgame.domain.AreaConfig;
import com.orange.goldgame.domain.AreaConfigExample;

public class AreaConfigDAOImpl implements AreaConfigDAO {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table area_config
     *
     * @abatorgenerated Wed Apr 16 10:41:12 CST 2014
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table area_config
     *
     * @abatorgenerated Wed Apr 16 10:41:12 CST 2014
     */
    public AreaConfigDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table area_config
     *
     * @abatorgenerated Wed Apr 16 10:41:12 CST 2014
     */
    public Integer insert(AreaConfig record) throws SQLException {
        Object newKey = sqlMapClient.insert("area_config.abatorgenerated_insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table area_config
     *
     * @abatorgenerated Wed Apr 16 10:41:12 CST 2014
     */
    public int updateByPrimaryKey(AreaConfig record) throws SQLException {
        int rows = sqlMapClient.update("area_config.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table area_config
     *
     * @abatorgenerated Wed Apr 16 10:41:12 CST 2014
     */
    public int updateByPrimaryKeySelective(AreaConfig record) throws SQLException {
        int rows = sqlMapClient.update("area_config.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table area_config
     *
     * @abatorgenerated Wed Apr 16 10:41:12 CST 2014
     */
    @SuppressWarnings("unchecked")
    public List<AreaConfig> selectByExample(AreaConfigExample example) throws SQLException {
        List<AreaConfig> list = (List<AreaConfig>) sqlMapClient.queryForList("area_config.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table area_config
     *
     * @abatorgenerated Wed Apr 16 10:41:12 CST 2014
     */
    public AreaConfig selectByPrimaryKey(Integer id) throws SQLException {
        AreaConfig key = new AreaConfig();
        key.setId(id);
        AreaConfig record = (AreaConfig) sqlMapClient.queryForObject("area_config.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table area_config
     *
     * @abatorgenerated Wed Apr 16 10:41:12 CST 2014
     */
    public int deleteByExample(AreaConfigExample example) throws SQLException {
        int rows = sqlMapClient.delete("area_config.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table area_config
     *
     * @abatorgenerated Wed Apr 16 10:41:12 CST 2014
     */
    public int deleteByPrimaryKey(Integer id) throws SQLException {
        AreaConfig key = new AreaConfig();
        key.setId(id);
        int rows = sqlMapClient.delete("area_config.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table area_config
     *
     * @abatorgenerated Wed Apr 16 10:41:12 CST 2014
     */
    public int countByExample(AreaConfigExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("area_config.abatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table area_config
     *
     * @abatorgenerated Wed Apr 16 10:41:12 CST 2014
     */
    public int updateByExampleSelective(AreaConfig record, AreaConfigExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("area_config.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table area_config
     *
     * @abatorgenerated Wed Apr 16 10:41:12 CST 2014
     */
    public int updateByExample(AreaConfig record, AreaConfigExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("area_config.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table area_config
     *
     * @abatorgenerated Wed Apr 16 10:41:12 CST 2014
     */
    private static class UpdateByExampleParms extends AreaConfigExample {
        private Object record;

        public UpdateByExampleParms(Object record, AreaConfigExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}