package com.orange.goldgame.system.dao;

import java.sql.SQLException;
import java.util.List;

import com.orange.goldgame.domain.AreaConfig;
import com.orange.goldgame.domain.AreaConfigExample;

public interface AreaConfigDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table area_config
     *
     * @abatorgenerated Wed Apr 16 10:41:12 CST 2014
     */
    Integer insert(AreaConfig record) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table area_config
     *
     * @abatorgenerated Wed Apr 16 10:41:12 CST 2014
     */
    int updateByPrimaryKey(AreaConfig record) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table area_config
     *
     * @abatorgenerated Wed Apr 16 10:41:12 CST 2014
     */
    int updateByPrimaryKeySelective(AreaConfig record) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table area_config
     *
     * @abatorgenerated Wed Apr 16 10:41:12 CST 2014
     */
    List<AreaConfig> selectByExample(AreaConfigExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table area_config
     *
     * @abatorgenerated Wed Apr 16 10:41:12 CST 2014
     */
    AreaConfig selectByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table area_config
     *
     * @abatorgenerated Wed Apr 16 10:41:12 CST 2014
     */
    int deleteByExample(AreaConfigExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table area_config
     *
     * @abatorgenerated Wed Apr 16 10:41:12 CST 2014
     */
    int deleteByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table area_config
     *
     * @abatorgenerated Wed Apr 16 10:41:12 CST 2014
     */
    int countByExample(AreaConfigExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table area_config
     *
     * @abatorgenerated Wed Apr 16 10:41:12 CST 2014
     */
    int updateByExampleSelective(AreaConfig record, AreaConfigExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table area_config
     *
     * @abatorgenerated Wed Apr 16 10:41:12 CST 2014
     */
    int updateByExample(AreaConfig record, AreaConfigExample example) throws SQLException;
}