package com.orange.goldgame.system.dao;

import java.sql.SQLException;
import java.util.List;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.orange.goldgame.domain.ArearobotPre;
import com.orange.goldgame.domain.ArearobotPreExample;

public class ArearobotPreDAOImpl implements ArearobotPreDAO {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table arearobot_pre
     *
     * @ibatorgenerated Sun Sep 29 17:16:17 CST 2013
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table arearobot_pre
     *
     * @ibatorgenerated Sun Sep 29 17:16:17 CST 2013
     */
    public ArearobotPreDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table arearobot_pre
     *
     * @ibatorgenerated Sun Sep 29 17:16:17 CST 2013
     */
    public int countByExample(ArearobotPreExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("arearobot_pre.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table arearobot_pre
     *
     * @ibatorgenerated Sun Sep 29 17:16:17 CST 2013
     */
    public int deleteByExample(ArearobotPreExample example) throws SQLException {
        int rows = sqlMapClient.delete("arearobot_pre.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table arearobot_pre
     *
     * @ibatorgenerated Sun Sep 29 17:16:17 CST 2013
     */
    public int deleteByPrimaryKey(Integer id) throws SQLException {
        ArearobotPre key = new ArearobotPre();
        key.setId(id);
        int rows = sqlMapClient.delete("arearobot_pre.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table arearobot_pre
     *
     * @ibatorgenerated Sun Sep 29 17:16:17 CST 2013
     */
    public Integer insert(ArearobotPre record) throws SQLException {
        Object newKey = sqlMapClient.insert("arearobot_pre.ibatorgenerated_insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table arearobot_pre
     *
     * @ibatorgenerated Sun Sep 29 17:16:17 CST 2013
     */
    public Integer insertSelective(ArearobotPre record) throws SQLException {
        Object newKey = sqlMapClient.insert("arearobot_pre.ibatorgenerated_insertSelective", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table arearobot_pre
     *
     * @ibatorgenerated Sun Sep 29 17:16:17 CST 2013
     */
    public List selectByExample(ArearobotPreExample example) throws SQLException {
        List list = sqlMapClient.queryForList("arearobot_pre.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table arearobot_pre
     *
     * @ibatorgenerated Sun Sep 29 17:16:17 CST 2013
     */
    public ArearobotPre selectByPrimaryKey(Integer id) throws SQLException {
        ArearobotPre key = new ArearobotPre();
        key.setId(id);
        ArearobotPre record = (ArearobotPre) sqlMapClient.queryForObject("arearobot_pre.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table arearobot_pre
     *
     * @ibatorgenerated Sun Sep 29 17:16:17 CST 2013
     */
    public int updateByExampleSelective(ArearobotPre record, ArearobotPreExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("arearobot_pre.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table arearobot_pre
     *
     * @ibatorgenerated Sun Sep 29 17:16:17 CST 2013
     */
    public int updateByExample(ArearobotPre record, ArearobotPreExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("arearobot_pre.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table arearobot_pre
     *
     * @ibatorgenerated Sun Sep 29 17:16:17 CST 2013
     */
    public int updateByPrimaryKeySelective(ArearobotPre record) throws SQLException {
        int rows = sqlMapClient.update("arearobot_pre.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table arearobot_pre
     *
     * @ibatorgenerated Sun Sep 29 17:16:17 CST 2013
     */
    public int updateByPrimaryKey(ArearobotPre record) throws SQLException {
        int rows = sqlMapClient.update("arearobot_pre.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table arearobot_pre
     *
     * @ibatorgenerated Sun Sep 29 17:16:17 CST 2013
     */
    private static class UpdateByExampleParms extends ArearobotPreExample {
        private Object record;

        public UpdateByExampleParms(Object record, ArearobotPreExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}