package com.orange.goldgame.system.dao;

import java.sql.SQLException;
import java.util.List;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.orange.goldgame.domain.BuyPropRecord;
import com.orange.goldgame.domain.BuyPropRecordExample;

public class BuyPropRecordDAOImpl implements BuyPropRecordDAO {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table buy_prop_record
     *
     * @ibatorgenerated Tue Jul 09 16:45:52 CST 2013
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table buy_prop_record
     *
     * @ibatorgenerated Tue Jul 09 16:45:52 CST 2013
     */
    public BuyPropRecordDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table buy_prop_record
     *
     * @ibatorgenerated Tue Jul 09 16:45:52 CST 2013
     */
    public int countByExample(BuyPropRecordExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("buy_prop_record.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table buy_prop_record
     *
     * @ibatorgenerated Tue Jul 09 16:45:52 CST 2013
     */
    public int deleteByExample(BuyPropRecordExample example) throws SQLException {
        int rows = sqlMapClient.delete("buy_prop_record.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table buy_prop_record
     *
     * @ibatorgenerated Tue Jul 09 16:45:52 CST 2013
     */
    public int deleteByPrimaryKey(Integer id) throws SQLException {
        BuyPropRecord key = new BuyPropRecord();
        key.setId(id);
        int rows = sqlMapClient.delete("buy_prop_record.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table buy_prop_record
     *
     * @ibatorgenerated Tue Jul 09 16:45:52 CST 2013
     */
    public Integer insert(BuyPropRecord record) throws SQLException {
        Object newKey = sqlMapClient.insert("buy_prop_record.ibatorgenerated_insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table buy_prop_record
     *
     * @ibatorgenerated Tue Jul 09 16:45:52 CST 2013
     */
    public Integer insertSelective(BuyPropRecord record) throws SQLException {
        Object newKey = sqlMapClient.insert("buy_prop_record.ibatorgenerated_insertSelective", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table buy_prop_record
     *
     * @ibatorgenerated Tue Jul 09 16:45:52 CST 2013
     */
    public List selectByExample(BuyPropRecordExample example) throws SQLException {
        List list = sqlMapClient.queryForList("buy_prop_record.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table buy_prop_record
     *
     * @ibatorgenerated Tue Jul 09 16:45:52 CST 2013
     */
    public BuyPropRecord selectByPrimaryKey(Integer id) throws SQLException {
        BuyPropRecord key = new BuyPropRecord();
        key.setId(id);
        BuyPropRecord record = (BuyPropRecord) sqlMapClient.queryForObject("buy_prop_record.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table buy_prop_record
     *
     * @ibatorgenerated Tue Jul 09 16:45:52 CST 2013
     */
    public int updateByExampleSelective(BuyPropRecord record, BuyPropRecordExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("buy_prop_record.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table buy_prop_record
     *
     * @ibatorgenerated Tue Jul 09 16:45:52 CST 2013
     */
    public int updateByExample(BuyPropRecord record, BuyPropRecordExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("buy_prop_record.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table buy_prop_record
     *
     * @ibatorgenerated Tue Jul 09 16:45:52 CST 2013
     */
    public int updateByPrimaryKeySelective(BuyPropRecord record) throws SQLException {
        int rows = sqlMapClient.update("buy_prop_record.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table buy_prop_record
     *
     * @ibatorgenerated Tue Jul 09 16:45:52 CST 2013
     */
    public int updateByPrimaryKey(BuyPropRecord record) throws SQLException {
        int rows = sqlMapClient.update("buy_prop_record.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table buy_prop_record
     *
     * @ibatorgenerated Tue Jul 09 16:45:52 CST 2013
     */
    private static class UpdateByExampleParms extends BuyPropRecordExample {
        private Object record;

        public UpdateByExampleParms(Object record, BuyPropRecordExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}