package com.orange.goldgame.system.dao;

import java.sql.SQLException;
import java.util.List;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.orange.goldgame.domain.ClientToolNotice;
import com.orange.goldgame.domain.ClientToolNoticeExample;

public class ClientToolNoticeDAOImpl implements ClientToolNoticeDAO {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table client_tool_notice
	 * @ibatorgenerated  Tue Jan 14 17:49:56 CST 2014
	 */
	private SqlMapClient sqlMapClient;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table client_tool_notice
	 * @ibatorgenerated  Tue Jan 14 17:49:56 CST 2014
	 */
	public ClientToolNoticeDAOImpl(SqlMapClient sqlMapClient) {
		super();
		this.sqlMapClient = sqlMapClient;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table client_tool_notice
	 * @ibatorgenerated  Tue Jan 14 17:49:56 CST 2014
	 */
	public int countByExample(ClientToolNoticeExample example)
			throws SQLException {
		Integer count = (Integer) sqlMapClient.queryForObject(
				"client_tool_notice.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table client_tool_notice
	 * @ibatorgenerated  Tue Jan 14 17:49:56 CST 2014
	 */
	public int deleteByExample(ClientToolNoticeExample example)
			throws SQLException {
		int rows = sqlMapClient.delete(
				"client_tool_notice.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table client_tool_notice
	 * @ibatorgenerated  Tue Jan 14 17:49:56 CST 2014
	 */
	public int deleteByPrimaryKey(Integer id) throws SQLException {
		ClientToolNotice key = new ClientToolNotice();
		key.setId(id);
		int rows = sqlMapClient.delete(
				"client_tool_notice.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table client_tool_notice
	 * @ibatorgenerated  Tue Jan 14 17:49:56 CST 2014
	 */
	public Integer insert(ClientToolNotice record) throws SQLException {
		Object newKey = sqlMapClient.insert(
				"client_tool_notice.ibatorgenerated_insert", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table client_tool_notice
	 * @ibatorgenerated  Tue Jan 14 17:49:56 CST 2014
	 */
	public Integer insertSelective(ClientToolNotice record) throws SQLException {
		Object newKey = sqlMapClient.insert(
				"client_tool_notice.ibatorgenerated_insertSelective", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table client_tool_notice
	 * @ibatorgenerated  Tue Jan 14 17:49:56 CST 2014
	 */
	public List selectByExample(ClientToolNoticeExample example)
			throws SQLException {
		List list = sqlMapClient.queryForList(
				"client_tool_notice.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table client_tool_notice
	 * @ibatorgenerated  Tue Jan 14 17:49:56 CST 2014
	 */
	public ClientToolNotice selectByPrimaryKey(Integer id) throws SQLException {
		ClientToolNotice key = new ClientToolNotice();
		key.setId(id);
		ClientToolNotice record = (ClientToolNotice) sqlMapClient
				.queryForObject(
						"client_tool_notice.ibatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table client_tool_notice
	 * @ibatorgenerated  Tue Jan 14 17:49:56 CST 2014
	 */
	public int updateByExampleSelective(ClientToolNotice record,
			ClientToolNoticeExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"client_tool_notice.ibatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table client_tool_notice
	 * @ibatorgenerated  Tue Jan 14 17:49:56 CST 2014
	 */
	public int updateByExample(ClientToolNotice record,
			ClientToolNoticeExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"client_tool_notice.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table client_tool_notice
	 * @ibatorgenerated  Tue Jan 14 17:49:56 CST 2014
	 */
	public int updateByPrimaryKeySelective(ClientToolNotice record)
			throws SQLException {
		int rows = sqlMapClient
				.update("client_tool_notice.ibatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table client_tool_notice
	 * @ibatorgenerated  Tue Jan 14 17:49:56 CST 2014
	 */
	public int updateByPrimaryKey(ClientToolNotice record) throws SQLException {
		int rows = sqlMapClient
				.update("client_tool_notice.ibatorgenerated_updateByPrimaryKey",
						record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table client_tool_notice
	 * @ibatorgenerated  Tue Jan 14 17:49:56 CST 2014
	 */
	private static class UpdateByExampleParms extends ClientToolNoticeExample {
		private Object record;

		public UpdateByExampleParms(Object record,
				ClientToolNoticeExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}