package com.orange.goldgame.system.dao;

import java.sql.SQLException;
import java.util.List;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.orange.goldgame.domain.GoodsConfig;
import com.orange.goldgame.domain.GoodsConfigExample;

public class GoodsConfigDAOImpl implements GoodsConfigDAO {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table goods_config
	 * @ibatorgenerated  Tue Sep 10 20:35:12 CST 2013
	 */
	private SqlMapClient sqlMapClient;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table goods_config
	 * @ibatorgenerated  Tue Sep 10 20:35:12 CST 2013
	 */
	public GoodsConfigDAOImpl(SqlMapClient sqlMapClient) {
		super();
		this.sqlMapClient = sqlMapClient;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table goods_config
	 * @ibatorgenerated  Tue Sep 10 20:35:12 CST 2013
	 */
	public int countByExample(GoodsConfigExample example) throws SQLException {
		Integer count = (Integer) sqlMapClient.queryForObject(
				"goods_config.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table goods_config
	 * @ibatorgenerated  Tue Sep 10 20:35:12 CST 2013
	 */
	public int deleteByExample(GoodsConfigExample example) throws SQLException {
		int rows = sqlMapClient.delete(
				"goods_config.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table goods_config
	 * @ibatorgenerated  Tue Sep 10 20:35:12 CST 2013
	 */
	public int deleteByPrimaryKey(Integer id) throws SQLException {
		GoodsConfig key = new GoodsConfig();
		key.setId(id);
		int rows = sqlMapClient.delete(
				"goods_config.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table goods_config
	 * @ibatorgenerated  Tue Sep 10 20:35:12 CST 2013
	 */
	public Integer insert(GoodsConfig record) throws SQLException {
		Object newKey = sqlMapClient.insert(
				"goods_config.ibatorgenerated_insert", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table goods_config
	 * @ibatorgenerated  Tue Sep 10 20:35:12 CST 2013
	 */
	public Integer insertSelective(GoodsConfig record) throws SQLException {
		Object newKey = sqlMapClient.insert(
				"goods_config.ibatorgenerated_insertSelective", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table goods_config
	 * @ibatorgenerated  Tue Sep 10 20:35:12 CST 2013
	 */
	public List selectByExample(GoodsConfigExample example) throws SQLException {
		List list = sqlMapClient.queryForList(
				"goods_config.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table goods_config
	 * @ibatorgenerated  Tue Sep 10 20:35:12 CST 2013
	 */
	public GoodsConfig selectByPrimaryKey(Integer id) throws SQLException {
		GoodsConfig key = new GoodsConfig();
		key.setId(id);
		GoodsConfig record = (GoodsConfig) sqlMapClient.queryForObject(
				"goods_config.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table goods_config
	 * @ibatorgenerated  Tue Sep 10 20:35:12 CST 2013
	 */
	public int updateByExampleSelective(GoodsConfig record,
			GoodsConfigExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"goods_config.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table goods_config
	 * @ibatorgenerated  Tue Sep 10 20:35:12 CST 2013
	 */
	public int updateByExample(GoodsConfig record, GoodsConfigExample example)
			throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"goods_config.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table goods_config
	 * @ibatorgenerated  Tue Sep 10 20:35:12 CST 2013
	 */
	public int updateByPrimaryKeySelective(GoodsConfig record)
			throws SQLException {
		int rows = sqlMapClient.update(
				"goods_config.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table goods_config
	 * @ibatorgenerated  Tue Sep 10 20:35:12 CST 2013
	 */
	public int updateByPrimaryKey(GoodsConfig record) throws SQLException {
		int rows = sqlMapClient.update(
				"goods_config.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table goods_config
	 * @ibatorgenerated  Tue Sep 10 20:35:12 CST 2013
	 */
	private static class UpdateByExampleParms extends GoodsConfigExample {
		private Object record;

		public UpdateByExampleParms(Object record, GoodsConfigExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}