package com.orange.goldgame.system.dao;

import java.sql.SQLException;
import java.util.List;

import com.orange.goldgame.domain.HelpType;
import com.orange.goldgame.domain.HelpTypeExample;

public interface HelpTypeDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table help_type
     *
     * @ibatorgenerated Wed Jul 24 10:23:54 CST 2013
     */
    int countByExample(HelpTypeExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table help_type
     *
     * @ibatorgenerated Wed Jul 24 10:23:54 CST 2013
     */
    int deleteByExample(HelpTypeExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table help_type
     *
     * @ibatorgenerated Wed Jul 24 10:23:54 CST 2013
     */
    int deleteByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table help_type
     *
     * @ibatorgenerated Wed Jul 24 10:23:54 CST 2013
     */
    Integer insert(HelpType record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table help_type
     *
     * @ibatorgenerated Wed Jul 24 10:23:54 CST 2013
     */
    Integer insertSelective(HelpType record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table help_type
     *
     * @ibatorgenerated Wed Jul 24 10:23:54 CST 2013
     */
    List selectByExample(HelpTypeExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table help_type
     *
     * @ibatorgenerated Wed Jul 24 10:23:54 CST 2013
     */
    HelpType selectByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table help_type
     *
     * @ibatorgenerated Wed Jul 24 10:23:54 CST 2013
     */
    int updateByExampleSelective(HelpType record, HelpTypeExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table help_type
     *
     * @ibatorgenerated Wed Jul 24 10:23:54 CST 2013
     */
    int updateByExample(HelpType record, HelpTypeExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table help_type
     *
     * @ibatorgenerated Wed Jul 24 10:23:54 CST 2013
     */
    int updateByPrimaryKeySelective(HelpType record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table help_type
     *
     * @ibatorgenerated Wed Jul 24 10:23:54 CST 2013
     */
    int updateByPrimaryKey(HelpType record) throws SQLException;
}