package com.orange.goldgame.system.dao;

import java.sql.SQLException;
import java.util.List;

import com.orange.goldgame.domain.HelpQa;
import com.orange.goldgame.domain.HelpQaExample;

public interface HelpQaDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table help_qa
	 * @ibatorgenerated  Wed Jul 24 10:22:52 CST 2013
	 */
	int countByExample(HelpQaExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table help_qa
	 * @ibatorgenerated  Wed Jul 24 10:22:52 CST 2013
	 */
	int deleteByExample(HelpQaExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table help_qa
	 * @ibatorgenerated  Wed Jul 24 10:22:52 CST 2013
	 */
	int deleteByPrimaryKey(Integer id) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table help_qa
	 * @ibatorgenerated  Wed Jul 24 10:22:52 CST 2013
	 */
	Integer insert(HelpQa record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table help_qa
	 * @ibatorgenerated  Wed Jul 24 10:22:52 CST 2013
	 */
	Integer insertSelective(HelpQa record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table help_qa
	 * @ibatorgenerated  Wed Jul 24 10:22:52 CST 2013
	 */
	List selectByExample(HelpQaExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table help_qa
	 * @ibatorgenerated  Wed Jul 24 10:22:52 CST 2013
	 */
	HelpQa selectByPrimaryKey(Integer id) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table help_qa
	 * @ibatorgenerated  Wed Jul 24 10:22:52 CST 2013
	 */
	int updateByExampleSelective(HelpQa record, HelpQaExample example)
			throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table help_qa
	 * @ibatorgenerated  Wed Jul 24 10:22:52 CST 2013
	 */
	int updateByExample(HelpQa record, HelpQaExample example)
			throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table help_qa
	 * @ibatorgenerated  Wed Jul 24 10:22:52 CST 2013
	 */
	int updateByPrimaryKeySelective(HelpQa record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table help_qa
	 * @ibatorgenerated  Wed Jul 24 10:22:52 CST 2013
	 */
	int updateByPrimaryKey(HelpQa record) throws SQLException;
}