package com.orange.goldgame.system.dao;

import java.sql.SQLException;
import java.util.List;

import com.orange.goldgame.domain.PayInfo;
import com.orange.goldgame.domain.PayInfoExample;

public interface PayInfoDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table pay_info
	 * @abatorgenerated  Thu Apr 17 14:51:09 CST 2014
	 */
	Integer insert(PayInfo record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table pay_info
	 * @abatorgenerated  Thu Apr 17 14:51:09 CST 2014
	 */
	int updateByPrimaryKey(PayInfo record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table pay_info
	 * @abatorgenerated  Thu Apr 17 14:51:09 CST 2014
	 */
	int updateByPrimaryKeySelective(PayInfo record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table pay_info
	 * @abatorgenerated  Thu Apr 17 14:51:09 CST 2014
	 */
	List<PayInfo> selectByExample(PayInfoExample example) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table pay_info
	 * @abatorgenerated  Thu Apr 17 14:51:09 CST 2014
	 */
	PayInfo selectByPrimaryKey(Integer id) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table pay_info
	 * @abatorgenerated  Thu Apr 17 14:51:09 CST 2014
	 */
	int deleteByExample(PayInfoExample example) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table pay_info
	 * @abatorgenerated  Thu Apr 17 14:51:09 CST 2014
	 */
	int deleteByPrimaryKey(Integer id) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table pay_info
	 * @abatorgenerated  Thu Apr 17 14:51:09 CST 2014
	 */
	int countByExample(PayInfoExample example) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table pay_info
	 * @abatorgenerated  Thu Apr 17 14:51:09 CST 2014
	 */
	int updateByExampleSelective(PayInfo record, PayInfoExample example)
			throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table pay_info
	 * @abatorgenerated  Thu Apr 17 14:51:09 CST 2014
	 */
	int updateByExample(PayInfo record, PayInfoExample example)
			throws SQLException;
}