package com.orange.goldgame.system.dao;

import java.sql.SQLException;
import java.util.List;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.orange.goldgame.domain.PayOrder;
import com.orange.goldgame.domain.PayOrderExample;

public class PayOrderDAOImpl implements PayOrderDAO {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table pay_order
     *
     * @ibatorgenerated Wed Feb 26 15:34:31 CST 2014
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pay_order
     *
     * @ibatorgenerated Wed Feb 26 15:34:31 CST 2014
     */
    public PayOrderDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pay_order
     *
     * @ibatorgenerated Wed Feb 26 15:34:31 CST 2014
     */
    public int countByExample(PayOrderExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("pay_order.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pay_order
     *
     * @ibatorgenerated Wed Feb 26 15:34:31 CST 2014
     */
    public int deleteByExample(PayOrderExample example) throws SQLException {
        int rows = sqlMapClient.delete("pay_order.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pay_order
     *
     * @ibatorgenerated Wed Feb 26 15:34:31 CST 2014
     */
    public int deleteByPrimaryKey(Integer id) throws SQLException {
        PayOrder key = new PayOrder();
        key.setId(id);
        int rows = sqlMapClient.delete("pay_order.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pay_order
     *
     * @ibatorgenerated Wed Feb 26 15:34:31 CST 2014
     */
    public Integer insert(PayOrder record) throws SQLException {
        Object newKey = sqlMapClient.insert("pay_order.ibatorgenerated_insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pay_order
     *
     * @ibatorgenerated Wed Feb 26 15:34:31 CST 2014
     */
    public Integer insertSelective(PayOrder record) throws SQLException {
        Object newKey = sqlMapClient.insert("pay_order.ibatorgenerated_insertSelective", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pay_order
     *
     * @ibatorgenerated Wed Feb 26 15:34:31 CST 2014
     */
    public List selectByExample(PayOrderExample example) throws SQLException {
        List list = sqlMapClient.queryForList("pay_order.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pay_order
     *
     * @ibatorgenerated Wed Feb 26 15:34:31 CST 2014
     */
    public PayOrder selectByPrimaryKey(Integer id) throws SQLException {
        PayOrder key = new PayOrder();
        key.setId(id);
        PayOrder record = (PayOrder) sqlMapClient.queryForObject("pay_order.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pay_order
     *
     * @ibatorgenerated Wed Feb 26 15:34:31 CST 2014
     */
    public int updateByExampleSelective(PayOrder record, PayOrderExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("pay_order.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pay_order
     *
     * @ibatorgenerated Wed Feb 26 15:34:31 CST 2014
     */
    public int updateByExample(PayOrder record, PayOrderExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("pay_order.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pay_order
     *
     * @ibatorgenerated Wed Feb 26 15:34:31 CST 2014
     */
    public int updateByPrimaryKeySelective(PayOrder record) throws SQLException {
        int rows = sqlMapClient.update("pay_order.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pay_order
     *
     * @ibatorgenerated Wed Feb 26 15:34:31 CST 2014
     */
    public int updateByPrimaryKey(PayOrder record) throws SQLException {
        int rows = sqlMapClient.update("pay_order.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table pay_order
     *
     * @ibatorgenerated Wed Feb 26 15:34:31 CST 2014
     */
    private static class UpdateByExampleParms extends PayOrderExample {
        private Object record;

        public UpdateByExampleParms(Object record, PayOrderExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}