package com.orange.goldgame.system.dao;

import java.sql.SQLException;
import java.util.List;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.orange.goldgame.domain.PlayerActivityCpa;
import com.orange.goldgame.domain.PlayerActivityCpaExample;

public class PlayerActivityCpaDAOImpl implements PlayerActivityCpaDAO {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table player_activity_cpa
	 * @abatorgenerated  Thu Apr 10 14:16:42 CST 2014
	 */
	private SqlMapClient sqlMapClient;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table player_activity_cpa
	 * @abatorgenerated  Thu Apr 10 14:16:42 CST 2014
	 */
	public PlayerActivityCpaDAOImpl(SqlMapClient sqlMapClient) {
		super();
		this.sqlMapClient = sqlMapClient;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table player_activity_cpa
	 * @abatorgenerated  Thu Apr 10 14:16:42 CST 2014
	 */
	public Integer insert(PlayerActivityCpa record) throws SQLException {
		Object newKey = sqlMapClient.insert(
				"player_activity_cpa.abatorgenerated_insert", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table player_activity_cpa
	 * @abatorgenerated  Thu Apr 10 14:16:42 CST 2014
	 */
	public int updateByPrimaryKey(PlayerActivityCpa record) throws SQLException {
		int rows = sqlMapClient.update(
				"player_activity_cpa.abatorgenerated_updateByPrimaryKey",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table player_activity_cpa
	 * @abatorgenerated  Thu Apr 10 14:16:42 CST 2014
	 */
	public int updateByPrimaryKeySelective(PlayerActivityCpa record)
			throws SQLException {
		int rows = sqlMapClient
				.update("player_activity_cpa.abatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table player_activity_cpa
	 * @abatorgenerated  Thu Apr 10 14:16:42 CST 2014
	 */
	@SuppressWarnings("unchecked")
	public List<PlayerActivityCpa> selectByExample(
			PlayerActivityCpaExample example) throws SQLException {
		List<PlayerActivityCpa> list = (List<PlayerActivityCpa>) sqlMapClient
				.queryForList(
						"player_activity_cpa.abatorgenerated_selectByExample",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table player_activity_cpa
	 * @abatorgenerated  Thu Apr 10 14:16:42 CST 2014
	 */
	public PlayerActivityCpa selectByPrimaryKey(Integer id) throws SQLException {
		PlayerActivityCpa key = new PlayerActivityCpa();
		key.setId(id);
		PlayerActivityCpa record = (PlayerActivityCpa) sqlMapClient
				.queryForObject(
						"player_activity_cpa.abatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table player_activity_cpa
	 * @abatorgenerated  Thu Apr 10 14:16:42 CST 2014
	 */
	public int deleteByExample(PlayerActivityCpaExample example)
			throws SQLException {
		int rows = sqlMapClient.delete(
				"player_activity_cpa.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table player_activity_cpa
	 * @abatorgenerated  Thu Apr 10 14:16:42 CST 2014
	 */
	public int deleteByPrimaryKey(Integer id) throws SQLException {
		PlayerActivityCpa key = new PlayerActivityCpa();
		key.setId(id);
		int rows = sqlMapClient.delete(
				"player_activity_cpa.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table player_activity_cpa
	 * @abatorgenerated  Thu Apr 10 14:16:42 CST 2014
	 */
	public int countByExample(PlayerActivityCpaExample example)
			throws SQLException {
		Integer count = (Integer) sqlMapClient.queryForObject(
				"player_activity_cpa.abatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table player_activity_cpa
	 * @abatorgenerated  Thu Apr 10 14:16:42 CST 2014
	 */
	public int updateByExampleSelective(PlayerActivityCpa record,
			PlayerActivityCpaExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"player_activity_cpa.abatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table player_activity_cpa
	 * @abatorgenerated  Thu Apr 10 14:16:42 CST 2014
	 */
	public int updateByExample(PlayerActivityCpa record,
			PlayerActivityCpaExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"player_activity_cpa.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table player_activity_cpa
	 * @abatorgenerated  Thu Apr 10 14:16:42 CST 2014
	 */
	private static class UpdateByExampleParms extends PlayerActivityCpaExample {
		private Object record;

		public UpdateByExampleParms(Object record,
				PlayerActivityCpaExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}