package com.orange.goldgame.system.dao;

import java.sql.SQLException;
import java.util.List;

import com.orange.goldgame.domain.PlayerFriend;
import com.orange.goldgame.domain.PlayerFriendExample;

public interface PlayerFriendDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table player_friend
     *
     * @abatorgenerated Sat Mar 29 10:20:46 CST 2014
     */
    Integer insert(PlayerFriend record) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table player_friend
     *
     * @abatorgenerated Sat Mar 29 10:20:46 CST 2014
     */
    int updateByPrimaryKey(PlayerFriend record) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table player_friend
     *
     * @abatorgenerated Sat Mar 29 10:20:46 CST 2014
     */
    int updateByPrimaryKeySelective(PlayerFriend record) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table player_friend
     *
     * @abatorgenerated Sat Mar 29 10:20:46 CST 2014
     */
    List<PlayerFriend> selectByExample(PlayerFriendExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table player_friend
     *
     * @abatorgenerated Sat Mar 29 10:20:46 CST 2014
     */
    PlayerFriend selectByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table player_friend
     *
     * @abatorgenerated Sat Mar 29 10:20:46 CST 2014
     */
    int deleteByExample(PlayerFriendExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table player_friend
     *
     * @abatorgenerated Sat Mar 29 10:20:46 CST 2014
     */
    int deleteByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table player_friend
     *
     * @abatorgenerated Sat Mar 29 10:20:46 CST 2014
     */
    int countByExample(PlayerFriendExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table player_friend
     *
     * @abatorgenerated Sat Mar 29 10:20:46 CST 2014
     */
    int updateByExampleSelective(PlayerFriend record, PlayerFriendExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table player_friend
     *
     * @abatorgenerated Sat Mar 29 10:20:46 CST 2014
     */
    int updateByExample(PlayerFriend record, PlayerFriendExample example) throws SQLException;
}