package com.orange.goldgame.system.dao;

import java.sql.SQLException;
import java.util.List;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.orange.goldgame.domain.PlayerFriend;
import com.orange.goldgame.domain.PlayerFriendExample;

public class PlayerFriendDAOImpl implements PlayerFriendDAO {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table player_friend
     *
     * @abatorgenerated Sat Mar 29 10:20:46 CST 2014
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table player_friend
     *
     * @abatorgenerated Sat Mar 29 10:20:46 CST 2014
     */
    public PlayerFriendDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table player_friend
     *
     * @abatorgenerated Sat Mar 29 10:20:46 CST 2014
     */
    public Integer insert(PlayerFriend record) throws SQLException {
        Object newKey = sqlMapClient.insert("player_friend.abatorgenerated_insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table player_friend
     *
     * @abatorgenerated Sat Mar 29 10:20:46 CST 2014
     */
    public int updateByPrimaryKey(PlayerFriend record) throws SQLException {
        int rows = sqlMapClient.update("player_friend.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table player_friend
     *
     * @abatorgenerated Sat Mar 29 10:20:46 CST 2014
     */
    public int updateByPrimaryKeySelective(PlayerFriend record) throws SQLException {
        int rows = sqlMapClient.update("player_friend.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table player_friend
     *
     * @abatorgenerated Sat Mar 29 10:20:46 CST 2014
     */
    @SuppressWarnings("unchecked")
    public List<PlayerFriend> selectByExample(PlayerFriendExample example) throws SQLException {
        List<PlayerFriend> list = (List<PlayerFriend>) sqlMapClient.queryForList("player_friend.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table player_friend
     *
     * @abatorgenerated Sat Mar 29 10:20:46 CST 2014
     */
    public PlayerFriend selectByPrimaryKey(Integer id) throws SQLException {
        PlayerFriend key = new PlayerFriend();
        key.setId(id);
        PlayerFriend record = (PlayerFriend) sqlMapClient.queryForObject("player_friend.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table player_friend
     *
     * @abatorgenerated Sat Mar 29 10:20:46 CST 2014
     */
    public int deleteByExample(PlayerFriendExample example) throws SQLException {
        int rows = sqlMapClient.delete("player_friend.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table player_friend
     *
     * @abatorgenerated Sat Mar 29 10:20:46 CST 2014
     */
    public int deleteByPrimaryKey(Integer id) throws SQLException {
        PlayerFriend key = new PlayerFriend();
        key.setId(id);
        int rows = sqlMapClient.delete("player_friend.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table player_friend
     *
     * @abatorgenerated Sat Mar 29 10:20:46 CST 2014
     */
    public int countByExample(PlayerFriendExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("player_friend.abatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table player_friend
     *
     * @abatorgenerated Sat Mar 29 10:20:46 CST 2014
     */
    public int updateByExampleSelective(PlayerFriend record, PlayerFriendExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("player_friend.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table player_friend
     *
     * @abatorgenerated Sat Mar 29 10:20:46 CST 2014
     */
    public int updateByExample(PlayerFriend record, PlayerFriendExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("player_friend.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table player_friend
     *
     * @abatorgenerated Sat Mar 29 10:20:46 CST 2014
     */
    private static class UpdateByExampleParms extends PlayerFriendExample {
        private Object record;

        public UpdateByExampleParms(Object record, PlayerFriendExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}