package com.orange.goldgame.system.dao;

import java.sql.SQLException;
import java.util.List;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.orange.goldgame.domain.PlayerInfoCenter;
import com.orange.goldgame.domain.PlayerInfoCenterExample;

public class PlayerInfoCenterDAOImpl implements PlayerInfoCenterDAO {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table player_info_center
	 * @abatorgenerated  Wed Mar 26 18:32:50 CST 2014
	 */
	private SqlMapClient sqlMapClient;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table player_info_center
	 * @abatorgenerated  Wed Mar 26 18:32:50 CST 2014
	 */
	public PlayerInfoCenterDAOImpl(SqlMapClient sqlMapClient) {
		super();
		this.sqlMapClient = sqlMapClient;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table player_info_center
	 * @abatorgenerated  Wed Mar 26 18:32:50 CST 2014
	 */
	public Integer insert(PlayerInfoCenter record) throws SQLException {
		Object newKey = sqlMapClient.insert(
				"player_info_center.abatorgenerated_insert", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table player_info_center
	 * @abatorgenerated  Wed Mar 26 18:32:50 CST 2014
	 */
	public int updateByPrimaryKey(PlayerInfoCenter record) throws SQLException {
		int rows = sqlMapClient
				.update("player_info_center.abatorgenerated_updateByPrimaryKey",
						record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table player_info_center
	 * @abatorgenerated  Wed Mar 26 18:32:50 CST 2014
	 */
	public int updateByPrimaryKeySelective(PlayerInfoCenter record)
			throws SQLException {
		int rows = sqlMapClient
				.update("player_info_center.abatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table player_info_center
	 * @abatorgenerated  Wed Mar 26 18:32:50 CST 2014
	 */
	@SuppressWarnings("unchecked")
	public List<PlayerInfoCenter> selectByExample(
			PlayerInfoCenterExample example) throws SQLException {
		List<PlayerInfoCenter> list = (List<PlayerInfoCenter>) sqlMapClient
				.queryForList(
						"player_info_center.abatorgenerated_selectByExample",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table player_info_center
	 * @abatorgenerated  Wed Mar 26 18:32:50 CST 2014
	 */
	public PlayerInfoCenter selectByPrimaryKey(Integer id) throws SQLException {
		PlayerInfoCenter key = new PlayerInfoCenter();
		key.setId(id);
		PlayerInfoCenter record = (PlayerInfoCenter) sqlMapClient
				.queryForObject(
						"player_info_center.abatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table player_info_center
	 * @abatorgenerated  Wed Mar 26 18:32:50 CST 2014
	 */
	public int deleteByExample(PlayerInfoCenterExample example)
			throws SQLException {
		int rows = sqlMapClient.delete(
				"player_info_center.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table player_info_center
	 * @abatorgenerated  Wed Mar 26 18:32:50 CST 2014
	 */
	public int deleteByPrimaryKey(Integer id) throws SQLException {
		PlayerInfoCenter key = new PlayerInfoCenter();
		key.setId(id);
		int rows = sqlMapClient.delete(
				"player_info_center.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table player_info_center
	 * @abatorgenerated  Wed Mar 26 18:32:50 CST 2014
	 */
	public int countByExample(PlayerInfoCenterExample example)
			throws SQLException {
		Integer count = (Integer) sqlMapClient.queryForObject(
				"player_info_center.abatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table player_info_center
	 * @abatorgenerated  Wed Mar 26 18:32:50 CST 2014
	 */
	public int updateByExampleSelective(PlayerInfoCenter record,
			PlayerInfoCenterExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"player_info_center.abatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table player_info_center
	 * @abatorgenerated  Wed Mar 26 18:32:50 CST 2014
	 */
	public int updateByExample(PlayerInfoCenter record,
			PlayerInfoCenterExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"player_info_center.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table player_info_center
	 * @abatorgenerated  Wed Mar 26 18:32:50 CST 2014
	 */
	private static class UpdateByExampleParms extends PlayerInfoCenterExample {
		private Object record;

		public UpdateByExampleParms(Object record,
				PlayerInfoCenterExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}