package com.orange.goldgame.system.dao;

import java.sql.SQLException;
import java.util.List;

import com.orange.goldgame.domain.PlayerWheelRecoder;
import com.orange.goldgame.domain.PlayerWheelRecoderExample;

public interface PlayerWheelRecoderDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table player_wheel_recoder
	 * @abatorgenerated  Mon Mar 31 13:53:50 CST 2014
	 */
	Integer insert(PlayerWheelRecoder record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table player_wheel_recoder
	 * @abatorgenerated  Mon Mar 31 13:53:50 CST 2014
	 */
	int updateByPrimaryKey(PlayerWheelRecoder record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table player_wheel_recoder
	 * @abatorgenerated  Mon Mar 31 13:53:50 CST 2014
	 */
	int updateByPrimaryKeySelective(PlayerWheelRecoder record)
			throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table player_wheel_recoder
	 * @abatorgenerated  Mon Mar 31 13:53:50 CST 2014
	 */
	List<PlayerWheelRecoder> selectByExample(PlayerWheelRecoderExample example)
			throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table player_wheel_recoder
	 * @abatorgenerated  Mon Mar 31 13:53:50 CST 2014
	 */
	PlayerWheelRecoder selectByPrimaryKey(Integer id) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table player_wheel_recoder
	 * @abatorgenerated  Mon Mar 31 13:53:50 CST 2014
	 */
	int deleteByExample(PlayerWheelRecoderExample example) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table player_wheel_recoder
	 * @abatorgenerated  Mon Mar 31 13:53:50 CST 2014
	 */
	int deleteByPrimaryKey(Integer id) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table player_wheel_recoder
	 * @abatorgenerated  Mon Mar 31 13:53:50 CST 2014
	 */
	int countByExample(PlayerWheelRecoderExample example) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table player_wheel_recoder
	 * @abatorgenerated  Mon Mar 31 13:53:50 CST 2014
	 */
	int updateByExampleSelective(PlayerWheelRecoder record,
			PlayerWheelRecoderExample example) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table player_wheel_recoder
	 * @abatorgenerated  Mon Mar 31 13:53:50 CST 2014
	 */
	int updateByExample(PlayerWheelRecoder record,
			PlayerWheelRecoderExample example) throws SQLException;
}