package com.orange.goldgame.system.dao;

import java.sql.SQLException;
import java.util.List;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.orange.goldgame.domain.PlayerMessage;
import com.orange.goldgame.domain.PlayerMessageExample;

public class PlayerMessageDAOImpl implements PlayerMessageDAO {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table player_message
     *
     * @ibatorgenerated Mon Dec 23 15:30:50 CST 2013
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_message
     *
     * @ibatorgenerated Mon Dec 23 15:30:50 CST 2013
     */
    public PlayerMessageDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_message
     *
     * @ibatorgenerated Mon Dec 23 15:30:50 CST 2013
     */
    public int countByExample(PlayerMessageExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("player_message.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_message
     *
     * @ibatorgenerated Mon Dec 23 15:30:50 CST 2013
     */
    public int deleteByExample(PlayerMessageExample example) throws SQLException {
        int rows = sqlMapClient.delete("player_message.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_message
     *
     * @ibatorgenerated Mon Dec 23 15:30:50 CST 2013
     */
    public int deleteByPrimaryKey(Integer id) throws SQLException {
        PlayerMessage key = new PlayerMessage();
        key.setId(id);
        int rows = sqlMapClient.delete("player_message.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_message
     *
     * @ibatorgenerated Mon Dec 23 15:30:50 CST 2013
     */
    public Integer insert(PlayerMessage record) throws SQLException {
        Object newKey = sqlMapClient.insert("player_message.ibatorgenerated_insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_message
     *
     * @ibatorgenerated Mon Dec 23 15:30:50 CST 2013
     */
    public Integer insertSelective(PlayerMessage record) throws SQLException {
        Object newKey = sqlMapClient.insert("player_message.ibatorgenerated_insertSelective", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_message
     *
     * @ibatorgenerated Mon Dec 23 15:30:50 CST 2013
     */
    public List selectByExample(PlayerMessageExample example) throws SQLException {
        List list = sqlMapClient.queryForList("player_message.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_message
     *
     * @ibatorgenerated Mon Dec 23 15:30:50 CST 2013
     */
    public PlayerMessage selectByPrimaryKey(Integer id) throws SQLException {
        PlayerMessage key = new PlayerMessage();
        key.setId(id);
        PlayerMessage record = (PlayerMessage) sqlMapClient.queryForObject("player_message.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_message
     *
     * @ibatorgenerated Mon Dec 23 15:30:50 CST 2013
     */
    public int updateByExampleSelective(PlayerMessage record, PlayerMessageExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("player_message.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_message
     *
     * @ibatorgenerated Mon Dec 23 15:30:50 CST 2013
     */
    public int updateByExample(PlayerMessage record, PlayerMessageExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("player_message.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_message
     *
     * @ibatorgenerated Mon Dec 23 15:30:50 CST 2013
     */
    public int updateByPrimaryKeySelective(PlayerMessage record) throws SQLException {
        int rows = sqlMapClient.update("player_message.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_message
     *
     * @ibatorgenerated Mon Dec 23 15:30:50 CST 2013
     */
    public int updateByPrimaryKey(PlayerMessage record) throws SQLException {
        int rows = sqlMapClient.update("player_message.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table player_message
     *
     * @ibatorgenerated Mon Dec 23 15:30:50 CST 2013
     */
    private static class UpdateByExampleParms extends PlayerMessageExample {
        private Object record;

        public UpdateByExampleParms(Object record, PlayerMessageExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}