package com.orange.goldgame.system.dao;

import java.sql.SQLException;
import java.util.List;

import com.orange.goldgame.domain.PlayerInfoCenter;
import com.orange.goldgame.domain.PlayerInfoCenterExample;

public interface PlayerInfoCenterDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table player_info_center
	 * @abatorgenerated  Wed Mar 26 18:32:50 CST 2014
	 */
	Integer insert(PlayerInfoCenter record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table player_info_center
	 * @abatorgenerated  Wed Mar 26 18:32:50 CST 2014
	 */
	int updateByPrimaryKey(PlayerInfoCenter record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table player_info_center
	 * @abatorgenerated  Wed Mar 26 18:32:50 CST 2014
	 */
	int updateByPrimaryKeySelective(PlayerInfoCenter record)
			throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table player_info_center
	 * @abatorgenerated  Wed Mar 26 18:32:50 CST 2014
	 */
	List<PlayerInfoCenter> selectByExample(PlayerInfoCenterExample example)
			throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table player_info_center
	 * @abatorgenerated  Wed Mar 26 18:32:50 CST 2014
	 */
	PlayerInfoCenter selectByPrimaryKey(Integer id) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table player_info_center
	 * @abatorgenerated  Wed Mar 26 18:32:50 CST 2014
	 */
	int deleteByExample(PlayerInfoCenterExample example) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table player_info_center
	 * @abatorgenerated  Wed Mar 26 18:32:50 CST 2014
	 */
	int deleteByPrimaryKey(Integer id) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table player_info_center
	 * @abatorgenerated  Wed Mar 26 18:32:50 CST 2014
	 */
	int countByExample(PlayerInfoCenterExample example) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table player_info_center
	 * @abatorgenerated  Wed Mar 26 18:32:50 CST 2014
	 */
	int updateByExampleSelective(PlayerInfoCenter record,
			PlayerInfoCenterExample example) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table player_info_center
	 * @abatorgenerated  Wed Mar 26 18:32:50 CST 2014
	 */
	int updateByExample(PlayerInfoCenter record, PlayerInfoCenterExample example)
			throws SQLException;
}