package com.orange.goldgame.system.dao;

import java.sql.SQLException;
import java.util.List;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.orange.goldgame.domain.PlayerPay;
import com.orange.goldgame.domain.PlayerPayExample;

public class PlayerPayDAOImpl implements PlayerPayDAO {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table player_pay
	 * @ibatorgenerated  Thu Oct 31 17:18:43 CST 2013
	 */
	private SqlMapClient sqlMapClient;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_pay
	 * @ibatorgenerated  Thu Oct 31 17:18:43 CST 2013
	 */
	public PlayerPayDAOImpl(SqlMapClient sqlMapClient) {
		super();
		this.sqlMapClient = sqlMapClient;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_pay
	 * @ibatorgenerated  Thu Oct 31 17:18:43 CST 2013
	 */
	public int countByExample(PlayerPayExample example) throws SQLException {
		Integer count = (Integer) sqlMapClient.queryForObject(
				"player_pay.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_pay
	 * @ibatorgenerated  Thu Oct 31 17:18:43 CST 2013
	 */
	public int deleteByExample(PlayerPayExample example) throws SQLException {
		int rows = sqlMapClient.delete(
				"player_pay.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_pay
	 * @ibatorgenerated  Thu Oct 31 17:18:43 CST 2013
	 */
	public int deleteByPrimaryKey(Integer id) throws SQLException {
		PlayerPay key = new PlayerPay();
		key.setId(id);
		int rows = sqlMapClient.delete(
				"player_pay.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_pay
	 * @ibatorgenerated  Thu Oct 31 17:18:43 CST 2013
	 */
	public Integer insert(PlayerPay record) throws SQLException {
		Object newKey = sqlMapClient.insert(
				"player_pay.ibatorgenerated_insert", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_pay
	 * @ibatorgenerated  Thu Oct 31 17:18:43 CST 2013
	 */
	public Integer insertSelective(PlayerPay record) throws SQLException {
		Object newKey = sqlMapClient.insert(
				"player_pay.ibatorgenerated_insertSelective", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_pay
	 * @ibatorgenerated  Thu Oct 31 17:18:43 CST 2013
	 */
	public List selectByExample(PlayerPayExample example) throws SQLException {
		List list = sqlMapClient.queryForList(
				"player_pay.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_pay
	 * @ibatorgenerated  Thu Oct 31 17:18:43 CST 2013
	 */
	public PlayerPay selectByPrimaryKey(Integer id) throws SQLException {
		PlayerPay key = new PlayerPay();
		key.setId(id);
		PlayerPay record = (PlayerPay) sqlMapClient.queryForObject(
				"player_pay.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_pay
	 * @ibatorgenerated  Thu Oct 31 17:18:43 CST 2013
	 */
	public int updateByExampleSelective(PlayerPay record,
			PlayerPayExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"player_pay.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_pay
	 * @ibatorgenerated  Thu Oct 31 17:18:43 CST 2013
	 */
	public int updateByExample(PlayerPay record, PlayerPayExample example)
			throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"player_pay.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_pay
	 * @ibatorgenerated  Thu Oct 31 17:18:43 CST 2013
	 */
	public int updateByPrimaryKeySelective(PlayerPay record)
			throws SQLException {
		int rows = sqlMapClient.update(
				"player_pay.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_pay
	 * @ibatorgenerated  Thu Oct 31 17:18:43 CST 2013
	 */
	public int updateByPrimaryKey(PlayerPay record) throws SQLException {
		int rows = sqlMapClient.update(
				"player_pay.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table player_pay
	 * @ibatorgenerated  Thu Oct 31 17:18:43 CST 2013
	 */
	private static class UpdateByExampleParms extends PlayerPayExample {
		private Object record;

		public UpdateByExampleParms(Object record, PlayerPayExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}