package com.orange.goldgame.system.dao;

import java.sql.SQLException;
import java.util.List;

import com.orange.goldgame.domain.PlayerWheelTimes;
import com.orange.goldgame.domain.PlayerWheelTimesExample;

public interface PlayerWheelTimesDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table player_wheel_times
     *
     * @abatorgenerated Wed Apr 09 11:52:48 CST 2014
     */
    Integer insert(PlayerWheelTimes record) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table player_wheel_times
     *
     * @abatorgenerated Wed Apr 09 11:52:48 CST 2014
     */
    int updateByPrimaryKey(PlayerWheelTimes record) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table player_wheel_times
     *
     * @abatorgenerated Wed Apr 09 11:52:48 CST 2014
     */
    int updateByPrimaryKeySelective(PlayerWheelTimes record) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table player_wheel_times
     *
     * @abatorgenerated Wed Apr 09 11:52:48 CST 2014
     */
    List<PlayerWheelTimes> selectByExample(PlayerWheelTimesExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table player_wheel_times
     *
     * @abatorgenerated Wed Apr 09 11:52:48 CST 2014
     */
    PlayerWheelTimes selectByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table player_wheel_times
     *
     * @abatorgenerated Wed Apr 09 11:52:48 CST 2014
     */
    int deleteByExample(PlayerWheelTimesExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table player_wheel_times
     *
     * @abatorgenerated Wed Apr 09 11:52:48 CST 2014
     */
    int deleteByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table player_wheel_times
     *
     * @abatorgenerated Wed Apr 09 11:52:48 CST 2014
     */
    int countByExample(PlayerWheelTimesExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table player_wheel_times
     *
     * @abatorgenerated Wed Apr 09 11:52:48 CST 2014
     */
    int updateByExampleSelective(PlayerWheelTimes record, PlayerWheelTimesExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table player_wheel_times
     *
     * @abatorgenerated Wed Apr 09 11:52:48 CST 2014
     */
    int updateByExample(PlayerWheelTimes record, PlayerWheelTimesExample example) throws SQLException;
}