package com.orange.goldgame.system.dao;

import java.sql.SQLException;
import java.util.List;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.orange.goldgame.domain.Player;
import com.orange.goldgame.domain.PlayerExample;

public class PlayerDAOImpl implements PlayerDAO {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table player
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	private SqlMapClient sqlMapClient;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	public PlayerDAOImpl(SqlMapClient sqlMapClient) {
		super();
		this.sqlMapClient = sqlMapClient;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	public int countByExample(PlayerExample example) throws SQLException {
		Integer count = (Integer) sqlMapClient.queryForObject(
				"player.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	public int deleteByExample(PlayerExample example) throws SQLException {
		int rows = sqlMapClient.delete(
				"player.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	public int deleteByPrimaryKey(Integer id) throws SQLException {
		Player key = new Player();
		key.setId(id);
		int rows = sqlMapClient.delete(
				"player.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	public Integer insert(Player record) throws SQLException {
		Object newKey = sqlMapClient.insert("player.ibatorgenerated_insert",
				record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	public Integer insertSelective(Player record) throws SQLException {
		Object newKey = sqlMapClient.insert(
				"player.ibatorgenerated_insertSelective", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	public List selectByExample(PlayerExample example) throws SQLException {
		List list = sqlMapClient.queryForList(
				"player.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	public Player selectByPrimaryKey(Integer id) throws SQLException {
		Player key = new Player();
		key.setId(id);
		Player record = (Player) sqlMapClient.queryForObject(
				"player.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	public int updateByExampleSelective(Player record, PlayerExample example)
			throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"player.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	public int updateByExample(Player record, PlayerExample example)
			throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"player.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	public int updateByPrimaryKeySelective(Player record) throws SQLException {
		int rows = sqlMapClient.update(
				"player.ibatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	public int updateByPrimaryKey(Player record) throws SQLException {
		int rows = sqlMapClient.update(
				"player.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table player
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	private static class UpdateByExampleParms extends PlayerExample {
		private Object record;

		public UpdateByExampleParms(Object record, PlayerExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}