package com.orange.goldgame.system.dao;

import java.sql.SQLException;
import java.util.List;

import com.orange.goldgame.domain.Prop;
import com.orange.goldgame.domain.PropExample;

public interface PropDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table prop
	 * @ibatorgenerated  Mon Jul 08 14:19:26 CST 2013
	 */
	int countByExample(PropExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table prop
	 * @ibatorgenerated  Mon Jul 08 14:19:26 CST 2013
	 */
	int deleteByExample(PropExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table prop
	 * @ibatorgenerated  Mon Jul 08 14:19:26 CST 2013
	 */
	int deleteByPrimaryKey(Integer propid) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table prop
	 * @ibatorgenerated  Mon Jul 08 14:19:26 CST 2013
	 */
	void insert(Prop record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table prop
	 * @ibatorgenerated  Mon Jul 08 14:19:26 CST 2013
	 */
	void insertSelective(Prop record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table prop
	 * @ibatorgenerated  Mon Jul 08 14:19:26 CST 2013
	 */
	List selectByExample(PropExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table prop
	 * @ibatorgenerated  Mon Jul 08 14:19:26 CST 2013
	 */
	Prop selectByPrimaryKey(Integer propid) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table prop
	 * @ibatorgenerated  Mon Jul 08 14:19:26 CST 2013
	 */
	int updateByExampleSelective(Prop record, PropExample example)
			throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table prop
	 * @ibatorgenerated  Mon Jul 08 14:19:26 CST 2013
	 */
	int updateByExample(Prop record, PropExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table prop
	 * @ibatorgenerated  Mon Jul 08 14:19:26 CST 2013
	 */
	int updateByPrimaryKeySelective(Prop record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table prop
	 * @ibatorgenerated  Mon Jul 08 14:19:26 CST 2013
	 */
	int updateByPrimaryKey(Prop record) throws SQLException;
}