package com.orange.goldgame.system.dao;

import java.sql.SQLException;
import java.util.List;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.orange.goldgame.domain.Prop;
import com.orange.goldgame.domain.PropExample;

public class PropDAOImpl implements PropDAO {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table prop
	 * @ibatorgenerated  Mon Jul 08 14:19:26 CST 2013
	 */
	private SqlMapClient sqlMapClient;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table prop
	 * @ibatorgenerated  Mon Jul 08 14:19:26 CST 2013
	 */
	public PropDAOImpl(SqlMapClient sqlMapClient) {
		super();
		this.sqlMapClient = sqlMapClient;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table prop
	 * @ibatorgenerated  Mon Jul 08 14:19:26 CST 2013
	 */
	public int countByExample(PropExample example) throws SQLException {
		Integer count = (Integer) sqlMapClient.queryForObject(
				"prop.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table prop
	 * @ibatorgenerated  Mon Jul 08 14:19:26 CST 2013
	 */
	public int deleteByExample(PropExample example) throws SQLException {
		int rows = sqlMapClient.delete("prop.ibatorgenerated_deleteByExample",
				example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table prop
	 * @ibatorgenerated  Mon Jul 08 14:19:26 CST 2013
	 */
	public int deleteByPrimaryKey(Integer propid) throws SQLException {
		Prop key = new Prop();
		key.setPropid(propid);
		int rows = sqlMapClient.delete(
				"prop.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table prop
	 * @ibatorgenerated  Mon Jul 08 14:19:26 CST 2013
	 */
	public void insert(Prop record) throws SQLException {
		sqlMapClient.insert("prop.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table prop
	 * @ibatorgenerated  Mon Jul 08 14:19:26 CST 2013
	 */
	public void insertSelective(Prop record) throws SQLException {
		sqlMapClient.insert("prop.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table prop
	 * @ibatorgenerated  Mon Jul 08 14:19:26 CST 2013
	 */
	public List selectByExample(PropExample example) throws SQLException {
		List list = sqlMapClient.queryForList(
				"prop.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table prop
	 * @ibatorgenerated  Mon Jul 08 14:19:26 CST 2013
	 */
	public Prop selectByPrimaryKey(Integer propid) throws SQLException {
		Prop key = new Prop();
		key.setPropid(propid);
		Prop record = (Prop) sqlMapClient.queryForObject(
				"prop.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table prop
	 * @ibatorgenerated  Mon Jul 08 14:19:26 CST 2013
	 */
	public int updateByExampleSelective(Prop record, PropExample example)
			throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"prop.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table prop
	 * @ibatorgenerated  Mon Jul 08 14:19:26 CST 2013
	 */
	public int updateByExample(Prop record, PropExample example)
			throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update("prop.ibatorgenerated_updateByExample",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table prop
	 * @ibatorgenerated  Mon Jul 08 14:19:26 CST 2013
	 */
	public int updateByPrimaryKeySelective(Prop record) throws SQLException {
		int rows = sqlMapClient.update(
				"prop.ibatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table prop
	 * @ibatorgenerated  Mon Jul 08 14:19:26 CST 2013
	 */
	public int updateByPrimaryKey(Prop record) throws SQLException {
		int rows = sqlMapClient.update(
				"prop.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table prop
	 * @ibatorgenerated  Mon Jul 08 14:19:26 CST 2013
	 */
	private static class UpdateByExampleParms extends PropExample {
		private Object record;

		public UpdateByExampleParms(Object record, PropExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}