package com.orange.goldgame.system.dao;

import java.sql.SQLException;
import java.util.List;

import com.orange.goldgame.domain.RobotPre;
import com.orange.goldgame.domain.RobotPreExample;

public interface RobotPreDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table robot_pre
	 * @ibatorgenerated  Wed Jul 17 17:51:47 CST 2013
	 */
	int countByExample(RobotPreExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table robot_pre
	 * @ibatorgenerated  Wed Jul 17 17:51:47 CST 2013
	 */
	int deleteByExample(RobotPreExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table robot_pre
	 * @ibatorgenerated  Wed Jul 17 17:51:47 CST 2013
	 */
	int deleteByPrimaryKey(Integer id) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table robot_pre
	 * @ibatorgenerated  Wed Jul 17 17:51:47 CST 2013
	 */
	Integer insert(RobotPre record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table robot_pre
	 * @ibatorgenerated  Wed Jul 17 17:51:47 CST 2013
	 */
	Integer insertSelective(RobotPre record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table robot_pre
	 * @ibatorgenerated  Wed Jul 17 17:51:47 CST 2013
	 */
	List selectByExample(RobotPreExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table robot_pre
	 * @ibatorgenerated  Wed Jul 17 17:51:47 CST 2013
	 */
	RobotPre selectByPrimaryKey(Integer id) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table robot_pre
	 * @ibatorgenerated  Wed Jul 17 17:51:47 CST 2013
	 */
	int updateByExampleSelective(RobotPre record, RobotPreExample example)
			throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table robot_pre
	 * @ibatorgenerated  Wed Jul 17 17:51:47 CST 2013
	 */
	int updateByExample(RobotPre record, RobotPreExample example)
			throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table robot_pre
	 * @ibatorgenerated  Wed Jul 17 17:51:47 CST 2013
	 */
	int updateByPrimaryKeySelective(RobotPre record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table robot_pre
	 * @ibatorgenerated  Wed Jul 17 17:51:47 CST 2013
	 */
	int updateByPrimaryKey(RobotPre record) throws SQLException;
}