package com.orange.goldgame.system.dao;

import java.sql.SQLException;
import java.util.List;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.orange.goldgame.domain.SealInfo;
import com.orange.goldgame.domain.SealInfoExample;

public class SealInfoDAOImpl implements SealInfoDAO {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table seal_info
	 * @ibatorgenerated  Sat Jan 18 15:10:51 CST 2014
	 */
	private SqlMapClient sqlMapClient;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table seal_info
	 * @ibatorgenerated  Sat Jan 18 15:10:51 CST 2014
	 */
	public SealInfoDAOImpl(SqlMapClient sqlMapClient) {
		super();
		this.sqlMapClient = sqlMapClient;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table seal_info
	 * @ibatorgenerated  Sat Jan 18 15:10:51 CST 2014
	 */
	public int countByExample(SealInfoExample example) throws SQLException {
		Integer count = (Integer) sqlMapClient.queryForObject(
				"seal_info.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table seal_info
	 * @ibatorgenerated  Sat Jan 18 15:10:51 CST 2014
	 */
	public int deleteByExample(SealInfoExample example) throws SQLException {
		int rows = sqlMapClient.delete(
				"seal_info.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table seal_info
	 * @ibatorgenerated  Sat Jan 18 15:10:51 CST 2014
	 */
	public int deleteByPrimaryKey(Integer playerId) throws SQLException {
		SealInfo key = new SealInfo();
		key.setPlayerId(playerId);
		int rows = sqlMapClient.delete(
				"seal_info.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table seal_info
	 * @ibatorgenerated  Sat Jan 18 15:10:51 CST 2014
	 */
	public void insert(SealInfo record) throws SQLException {
		sqlMapClient.insert("seal_info.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table seal_info
	 * @ibatorgenerated  Sat Jan 18 15:10:51 CST 2014
	 */
	public void insertSelective(SealInfo record) throws SQLException {
		sqlMapClient
				.insert("seal_info.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table seal_info
	 * @ibatorgenerated  Sat Jan 18 15:10:51 CST 2014
	 */
	public List selectByExample(SealInfoExample example) throws SQLException {
		List list = sqlMapClient.queryForList(
				"seal_info.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table seal_info
	 * @ibatorgenerated  Sat Jan 18 15:10:51 CST 2014
	 */
	public SealInfo selectByPrimaryKey(Integer playerId) throws SQLException {
		SealInfo key = new SealInfo();
		key.setPlayerId(playerId);
		SealInfo record = (SealInfo) sqlMapClient.queryForObject(
				"seal_info.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table seal_info
	 * @ibatorgenerated  Sat Jan 18 15:10:51 CST 2014
	 */
	public int updateByExampleSelective(SealInfo record, SealInfoExample example)
			throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"seal_info.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table seal_info
	 * @ibatorgenerated  Sat Jan 18 15:10:51 CST 2014
	 */
	public int updateByExample(SealInfo record, SealInfoExample example)
			throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"seal_info.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table seal_info
	 * @ibatorgenerated  Sat Jan 18 15:10:51 CST 2014
	 */
	public int updateByPrimaryKeySelective(SealInfo record) throws SQLException {
		int rows = sqlMapClient
				.update("seal_info.ibatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table seal_info
	 * @ibatorgenerated  Sat Jan 18 15:10:51 CST 2014
	 */
	public int updateByPrimaryKey(SealInfo record) throws SQLException {
		int rows = sqlMapClient.update(
				"seal_info.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table seal_info
	 * @ibatorgenerated  Sat Jan 18 15:10:51 CST 2014
	 */
	private static class UpdateByExampleParms extends SealInfoExample {
		private Object record;

		public UpdateByExampleParms(Object record, SealInfoExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}