package com.orange.goldgame.system.dao;

import java.sql.SQLException;
import java.util.List;

import com.orange.goldgame.domain.SealInfo;
import com.orange.goldgame.domain.SealInfoExample;

public interface SealInfoDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table seal_info
	 * @ibatorgenerated  Sat Jan 18 15:10:51 CST 2014
	 */
	int countByExample(SealInfoExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table seal_info
	 * @ibatorgenerated  Sat Jan 18 15:10:51 CST 2014
	 */
	int deleteByExample(SealInfoExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table seal_info
	 * @ibatorgenerated  Sat Jan 18 15:10:51 CST 2014
	 */
	int deleteByPrimaryKey(Integer playerId) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table seal_info
	 * @ibatorgenerated  Sat Jan 18 15:10:51 CST 2014
	 */
	void insert(SealInfo record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table seal_info
	 * @ibatorgenerated  Sat Jan 18 15:10:51 CST 2014
	 */
	void insertSelective(SealInfo record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table seal_info
	 * @ibatorgenerated  Sat Jan 18 15:10:51 CST 2014
	 */
	List selectByExample(SealInfoExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table seal_info
	 * @ibatorgenerated  Sat Jan 18 15:10:51 CST 2014
	 */
	SealInfo selectByPrimaryKey(Integer playerId) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table seal_info
	 * @ibatorgenerated  Sat Jan 18 15:10:51 CST 2014
	 */
	int updateByExampleSelective(SealInfo record, SealInfoExample example)
			throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table seal_info
	 * @ibatorgenerated  Sat Jan 18 15:10:51 CST 2014
	 */
	int updateByExample(SealInfo record, SealInfoExample example)
			throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table seal_info
	 * @ibatorgenerated  Sat Jan 18 15:10:51 CST 2014
	 */
	int updateByPrimaryKeySelective(SealInfo record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table seal_info
	 * @ibatorgenerated  Sat Jan 18 15:10:51 CST 2014
	 */
	int updateByPrimaryKey(SealInfo record) throws SQLException;
}