package com.orange.goldgame.system.dao;

import java.sql.SQLException;
import java.util.List;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.orange.goldgame.domain.ServerConfig;
import com.orange.goldgame.domain.ServerConfigExample;

public class ServerConfigDAOImpl implements ServerConfigDAO {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table server_config
     *
     * @abatorgenerated Wed Apr 02 17:48:42 CST 2014
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table server_config
     *
     * @abatorgenerated Wed Apr 02 17:48:42 CST 2014
     */
    public ServerConfigDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table server_config
     *
     * @abatorgenerated Wed Apr 02 17:48:42 CST 2014
     */
    public Integer insert(ServerConfig record) throws SQLException {
        Object newKey = sqlMapClient.insert("server_config.abatorgenerated_insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table server_config
     *
     * @abatorgenerated Wed Apr 02 17:48:42 CST 2014
     */
    public int updateByPrimaryKey(ServerConfig record) throws SQLException {
        int rows = sqlMapClient.update("server_config.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table server_config
     *
     * @abatorgenerated Wed Apr 02 17:48:42 CST 2014
     */
    public int updateByPrimaryKeySelective(ServerConfig record) throws SQLException {
        int rows = sqlMapClient.update("server_config.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table server_config
     *
     * @abatorgenerated Wed Apr 02 17:48:42 CST 2014
     */
    @SuppressWarnings("unchecked")
    public List<ServerConfig> selectByExample(ServerConfigExample example) throws SQLException {
        List<ServerConfig> list = (List<ServerConfig>) sqlMapClient.queryForList("server_config.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table server_config
     *
     * @abatorgenerated Wed Apr 02 17:48:42 CST 2014
     */
    public ServerConfig selectByPrimaryKey(Integer id) throws SQLException {
        ServerConfig key = new ServerConfig();
        key.setId(id);
        ServerConfig record = (ServerConfig) sqlMapClient.queryForObject("server_config.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table server_config
     *
     * @abatorgenerated Wed Apr 02 17:48:42 CST 2014
     */
    public int deleteByExample(ServerConfigExample example) throws SQLException {
        int rows = sqlMapClient.delete("server_config.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table server_config
     *
     * @abatorgenerated Wed Apr 02 17:48:42 CST 2014
     */
    public int deleteByPrimaryKey(Integer id) throws SQLException {
        ServerConfig key = new ServerConfig();
        key.setId(id);
        int rows = sqlMapClient.delete("server_config.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table server_config
     *
     * @abatorgenerated Wed Apr 02 17:48:42 CST 2014
     */
    public int countByExample(ServerConfigExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("server_config.abatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table server_config
     *
     * @abatorgenerated Wed Apr 02 17:48:42 CST 2014
     */
    public int updateByExampleSelective(ServerConfig record, ServerConfigExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("server_config.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table server_config
     *
     * @abatorgenerated Wed Apr 02 17:48:42 CST 2014
     */
    public int updateByExample(ServerConfig record, ServerConfigExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("server_config.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table server_config
     *
     * @abatorgenerated Wed Apr 02 17:48:42 CST 2014
     */
    private static class UpdateByExampleParms extends ServerConfigExample {
        private Object record;

        public UpdateByExampleParms(Object record, ServerConfigExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}