package com.orange.goldgame.system.dao;

import java.sql.SQLException;
import java.util.List;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.orange.goldgame.domain.Task;
import com.orange.goldgame.domain.TaskExample;

public class TaskDAOImpl implements TaskDAO {

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database table task
     * @ibatorgenerated  Tue Jul 23 16:03:14 CST 2013
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table task
     * @ibatorgenerated  Tue Jul 23 16:03:14 CST 2013
     */
    public TaskDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table task
     * @ibatorgenerated  Tue Jul 23 16:03:14 CST 2013
     */
    public int countByExample(TaskExample example) throws SQLException {
        Integer count = (Integer) sqlMapClient.queryForObject(
                "task.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table task
     * @ibatorgenerated  Tue Jul 23 16:03:14 CST 2013
     */
    public int deleteByExample(TaskExample example) throws SQLException {
        int rows = sqlMapClient.delete("task.ibatorgenerated_deleteByExample",
                example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table task
     * @ibatorgenerated  Tue Jul 23 16:03:14 CST 2013
     */
    public int deleteByPrimaryKey(Integer id) throws SQLException {
        Task key = new Task();
        key.setId(id);
        int rows = sqlMapClient.delete(
                "task.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table task
     * @ibatorgenerated  Tue Jul 23 16:03:14 CST 2013
     */
    public Integer insert(Task record) throws SQLException {
        Object newKey = sqlMapClient.insert("task.ibatorgenerated_insert",
                record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table task
     * @ibatorgenerated  Tue Jul 23 16:03:14 CST 2013
     */
    public Integer insertSelective(Task record) throws SQLException {
        Object newKey = sqlMapClient.insert(
                "task.ibatorgenerated_insertSelective", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table task
     * @ibatorgenerated  Tue Jul 23 16:03:14 CST 2013
     */
    public List selectByExample(TaskExample example) throws SQLException {
        List list = sqlMapClient.queryForList(
                "task.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table task
     * @ibatorgenerated  Tue Jul 23 16:03:14 CST 2013
     */
    public Task selectByPrimaryKey(Integer id) throws SQLException {
        Task key = new Task();
        key.setId(id);
        Task record = (Task) sqlMapClient.queryForObject(
                "task.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table task
     * @ibatorgenerated  Tue Jul 23 16:03:14 CST 2013
     */
    public int updateByExampleSelective(Task record, TaskExample example)
            throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update(
                "task.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table task
     * @ibatorgenerated  Tue Jul 23 16:03:14 CST 2013
     */
    public int updateByExample(Task record, TaskExample example)
            throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("task.ibatorgenerated_updateByExample",
                parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table task
     * @ibatorgenerated  Tue Jul 23 16:03:14 CST 2013
     */
    public int updateByPrimaryKeySelective(Task record) throws SQLException {
        int rows = sqlMapClient.update(
                "task.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table task
     * @ibatorgenerated  Tue Jul 23 16:03:14 CST 2013
     */
    public int updateByPrimaryKey(Task record) throws SQLException {
        int rows = sqlMapClient.update(
                "task.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator. This class corresponds to the database table task
     * @ibatorgenerated  Tue Jul 23 16:03:14 CST 2013
     */
    private static class UpdateByExampleParms extends TaskExample {
        private Object record;

        public UpdateByExampleParms(Object record, TaskExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}