package com.orange.goldgame.system.dao;

import java.sql.SQLException;
import java.util.List;

import com.orange.goldgame.domain.WheelReward;
import com.orange.goldgame.domain.WheelRewardExample;

public interface WheelRewardDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table wheel_reward
	 * @abatorgenerated  Tue Mar 25 16:00:31 CST 2014
	 */
	Integer insert(WheelReward record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table wheel_reward
	 * @abatorgenerated  Tue Mar 25 16:00:31 CST 2014
	 */
	int updateByPrimaryKey(WheelReward record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table wheel_reward
	 * @abatorgenerated  Tue Mar 25 16:00:31 CST 2014
	 */
	int updateByPrimaryKeySelective(WheelReward record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table wheel_reward
	 * @abatorgenerated  Tue Mar 25 16:00:31 CST 2014
	 */
	List<WheelReward> selectByExample(WheelRewardExample example)
			throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table wheel_reward
	 * @abatorgenerated  Tue Mar 25 16:00:31 CST 2014
	 */
	WheelReward selectByPrimaryKey(Integer id) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table wheel_reward
	 * @abatorgenerated  Tue Mar 25 16:00:31 CST 2014
	 */
	int deleteByExample(WheelRewardExample example) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table wheel_reward
	 * @abatorgenerated  Tue Mar 25 16:00:31 CST 2014
	 */
	int deleteByPrimaryKey(Integer id) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table wheel_reward
	 * @abatorgenerated  Tue Mar 25 16:00:31 CST 2014
	 */
	int countByExample(WheelRewardExample example) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table wheel_reward
	 * @abatorgenerated  Tue Mar 25 16:00:31 CST 2014
	 */
	int updateByExampleSelective(WheelReward record, WheelRewardExample example)
			throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table wheel_reward
	 * @abatorgenerated  Tue Mar 25 16:00:31 CST 2014
	 */
	int updateByExample(WheelReward record, WheelRewardExample example)
			throws SQLException;
}