package com.orange.goldgame.domain;

public class ActivityPayRecord extends BaseObject {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column activity_pay_record.id
	 * @ibatorgenerated  Fri Nov 22 09:22:25 CST 2013
	 */
	private Integer id;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column activity_pay_record.player_id
	 * @ibatorgenerated  Fri Nov 22 09:22:25 CST 2013
	 */
	private Integer playerId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column activity_pay_record.pay_money_sum
	 * @ibatorgenerated  Fri Nov 22 09:22:25 CST 2013
	 */
	private Integer payMoneySum;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column activity_pay_record.award_num
	 * @ibatorgenerated  Fri Nov 22 09:22:25 CST 2013
	 */
	private Integer awardNum;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column activity_pay_record.pay_sign
	 * @ibatorgenerated  Fri Nov 22 09:22:25 CST 2013
	 */
	private String paySign;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column activity_pay_record.state
	 * @ibatorgenerated  Fri Nov 22 09:22:25 CST 2013
	 */
	private Byte state;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column activity_pay_record.id
	 * @return  the value of activity_pay_record.id
	 * @ibatorgenerated  Fri Nov 22 09:22:25 CST 2013
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column activity_pay_record.id
	 * @param id  the value for activity_pay_record.id
	 * @ibatorgenerated  Fri Nov 22 09:22:25 CST 2013
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column activity_pay_record.player_id
	 * @return  the value of activity_pay_record.player_id
	 * @ibatorgenerated  Fri Nov 22 09:22:25 CST 2013
	 */
	public Integer getPlayerId() {
		return playerId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column activity_pay_record.player_id
	 * @param playerId  the value for activity_pay_record.player_id
	 * @ibatorgenerated  Fri Nov 22 09:22:25 CST 2013
	 */
	public void setPlayerId(Integer playerId) {
		this.playerId = playerId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column activity_pay_record.pay_money_sum
	 * @return  the value of activity_pay_record.pay_money_sum
	 * @ibatorgenerated  Fri Nov 22 09:22:25 CST 2013
	 */
	public Integer getPayMoneySum() {
		return payMoneySum;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column activity_pay_record.pay_money_sum
	 * @param payMoneySum  the value for activity_pay_record.pay_money_sum
	 * @ibatorgenerated  Fri Nov 22 09:22:25 CST 2013
	 */
	public void setPayMoneySum(Integer payMoneySum) {
		this.payMoneySum = payMoneySum;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column activity_pay_record.award_num
	 * @return  the value of activity_pay_record.award_num
	 * @ibatorgenerated  Fri Nov 22 09:22:25 CST 2013
	 */
	public Integer getAwardNum() {
		return awardNum;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column activity_pay_record.award_num
	 * @param awardNum  the value for activity_pay_record.award_num
	 * @ibatorgenerated  Fri Nov 22 09:22:25 CST 2013
	 */
	public void setAwardNum(Integer awardNum) {
		this.awardNum = awardNum;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column activity_pay_record.pay_sign
	 * @return  the value of activity_pay_record.pay_sign
	 * @ibatorgenerated  Fri Nov 22 09:22:25 CST 2013
	 */
	public String getPaySign() {
		return paySign;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column activity_pay_record.pay_sign
	 * @param paySign  the value for activity_pay_record.pay_sign
	 * @ibatorgenerated  Fri Nov 22 09:22:25 CST 2013
	 */
	public void setPaySign(String paySign) {
		this.paySign = paySign;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column activity_pay_record.state
	 * @return  the value of activity_pay_record.state
	 * @ibatorgenerated  Fri Nov 22 09:22:25 CST 2013
	 */
	public Byte getState() {
		return state;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column activity_pay_record.state
	 * @param state  the value for activity_pay_record.state
	 * @ibatorgenerated  Fri Nov 22 09:22:25 CST 2013
	 */
	public void setState(Byte state) {
		this.state = state;
	}
}