package com.orange.goldgame.domain;


public class AppConfig extends BaseObject {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column app_config.Id
	 * @ibatorgenerated  Thu Jul 11 17:07:35 CST 2013
	 */
	private Integer id;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column app_config.app_key
	 * @ibatorgenerated  Thu Jul 11 17:07:35 CST 2013
	 */
	private String appKey;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column app_config.app_value
	 * @ibatorgenerated  Thu Jul 11 17:07:35 CST 2013
	 */
	private String appValue;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column app_config.destances
	 * @ibatorgenerated  Thu Jul 11 17:07:35 CST 2013
	 */
	private String destances;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column app_config.Id
	 * @return  the value of app_config.Id
	 * @ibatorgenerated  Thu Jul 11 17:07:35 CST 2013
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column app_config.Id
	 * @param id  the value for app_config.Id
	 * @ibatorgenerated  Thu Jul 11 17:07:35 CST 2013
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column app_config.app_key
	 * @return  the value of app_config.app_key
	 * @ibatorgenerated  Thu Jul 11 17:07:35 CST 2013
	 */
	public String getAppKey() {
		return appKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column app_config.app_key
	 * @param appKey  the value for app_config.app_key
	 * @ibatorgenerated  Thu Jul 11 17:07:35 CST 2013
	 */
	public void setAppKey(String appKey) {
		this.appKey = appKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column app_config.app_value
	 * @return  the value of app_config.app_value
	 * @ibatorgenerated  Thu Jul 11 17:07:35 CST 2013
	 */
	public String getAppValue() {
		return appValue;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column app_config.app_value
	 * @param appValue  the value for app_config.app_value
	 * @ibatorgenerated  Thu Jul 11 17:07:35 CST 2013
	 */
	public void setAppValue(String appValue) {
		this.appValue = appValue;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column app_config.destances
	 * @return  the value of app_config.destances
	 * @ibatorgenerated  Thu Jul 11 17:07:35 CST 2013
	 */
	public String getDestances() {
		return destances;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column app_config.destances
	 * @param destances  the value for app_config.destances
	 * @ibatorgenerated  Thu Jul 11 17:07:35 CST 2013
	 */
	public void setDestances(String destances) {
		this.destances = destances;
	}

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
}