package com.orange.goldgame.domain;

public class AppellationConfig extends BaseObject {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column appellation_config.id
     *
     * @ibatorgenerated Mon Aug 26 10:43:53 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column appellation_config.amount
     *
     * @ibatorgenerated Mon Aug 26 10:43:53 CST 2013
     */
    private Integer amount;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column appellation_config.appellation_name
     *
     * @ibatorgenerated Mon Aug 26 10:43:53 CST 2013
     */
    private String appellationName;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column appellation_config.id
     *
     * @return the value of appellation_config.id
     *
     * @ibatorgenerated Mon Aug 26 10:43:53 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column appellation_config.id
     *
     * @param id the value for appellation_config.id
     *
     * @ibatorgenerated Mon Aug 26 10:43:53 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column appellation_config.amount
     *
     * @return the value of appellation_config.amount
     *
     * @ibatorgenerated Mon Aug 26 10:43:53 CST 2013
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column appellation_config.amount
     *
     * @param amount the value for appellation_config.amount
     *
     * @ibatorgenerated Mon Aug 26 10:43:53 CST 2013
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column appellation_config.appellation_name
     *
     * @return the value of appellation_config.appellation_name
     *
     * @ibatorgenerated Mon Aug 26 10:43:53 CST 2013
     */
    public String getAppellationName() {
        return appellationName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column appellation_config.appellation_name
     *
     * @param appellationName the value for appellation_config.appellation_name
     *
     * @ibatorgenerated Mon Aug 26 10:43:53 CST 2013
     */
    public void setAppellationName(String appellationName) {
        this.appellationName = appellationName;
    }
}