package com.orange.goldgame.domain;

import java.util.Date;

public class BuyPropRecord extends BaseObject {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column buy_prop_record.id
     *
     * @ibatorgenerated Tue Jul 09 16:45:52 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column buy_prop_record.propId
     *
     * @ibatorgenerated Tue Jul 09 16:45:52 CST 2013
     */
    private Integer propid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column buy_prop_record.playerId
     *
     * @ibatorgenerated Tue Jul 09 16:45:52 CST 2013
     */
    private Integer playerid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column buy_prop_record.consume
     *
     * @ibatorgenerated Tue Jul 09 16:45:52 CST 2013
     */
    private Integer consume;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column buy_prop_record.date
     *
     * @ibatorgenerated Tue Jul 09 16:45:52 CST 2013
     */
    private Date date;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column buy_prop_record.id
     *
     * @return the value of buy_prop_record.id
     *
     * @ibatorgenerated Tue Jul 09 16:45:52 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column buy_prop_record.id
     *
     * @param id the value for buy_prop_record.id
     *
     * @ibatorgenerated Tue Jul 09 16:45:52 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column buy_prop_record.propId
     *
     * @return the value of buy_prop_record.propId
     *
     * @ibatorgenerated Tue Jul 09 16:45:52 CST 2013
     */
    public Integer getPropid() {
        return propid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column buy_prop_record.propId
     *
     * @param propid the value for buy_prop_record.propId
     *
     * @ibatorgenerated Tue Jul 09 16:45:52 CST 2013
     */
    public void setPropid(Integer propid) {
        this.propid = propid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column buy_prop_record.playerId
     *
     * @return the value of buy_prop_record.playerId
     *
     * @ibatorgenerated Tue Jul 09 16:45:52 CST 2013
     */
    public Integer getPlayerid() {
        return playerid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column buy_prop_record.playerId
     *
     * @param playerid the value for buy_prop_record.playerId
     *
     * @ibatorgenerated Tue Jul 09 16:45:52 CST 2013
     */
    public void setPlayerid(Integer playerid) {
        this.playerid = playerid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column buy_prop_record.consume
     *
     * @return the value of buy_prop_record.consume
     *
     * @ibatorgenerated Tue Jul 09 16:45:52 CST 2013
     */
    public Integer getConsume() {
        return consume;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column buy_prop_record.consume
     *
     * @param consume the value for buy_prop_record.consume
     *
     * @ibatorgenerated Tue Jul 09 16:45:52 CST 2013
     */
    public void setConsume(Integer consume) {
        this.consume = consume;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column buy_prop_record.date
     *
     * @return the value of buy_prop_record.date
     *
     * @ibatorgenerated Tue Jul 09 16:45:52 CST 2013
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column buy_prop_record.date
     *
     * @param date the value for buy_prop_record.date
     *
     * @ibatorgenerated Tue Jul 09 16:45:52 CST 2013
     */
    public void setDate(Date date) {
        this.date = date;
    }
}