package com.orange.goldgame.domain;

import java.util.Date;

public class ClientToolNotice extends BaseObject {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column client_tool_notice.id
	 * @ibatorgenerated  Tue Jan 14 17:49:56 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column client_tool_notice.notice_message
	 * @ibatorgenerated  Tue Jan 14 17:49:56 CST 2014
	 */
	private String noticeMessage;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column client_tool_notice.notice_condition
	 * @ibatorgenerated  Tue Jan 14 17:49:56 CST 2014
	 */
	private String noticeCondition;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column client_tool_notice.start_time
	 * @ibatorgenerated  Tue Jan 14 17:49:56 CST 2014
	 */
	private Date startTime;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column client_tool_notice.end_time
	 * @ibatorgenerated  Tue Jan 14 17:49:56 CST 2014
	 */
	private Date endTime;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column client_tool_notice.send_account
	 * @ibatorgenerated  Tue Jan 14 17:49:56 CST 2014
	 */
	private Integer sendAccount;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column client_tool_notice.send_space
	 * @ibatorgenerated  Tue Jan 14 17:49:56 CST 2014
	 */
	private String sendSpace;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column client_tool_notice.success_send
	 * @ibatorgenerated  Tue Jan 14 17:49:56 CST 2014
	 */
	private Integer successSend;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column client_tool_notice.status
	 * @ibatorgenerated  Tue Jan 14 17:49:56 CST 2014
	 */
	private Byte status;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column client_tool_notice.id
	 * @return  the value of client_tool_notice.id
	 * @ibatorgenerated  Tue Jan 14 17:49:56 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column client_tool_notice.id
	 * @param id  the value for client_tool_notice.id
	 * @ibatorgenerated  Tue Jan 14 17:49:56 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column client_tool_notice.notice_message
	 * @return  the value of client_tool_notice.notice_message
	 * @ibatorgenerated  Tue Jan 14 17:49:56 CST 2014
	 */
	public String getNoticeMessage() {
		return noticeMessage;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column client_tool_notice.notice_message
	 * @param noticeMessage  the value for client_tool_notice.notice_message
	 * @ibatorgenerated  Tue Jan 14 17:49:56 CST 2014
	 */
	public void setNoticeMessage(String noticeMessage) {
		this.noticeMessage = noticeMessage;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column client_tool_notice.notice_condition
	 * @return  the value of client_tool_notice.notice_condition
	 * @ibatorgenerated  Tue Jan 14 17:49:56 CST 2014
	 */
	public String getNoticeCondition() {
		return noticeCondition;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column client_tool_notice.notice_condition
	 * @param noticeCondition  the value for client_tool_notice.notice_condition
	 * @ibatorgenerated  Tue Jan 14 17:49:56 CST 2014
	 */
	public void setNoticeCondition(String noticeCondition) {
		this.noticeCondition = noticeCondition;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column client_tool_notice.start_time
	 * @return  the value of client_tool_notice.start_time
	 * @ibatorgenerated  Tue Jan 14 17:49:56 CST 2014
	 */
	public Date getStartTime() {
		return startTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column client_tool_notice.start_time
	 * @param startTime  the value for client_tool_notice.start_time
	 * @ibatorgenerated  Tue Jan 14 17:49:56 CST 2014
	 */
	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column client_tool_notice.end_time
	 * @return  the value of client_tool_notice.end_time
	 * @ibatorgenerated  Tue Jan 14 17:49:56 CST 2014
	 */
	public Date getEndTime() {
		return endTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column client_tool_notice.end_time
	 * @param endTime  the value for client_tool_notice.end_time
	 * @ibatorgenerated  Tue Jan 14 17:49:56 CST 2014
	 */
	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column client_tool_notice.send_account
	 * @return  the value of client_tool_notice.send_account
	 * @ibatorgenerated  Tue Jan 14 17:49:56 CST 2014
	 */
	public Integer getSendAccount() {
		return sendAccount;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column client_tool_notice.send_account
	 * @param sendAccount  the value for client_tool_notice.send_account
	 * @ibatorgenerated  Tue Jan 14 17:49:56 CST 2014
	 */
	public void setSendAccount(Integer sendAccount) {
		this.sendAccount = sendAccount;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column client_tool_notice.send_space
	 * @return  the value of client_tool_notice.send_space
	 * @ibatorgenerated  Tue Jan 14 17:49:56 CST 2014
	 */
	public String getSendSpace() {
		return sendSpace;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column client_tool_notice.send_space
	 * @param sendSpace  the value for client_tool_notice.send_space
	 * @ibatorgenerated  Tue Jan 14 17:49:56 CST 2014
	 */
	public void setSendSpace(String sendSpace) {
		this.sendSpace = sendSpace;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column client_tool_notice.success_send
	 * @return  the value of client_tool_notice.success_send
	 * @ibatorgenerated  Tue Jan 14 17:49:56 CST 2014
	 */
	public Integer getSuccessSend() {
		return successSend;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column client_tool_notice.success_send
	 * @param successSend  the value for client_tool_notice.success_send
	 * @ibatorgenerated  Tue Jan 14 17:49:56 CST 2014
	 */
	public void setSuccessSend(Integer successSend) {
		this.successSend = successSend;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column client_tool_notice.status
	 * @return  the value of client_tool_notice.status
	 * @ibatorgenerated  Tue Jan 14 17:49:56 CST 2014
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column client_tool_notice.status
	 * @param status  the value for client_tool_notice.status
	 * @ibatorgenerated  Tue Jan 14 17:49:56 CST 2014
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}
}