package com.orange.goldgame.domain;

import java.util.Map;

public class PackageProps extends BaseObject {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column package_props.id
     *
     * @abatorgenerated Thu Apr 17 16:33:19 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column package_props.props_Id
     *
     * @abatorgenerated Thu Apr 17 16:33:19 CST 2014
     */
    private Integer propsId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column package_props.props_Number
     *
     * @abatorgenerated Thu Apr 17 16:33:19 CST 2014
     */
    private Integer propsNumber;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column package_props.props_Money
     *
     * @abatorgenerated Thu Apr 17 16:33:19 CST 2014
     */
    private Integer propsMoney;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column package_props.props_Award
     *
     * @abatorgenerated Thu Apr 17 16:33:19 CST 2014
     */
    private Integer propsAward;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column package_props.activity_type
     *
     * @abatorgenerated Thu Apr 17 16:33:19 CST 2014
     */
    private Integer activityType;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column package_props.activity_reward
     *
     * @abatorgenerated Thu Apr 17 16:33:19 CST 2014
     */
    private String activityReward;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column package_props.id
     *
     * @return the value of package_props.id
     *
     * @abatorgenerated Thu Apr 17 16:33:19 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column package_props.id
     *
     * @param id the value for package_props.id
     *
     * @abatorgenerated Thu Apr 17 16:33:19 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column package_props.props_Id
     *
     * @return the value of package_props.props_Id
     *
     * @abatorgenerated Thu Apr 17 16:33:19 CST 2014
     */
    public Integer getPropsId() {
        return propsId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column package_props.props_Id
     *
     * @param propsId the value for package_props.props_Id
     *
     * @abatorgenerated Thu Apr 17 16:33:19 CST 2014
     */
    public void setPropsId(Integer propsId) {
        this.propsId = propsId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column package_props.props_Number
     *
     * @return the value of package_props.props_Number
     *
     * @abatorgenerated Thu Apr 17 16:33:19 CST 2014
     */
    public Integer getPropsNumber() {
        return propsNumber;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column package_props.props_Number
     *
     * @param propsNumber the value for package_props.props_Number
     *
     * @abatorgenerated Thu Apr 17 16:33:19 CST 2014
     */
    public void setPropsNumber(Integer propsNumber) {
        this.propsNumber = propsNumber;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column package_props.props_Money
     *
     * @return the value of package_props.props_Money
     *
     * @abatorgenerated Thu Apr 17 16:33:19 CST 2014
     */
    public Integer getPropsMoney() {
        return propsMoney;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column package_props.props_Money
     *
     * @param propsMoney the value for package_props.props_Money
     *
     * @abatorgenerated Thu Apr 17 16:33:19 CST 2014
     */
    public void setPropsMoney(Integer propsMoney) {
        this.propsMoney = propsMoney;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column package_props.props_Award
     *
     * @return the value of package_props.props_Award
     *
     * @abatorgenerated Thu Apr 17 16:33:19 CST 2014
     */
    public Integer getPropsAward() {
        return propsAward;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column package_props.props_Award
     *
     * @param propsAward the value for package_props.props_Award
     *
     * @abatorgenerated Thu Apr 17 16:33:19 CST 2014
     */
    public void setPropsAward(Integer propsAward) {
        this.propsAward = propsAward;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column package_props.activity_type
     *
     * @return the value of package_props.activity_type
     *
     * @abatorgenerated Thu Apr 17 16:33:19 CST 2014
     */
    public Integer getActivityType() {
        return activityType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column package_props.activity_type
     *
     * @param activityType the value for package_props.activity_type
     *
     * @abatorgenerated Thu Apr 17 16:33:19 CST 2014
     */
    public void setActivityType(Integer activityType) {
        this.activityType = activityType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column package_props.activity_reward
     *
     * @return the value of package_props.activity_reward
     *
     * @abatorgenerated Thu Apr 17 16:33:19 CST 2014
     */
    public String getActivityReward() {
        return activityReward;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column package_props.activity_reward
     *
     * @param activityReward the value for package_props.activity_reward
     *
     * @abatorgenerated Thu Apr 17 16:33:19 CST 2014
     */
    public void setActivityReward(String activityReward) {
        this.activityReward = activityReward;
    }
    private Map<Integer, Integer> activityRewards = null;

	public void setActivityRewards(Map<Integer, Integer> activityRewards) {
		this.activityRewards = activityRewards;
	}

	public Map<Integer, Integer> getActivityRewards() {
		return activityRewards;
	}
}