package com.orange.goldgame.domain;

import java.util.Date;

public class PlayerConsume extends BaseObject {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column player_consume.id
	 * @ibatorgenerated  Sun Jan 19 17:27:05 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column player_consume.player_id
	 * @ibatorgenerated  Sun Jan 19 17:27:05 CST 2014
	 */
	private Integer playerId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column player_consume.before_num
	 * @ibatorgenerated  Sun Jan 19 17:27:05 CST 2014
	 */
	private Integer beforeNum;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column player_consume.prop_config_id
	 * @ibatorgenerated  Sun Jan 19 17:27:05 CST 2014
	 */
	private Integer propConfigId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column player_consume.consume_num
	 * @ibatorgenerated  Sun Jan 19 17:27:05 CST 2014
	 */
	private Integer consumeNum;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column player_consume.after_num
	 * @ibatorgenerated  Sun Jan 19 17:27:05 CST 2014
	 */
	private Integer afterNum;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column player_consume.comsume_time
	 * @ibatorgenerated  Sun Jan 19 17:27:05 CST 2014
	 */
	private Date comsumeTime;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column player_consume.state
	 * @ibatorgenerated  Sun Jan 19 17:27:05 CST 2014
	 */
	private Byte state;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column player_consume.id
	 * @return  the value of player_consume.id
	 * @ibatorgenerated  Sun Jan 19 17:27:05 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column player_consume.id
	 * @param id  the value for player_consume.id
	 * @ibatorgenerated  Sun Jan 19 17:27:05 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column player_consume.player_id
	 * @return  the value of player_consume.player_id
	 * @ibatorgenerated  Sun Jan 19 17:27:05 CST 2014
	 */
	public Integer getPlayerId() {
		return playerId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column player_consume.player_id
	 * @param playerId  the value for player_consume.player_id
	 * @ibatorgenerated  Sun Jan 19 17:27:05 CST 2014
	 */
	public void setPlayerId(Integer playerId) {
		this.playerId = playerId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column player_consume.before_num
	 * @return  the value of player_consume.before_num
	 * @ibatorgenerated  Sun Jan 19 17:27:05 CST 2014
	 */
	public Integer getBeforeNum() {
		return beforeNum;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column player_consume.before_num
	 * @param beforeNum  the value for player_consume.before_num
	 * @ibatorgenerated  Sun Jan 19 17:27:05 CST 2014
	 */
	public void setBeforeNum(Integer beforeNum) {
		this.beforeNum = beforeNum;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column player_consume.prop_config_id
	 * @return  the value of player_consume.prop_config_id
	 * @ibatorgenerated  Sun Jan 19 17:27:05 CST 2014
	 */
	public Integer getPropConfigId() {
		return propConfigId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column player_consume.prop_config_id
	 * @param propConfigId  the value for player_consume.prop_config_id
	 * @ibatorgenerated  Sun Jan 19 17:27:05 CST 2014
	 */
	public void setPropConfigId(Integer propConfigId) {
		this.propConfigId = propConfigId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column player_consume.consume_num
	 * @return  the value of player_consume.consume_num
	 * @ibatorgenerated  Sun Jan 19 17:27:05 CST 2014
	 */
	public Integer getConsumeNum() {
		return consumeNum;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column player_consume.consume_num
	 * @param consumeNum  the value for player_consume.consume_num
	 * @ibatorgenerated  Sun Jan 19 17:27:05 CST 2014
	 */
	public void setConsumeNum(Integer consumeNum) {
		this.consumeNum = consumeNum;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column player_consume.after_num
	 * @return  the value of player_consume.after_num
	 * @ibatorgenerated  Sun Jan 19 17:27:05 CST 2014
	 */
	public Integer getAfterNum() {
		return afterNum;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column player_consume.after_num
	 * @param afterNum  the value for player_consume.after_num
	 * @ibatorgenerated  Sun Jan 19 17:27:05 CST 2014
	 */
	public void setAfterNum(Integer afterNum) {
		this.afterNum = afterNum;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column player_consume.comsume_time
	 * @return  the value of player_consume.comsume_time
	 * @ibatorgenerated  Sun Jan 19 17:27:05 CST 2014
	 */
	public Date getComsumeTime() {
		return comsumeTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column player_consume.comsume_time
	 * @param comsumeTime  the value for player_consume.comsume_time
	 * @ibatorgenerated  Sun Jan 19 17:27:05 CST 2014
	 */
	public void setComsumeTime(Date comsumeTime) {
		this.comsumeTime = comsumeTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column player_consume.state
	 * @return  the value of player_consume.state
	 * @ibatorgenerated  Sun Jan 19 17:27:05 CST 2014
	 */
	public Byte getState() {
		return state;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column player_consume.state
	 * @param state  the value for player_consume.state
	 * @ibatorgenerated  Sun Jan 19 17:27:05 CST 2014
	 */
	public void setState(Byte state) {
		this.state = state;
	}
}