package com.orange.goldgame.domain;

import java.util.Date;

public class PlayerPayApril extends BaseObject {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column player_pay_april.id
     *
     * @abatorgenerated Wed Mar 26 14:13:55 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column player_pay_april.player_id
     *
     * @abatorgenerated Wed Mar 26 14:13:55 CST 2014
     */
    private Integer playerId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column player_pay_april.create_time
     *
     * @abatorgenerated Wed Mar 26 14:13:55 CST 2014
     */
    private Date createTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column player_pay_april.all_golds
     *
     * @abatorgenerated Wed Mar 26 14:13:55 CST 2014
     */
    private Integer allGolds;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column player_pay_april.rewards_num
     *
     * @abatorgenerated Wed Mar 26 14:13:55 CST 2014
     */
    private Integer rewardsNum;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column player_pay_april.id
     *
     * @return the value of player_pay_april.id
     *
     * @abatorgenerated Wed Mar 26 14:13:55 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column player_pay_april.id
     *
     * @param id the value for player_pay_april.id
     *
     * @abatorgenerated Wed Mar 26 14:13:55 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column player_pay_april.player_id
     *
     * @return the value of player_pay_april.player_id
     *
     * @abatorgenerated Wed Mar 26 14:13:55 CST 2014
     */
    public Integer getPlayerId() {
        return playerId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column player_pay_april.player_id
     *
     * @param playerId the value for player_pay_april.player_id
     *
     * @abatorgenerated Wed Mar 26 14:13:55 CST 2014
     */
    public void setPlayerId(Integer playerId) {
        this.playerId = playerId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column player_pay_april.create_time
     *
     * @return the value of player_pay_april.create_time
     *
     * @abatorgenerated Wed Mar 26 14:13:55 CST 2014
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column player_pay_april.create_time
     *
     * @param createTime the value for player_pay_april.create_time
     *
     * @abatorgenerated Wed Mar 26 14:13:55 CST 2014
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column player_pay_april.all_golds
     *
     * @return the value of player_pay_april.all_golds
     *
     * @abatorgenerated Wed Mar 26 14:13:55 CST 2014
     */
    public Integer getAllGolds() {
        return allGolds;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column player_pay_april.all_golds
     *
     * @param allGolds the value for player_pay_april.all_golds
     *
     * @abatorgenerated Wed Mar 26 14:13:55 CST 2014
     */
    public void setAllGolds(Integer allGolds) {
        this.allGolds = allGolds;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column player_pay_april.rewards_num
     *
     * @return the value of player_pay_april.rewards_num
     *
     * @abatorgenerated Wed Mar 26 14:13:55 CST 2014
     */
    public Integer getRewardsNum() {
        return rewardsNum;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column player_pay_april.rewards_num
     *
     * @param rewardsNum the value for player_pay_april.rewards_num
     *
     * @abatorgenerated Wed Mar 26 14:13:55 CST 2014
     */
    public void setRewardsNum(Integer rewardsNum) {
        this.rewardsNum = rewardsNum;
    }
}