package com.orange.goldgame.domain;

public class PlayerShareInfo extends BaseObject {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column player_share_info.id
     *
     * @ibatorgenerated Fri Oct 25 09:38:45 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column player_share_info.player_id
     *
     * @ibatorgenerated Fri Oct 25 09:38:45 CST 2013
     */
    private Integer playerId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column player_share_info.other_id
     *
     * @ibatorgenerated Fri Oct 25 09:38:45 CST 2013
     */
    private Integer otherId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column player_share_info.head_img
     *
     * @ibatorgenerated Fri Oct 25 09:38:45 CST 2013
     */
    private String headImg;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column player_share_info.other_name
     *
     * @ibatorgenerated Fri Oct 25 09:38:45 CST 2013
     */
    private String otherName;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column player_share_info.id
     *
     * @return the value of player_share_info.id
     *
     * @ibatorgenerated Fri Oct 25 09:38:45 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column player_share_info.id
     *
     * @param id the value for player_share_info.id
     *
     * @ibatorgenerated Fri Oct 25 09:38:45 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column player_share_info.player_id
     *
     * @return the value of player_share_info.player_id
     *
     * @ibatorgenerated Fri Oct 25 09:38:45 CST 2013
     */
    public Integer getPlayerId() {
        return playerId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column player_share_info.player_id
     *
     * @param playerId the value for player_share_info.player_id
     *
     * @ibatorgenerated Fri Oct 25 09:38:45 CST 2013
     */
    public void setPlayerId(Integer playerId) {
        this.playerId = playerId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column player_share_info.other_id
     *
     * @return the value of player_share_info.other_id
     *
     * @ibatorgenerated Fri Oct 25 09:38:45 CST 2013
     */
    public Integer getOtherId() {
        return otherId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column player_share_info.other_id
     *
     * @param otherId the value for player_share_info.other_id
     *
     * @ibatorgenerated Fri Oct 25 09:38:45 CST 2013
     */
    public void setOtherId(Integer otherId) {
        this.otherId = otherId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column player_share_info.head_img
     *
     * @return the value of player_share_info.head_img
     *
     * @ibatorgenerated Fri Oct 25 09:38:45 CST 2013
     */
    public String getHeadImg() {
        return headImg;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column player_share_info.head_img
     *
     * @param headImg the value for player_share_info.head_img
     *
     * @ibatorgenerated Fri Oct 25 09:38:45 CST 2013
     */
    public void setHeadImg(String headImg) {
        this.headImg = headImg;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column player_share_info.other_name
     *
     * @return the value of player_share_info.other_name
     *
     * @ibatorgenerated Fri Oct 25 09:38:45 CST 2013
     */
    public String getOtherName() {
        return otherName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column player_share_info.other_name
     *
     * @param otherName the value for player_share_info.other_name
     *
     * @ibatorgenerated Fri Oct 25 09:38:45 CST 2013
     */
    public void setOtherName(String otherName) {
        this.otherName = otherName;
    }
}