package com.orange.goldgame.domain;

import java.io.Serializable;

public class PropsConfig extends BaseObject implements Serializable{

	/**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column props_config.id
     * @ibatorgenerated  Wed Jul 31 11:43:32 CST 2013
     */
    private Integer id;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column props_config.name
     * @ibatorgenerated  Wed Jul 31 11:43:32 CST 2013
     */
    private String name;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column props_config.props_type
     * @ibatorgenerated  Wed Jul 31 11:43:32 CST 2013
     */
    private Integer propsType;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column props_config.destance
     * @ibatorgenerated  Wed Jul 31 11:43:32 CST 2013
     */
    private String destance;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column props_config.copper
     * @ibatorgenerated  Wed Jul 31 11:43:32 CST 2013
     */
    private Integer copper;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column props_config.multiple
     * @ibatorgenerated  Wed Jul 31 11:43:32 CST 2013
     */
    private Integer multiple;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column props_config.left_time
     * @ibatorgenerated  Wed Jul 31 11:43:32 CST 2013
     */
    private Integer leftTime;

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column props_config.id
     * @return  the value of props_config.id
     * @ibatorgenerated  Wed Jul 31 11:43:32 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column props_config.id
     * @param id  the value for props_config.id
     * @ibatorgenerated  Wed Jul 31 11:43:32 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column props_config.name
     * @return  the value of props_config.name
     * @ibatorgenerated  Wed Jul 31 11:43:32 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column props_config.name
     * @param name  the value for props_config.name
     * @ibatorgenerated  Wed Jul 31 11:43:32 CST 2013
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column props_config.props_type
     * @return  the value of props_config.props_type
     * @ibatorgenerated  Wed Jul 31 11:43:32 CST 2013
     */
    public Integer getPropsType() {
        return propsType;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column props_config.props_type
     * @param propsType  the value for props_config.props_type
     * @ibatorgenerated  Wed Jul 31 11:43:32 CST 2013
     */
    public void setPropsType(Integer propsType) {
        this.propsType = propsType;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column props_config.destance
     * @return  the value of props_config.destance
     * @ibatorgenerated  Wed Jul 31 11:43:32 CST 2013
     */
    public String getDestance() {
        return destance;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column props_config.destance
     * @param destance  the value for props_config.destance
     * @ibatorgenerated  Wed Jul 31 11:43:32 CST 2013
     */
    public void setDestance(String destance) {
        this.destance = destance;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column props_config.copper
     * @return  the value of props_config.copper
     * @ibatorgenerated  Wed Jul 31 11:43:32 CST 2013
     */
    public Integer getCopper() {
        return copper;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column props_config.copper
     * @param copper  the value for props_config.copper
     * @ibatorgenerated  Wed Jul 31 11:43:32 CST 2013
     */
    public void setCopper(Integer copper) {
        this.copper = copper;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column props_config.multiple
     * @return  the value of props_config.multiple
     * @ibatorgenerated  Wed Jul 31 11:43:32 CST 2013
     */
    public Integer getMultiple() {
        return multiple;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column props_config.multiple
     * @param multiple  the value for props_config.multiple
     * @ibatorgenerated  Wed Jul 31 11:43:32 CST 2013
     */
    public void setMultiple(Integer multiple) {
        this.multiple = multiple;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column props_config.left_time
     * @return  the value of props_config.left_time
     * @ibatorgenerated  Wed Jul 31 11:43:32 CST 2013
     */
    public Integer getLeftTime() {
        return leftTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column props_config.left_time
     * @param leftTime  the value for props_config.left_time
     * @ibatorgenerated  Wed Jul 31 11:43:32 CST 2013
     */
    public void setLeftTime(Integer leftTime) {
        this.leftTime = leftTime;
    }

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
}