package com.orange.goldgame.domain;

public class WheelReward extends BaseObject {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column wheel_reward.id
	 * @abatorgenerated  Tue Mar 25 16:00:31 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column wheel_reward.rewards
	 * @abatorgenerated  Tue Mar 25 16:00:31 CST 2014
	 */
	private Integer rewards;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column wheel_reward.rewards_type
	 * @abatorgenerated  Tue Mar 25 16:00:31 CST 2014
	 */
	private Integer rewardsType;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column wheel_reward.name
	 * @abatorgenerated  Tue Mar 25 16:00:31 CST 2014
	 */
	private String name;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column wheel_reward.player_pre
	 * @abatorgenerated  Tue Mar 25 16:00:31 CST 2014
	 */
	private Integer playerPre;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column wheel_reward.robot_pre
	 * @abatorgenerated  Tue Mar 25 16:00:31 CST 2014
	 */
	private Integer robotPre;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column wheel_reward.id
	 * @return  the value of wheel_reward.id
	 * @abatorgenerated  Tue Mar 25 16:00:31 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column wheel_reward.id
	 * @param id  the value for wheel_reward.id
	 * @abatorgenerated  Tue Mar 25 16:00:31 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column wheel_reward.rewards
	 * @return  the value of wheel_reward.rewards
	 * @abatorgenerated  Tue Mar 25 16:00:31 CST 2014
	 */
	public Integer getRewards() {
		return rewards;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column wheel_reward.rewards
	 * @param rewards  the value for wheel_reward.rewards
	 * @abatorgenerated  Tue Mar 25 16:00:31 CST 2014
	 */
	public void setRewards(Integer rewards) {
		this.rewards = rewards;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column wheel_reward.rewards_type
	 * @return  the value of wheel_reward.rewards_type
	 * @abatorgenerated  Tue Mar 25 16:00:31 CST 2014
	 */
	public Integer getRewardsType() {
		return rewardsType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column wheel_reward.rewards_type
	 * @param rewardsType  the value for wheel_reward.rewards_type
	 * @abatorgenerated  Tue Mar 25 16:00:31 CST 2014
	 */
	public void setRewardsType(Integer rewardsType) {
		this.rewardsType = rewardsType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column wheel_reward.name
	 * @return  the value of wheel_reward.name
	 * @abatorgenerated  Tue Mar 25 16:00:31 CST 2014
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column wheel_reward.name
	 * @param name  the value for wheel_reward.name
	 * @abatorgenerated  Tue Mar 25 16:00:31 CST 2014
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column wheel_reward.player_pre
	 * @return  the value of wheel_reward.player_pre
	 * @abatorgenerated  Tue Mar 25 16:00:31 CST 2014
	 */
	public Integer getPlayerPre() {
		return playerPre;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column wheel_reward.player_pre
	 * @param playerPre  the value for wheel_reward.player_pre
	 * @abatorgenerated  Tue Mar 25 16:00:31 CST 2014
	 */
	public void setPlayerPre(Integer playerPre) {
		this.playerPre = playerPre;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column wheel_reward.robot_pre
	 * @return  the value of wheel_reward.robot_pre
	 * @abatorgenerated  Tue Mar 25 16:00:31 CST 2014
	 */
	public Integer getRobotPre() {
		return robotPre;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column wheel_reward.robot_pre
	 * @param robotPre  the value for wheel_reward.robot_pre
	 * @abatorgenerated  Tue Mar 25 16:00:31 CST 2014
	 */
	public void setRobotPre(Integer robotPre) {
		this.robotPre = robotPre;
	}
}