package com.orange.goldgame.domain;

import java.util.Date;

public class ZfbPayRecord extends BaseObject {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column zfb_pay_record.id
	 * @ibatorgenerated  Wed Nov 20 10:11:05 CST 2013
	 */
	private Integer id;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column zfb_pay_record.pay_id
	 * @ibatorgenerated  Wed Nov 20 10:11:05 CST 2013
	 */
	private String payId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column zfb_pay_record.player_id
	 * @ibatorgenerated  Wed Nov 20 10:11:05 CST 2013
	 */
	private Integer playerId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column zfb_pay_record.zfb_username
	 * @ibatorgenerated  Wed Nov 20 10:11:05 CST 2013
	 */
	private String zfbUsername;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column zfb_pay_record.goods_name
	 * @ibatorgenerated  Wed Nov 20 10:11:05 CST 2013
	 */
	private String goodsName;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column zfb_pay_record.goods_price
	 * @ibatorgenerated  Wed Nov 20 10:11:05 CST 2013
	 */
	private Float goodsPrice;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column zfb_pay_record.trade_state
	 * @ibatorgenerated  Wed Nov 20 10:11:05 CST 2013
	 */
	private String tradeState;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column zfb_pay_record.pay_time
	 * @ibatorgenerated  Wed Nov 20 10:11:05 CST 2013
	 */
	private Date payTime;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column zfb_pay_record.id
	 * @return  the value of zfb_pay_record.id
	 * @ibatorgenerated  Wed Nov 20 10:11:05 CST 2013
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column zfb_pay_record.id
	 * @param id  the value for zfb_pay_record.id
	 * @ibatorgenerated  Wed Nov 20 10:11:05 CST 2013
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column zfb_pay_record.pay_id
	 * @return  the value of zfb_pay_record.pay_id
	 * @ibatorgenerated  Wed Nov 20 10:11:05 CST 2013
	 */
	public String getPayId() {
		return payId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column zfb_pay_record.pay_id
	 * @param payId  the value for zfb_pay_record.pay_id
	 * @ibatorgenerated  Wed Nov 20 10:11:05 CST 2013
	 */
	public void setPayId(String payId) {
		this.payId = payId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column zfb_pay_record.player_id
	 * @return  the value of zfb_pay_record.player_id
	 * @ibatorgenerated  Wed Nov 20 10:11:05 CST 2013
	 */
	public Integer getPlayerId() {
		return playerId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column zfb_pay_record.player_id
	 * @param playerId  the value for zfb_pay_record.player_id
	 * @ibatorgenerated  Wed Nov 20 10:11:05 CST 2013
	 */
	public void setPlayerId(Integer playerId) {
		this.playerId = playerId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column zfb_pay_record.zfb_username
	 * @return  the value of zfb_pay_record.zfb_username
	 * @ibatorgenerated  Wed Nov 20 10:11:05 CST 2013
	 */
	public String getZfbUsername() {
		return zfbUsername;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column zfb_pay_record.zfb_username
	 * @param zfbUsername  the value for zfb_pay_record.zfb_username
	 * @ibatorgenerated  Wed Nov 20 10:11:05 CST 2013
	 */
	public void setZfbUsername(String zfbUsername) {
		this.zfbUsername = zfbUsername;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column zfb_pay_record.goods_name
	 * @return  the value of zfb_pay_record.goods_name
	 * @ibatorgenerated  Wed Nov 20 10:11:05 CST 2013
	 */
	public String getGoodsName() {
		return goodsName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column zfb_pay_record.goods_name
	 * @param goodsName  the value for zfb_pay_record.goods_name
	 * @ibatorgenerated  Wed Nov 20 10:11:05 CST 2013
	 */
	public void setGoodsName(String goodsName) {
		this.goodsName = goodsName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column zfb_pay_record.goods_price
	 * @return  the value of zfb_pay_record.goods_price
	 * @ibatorgenerated  Wed Nov 20 10:11:05 CST 2013
	 */
	public Float getGoodsPrice() {
		return goodsPrice;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column zfb_pay_record.goods_price
	 * @param goodsPrice  the value for zfb_pay_record.goods_price
	 * @ibatorgenerated  Wed Nov 20 10:11:05 CST 2013
	 */
	public void setGoodsPrice(Float goodsPrice) {
		this.goodsPrice = goodsPrice;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column zfb_pay_record.trade_state
	 * @return  the value of zfb_pay_record.trade_state
	 * @ibatorgenerated  Wed Nov 20 10:11:05 CST 2013
	 */
	public String getTradeState() {
		return tradeState;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column zfb_pay_record.trade_state
	 * @param tradeState  the value for zfb_pay_record.trade_state
	 * @ibatorgenerated  Wed Nov 20 10:11:05 CST 2013
	 */
	public void setTradeState(String tradeState) {
		this.tradeState = tradeState;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column zfb_pay_record.pay_time
	 * @return  the value of zfb_pay_record.pay_time
	 * @ibatorgenerated  Wed Nov 20 10:11:05 CST 2013
	 */
	public Date getPayTime() {
		return payTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column zfb_pay_record.pay_time
	 * @param payTime  the value for zfb_pay_record.pay_time
	 * @ibatorgenerated  Wed Nov 20 10:11:05 CST 2013
	 */
	public void setPayTime(Date payTime) {
		this.payTime = payTime;
	}
}