package com.orange.goldgame.domain;

public class AreaConfig extends BaseObject {

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column area_config.Id
     * @ibatorgenerated  Tue Sep 24 10:33:39 CST 2013
     */
    private Integer id;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column area_config.area_Type
     * @ibatorgenerated  Tue Sep 24 10:33:39 CST 2013
     */
    private Short areaType;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column area_config.area_Class
     * @ibatorgenerated  Tue Sep 24 10:33:39 CST 2013
     */
    private Short areaClass;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column area_config.top_Limit_Golds
     * @ibatorgenerated  Tue Sep 24 10:33:39 CST 2013
     */
    private Integer topLimitGolds;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column area_config.limit_Golds
     * @ibatorgenerated  Tue Sep 24 10:33:39 CST 2013
     */
    private Integer limitGolds;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column area_config.single_Golds
     * @ibatorgenerated  Tue Sep 24 10:33:39 CST 2013
     */
    private Integer singleGolds;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column area_config.aword
     * @ibatorgenerated  Tue Sep 24 10:33:39 CST 2013
     */
    private String aword;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column area_config.introdution
     * @ibatorgenerated  Tue Sep 24 10:33:39 CST 2013
     */
    private String introdution;

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column area_config.Id
     * @return  the value of area_config.Id
     * @ibatorgenerated  Tue Sep 24 10:33:39 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column area_config.Id
     * @param id  the value for area_config.Id
     * @ibatorgenerated  Tue Sep 24 10:33:39 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column area_config.area_Type
     * @return  the value of area_config.area_Type
     * @ibatorgenerated  Tue Sep 24 10:33:39 CST 2013
     */
    public Short getAreaType() {
        return areaType;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column area_config.area_Type
     * @param areaType  the value for area_config.area_Type
     * @ibatorgenerated  Tue Sep 24 10:33:39 CST 2013
     */
    public void setAreaType(Short areaType) {
        this.areaType = areaType;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column area_config.area_Class
     * @return  the value of area_config.area_Class
     * @ibatorgenerated  Tue Sep 24 10:33:39 CST 2013
     */
    public Short getAreaClass() {
        return areaClass;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column area_config.area_Class
     * @param areaClass  the value for area_config.area_Class
     * @ibatorgenerated  Tue Sep 24 10:33:39 CST 2013
     */
    public void setAreaClass(Short areaClass) {
        this.areaClass = areaClass;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column area_config.top_Limit_Golds
     * @return  the value of area_config.top_Limit_Golds
     * @ibatorgenerated  Tue Sep 24 10:33:39 CST 2013
     */
    public Integer getTopLimitGolds() {
        return topLimitGolds;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column area_config.top_Limit_Golds
     * @param topLimitGolds  the value for area_config.top_Limit_Golds
     * @ibatorgenerated  Tue Sep 24 10:33:39 CST 2013
     */
    public void setTopLimitGolds(Integer topLimitGolds) {
        this.topLimitGolds = topLimitGolds;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column area_config.limit_Golds
     * @return  the value of area_config.limit_Golds
     * @ibatorgenerated  Tue Sep 24 10:33:39 CST 2013
     */
    public Integer getLimitGolds() {
        return limitGolds;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column area_config.limit_Golds
     * @param limitGolds  the value for area_config.limit_Golds
     * @ibatorgenerated  Tue Sep 24 10:33:39 CST 2013
     */
    public void setLimitGolds(Integer limitGolds) {
        this.limitGolds = limitGolds;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column area_config.single_Golds
     * @return  the value of area_config.single_Golds
     * @ibatorgenerated  Tue Sep 24 10:33:39 CST 2013
     */
    public Integer getSingleGolds() {
        return singleGolds;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column area_config.single_Golds
     * @param singleGolds  the value for area_config.single_Golds
     * @ibatorgenerated  Tue Sep 24 10:33:39 CST 2013
     */
    public void setSingleGolds(Integer singleGolds) {
        this.singleGolds = singleGolds;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column area_config.aword
     * @return  the value of area_config.aword
     * @ibatorgenerated  Tue Sep 24 10:33:39 CST 2013
     */
    public String getAword() {
        return aword;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column area_config.aword
     * @param aword  the value for area_config.aword
     * @ibatorgenerated  Tue Sep 24 10:33:39 CST 2013
     */
    public void setAword(String aword) {
        this.aword = aword;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column area_config.introdution
     * @return  the value of area_config.introdution
     * @ibatorgenerated  Tue Sep 24 10:33:39 CST 2013
     */
    public String getIntrodution() {
        return introdution;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column area_config.introdution
     * @param introdution  the value for area_config.introdution
     * @ibatorgenerated  Tue Sep 24 10:33:39 CST 2013
     */
    public void setIntrodution(String introdution) {
        this.introdution = introdution;
    }
}