package com.orange.goldgame.domain;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class GetOnceExample {

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database table get_once
     * @ibatorgenerated  Mon Jul 15 09:59:23 CST 2013
     */
    protected String orderByClause;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database table get_once
     * @ibatorgenerated  Mon Jul 15 09:59:23 CST 2013
     */
    protected List oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table get_once
     * @ibatorgenerated  Mon Jul 15 09:59:23 CST 2013
     */
    public GetOnceExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table get_once
     * @ibatorgenerated  Mon Jul 15 09:59:23 CST 2013
     */
    protected GetOnceExample(GetOnceExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table get_once
     * @ibatorgenerated  Mon Jul 15 09:59:23 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table get_once
     * @ibatorgenerated  Mon Jul 15 09:59:23 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table get_once
     * @ibatorgenerated  Mon Jul 15 09:59:23 CST 2013
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table get_once
     * @ibatorgenerated  Mon Jul 15 09:59:23 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table get_once
     * @ibatorgenerated  Mon Jul 15 09:59:23 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table get_once
     * @ibatorgenerated  Mon Jul 15 09:59:23 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table get_once
     * @ibatorgenerated  Mon Jul 15 09:59:23 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator. This class corresponds to the database table get_once
     * @ibatorgenerated  Mon Jul 15 09:59:23 CST 2013
     */
    public static class Criteria {
        protected List criteriaWithoutValue;
        protected List criteriaWithSingleValue;
        protected List criteriaWithListValue;
        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                    || criteriaWithSingleValue.size() > 0
                    || criteriaWithListValue.size() > 0
                    || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value,
                String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property
                        + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values,
                String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property
                        + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1,
                Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property
                        + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return this;
        }

        public Criteria andIdIn(List values) {
            addCriterion("id in", values, "id");
            return this;
        }

        public Criteria andIdNotIn(List values) {
            addCriterion("id not in", values, "id");
            return this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return this;
        }

        public Criteria andPlayerIdIsNull() {
            addCriterion("player_id is null");
            return this;
        }

        public Criteria andPlayerIdIsNotNull() {
            addCriterion("player_id is not null");
            return this;
        }

        public Criteria andPlayerIdEqualTo(Integer value) {
            addCriterion("player_id =", value, "playerId");
            return this;
        }

        public Criteria andPlayerIdNotEqualTo(Integer value) {
            addCriterion("player_id <>", value, "playerId");
            return this;
        }

        public Criteria andPlayerIdGreaterThan(Integer value) {
            addCriterion("player_id >", value, "playerId");
            return this;
        }

        public Criteria andPlayerIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("player_id >=", value, "playerId");
            return this;
        }

        public Criteria andPlayerIdLessThan(Integer value) {
            addCriterion("player_id <", value, "playerId");
            return this;
        }

        public Criteria andPlayerIdLessThanOrEqualTo(Integer value) {
            addCriterion("player_id <=", value, "playerId");
            return this;
        }

        public Criteria andPlayerIdIn(List values) {
            addCriterion("player_id in", values, "playerId");
            return this;
        }

        public Criteria andPlayerIdNotIn(List values) {
            addCriterion("player_id not in", values, "playerId");
            return this;
        }

        public Criteria andPlayerIdBetween(Integer value1, Integer value2) {
            addCriterion("player_id between", value1, value2, "playerId");
            return this;
        }

        public Criteria andPlayerIdNotBetween(Integer value1, Integer value2) {
            addCriterion("player_id not between", value1, value2, "playerId");
            return this;
        }

        public Criteria andDayKeyIsNull() {
            addCriterion("day_key is null");
            return this;
        }

        public Criteria andDayKeyIsNotNull() {
            addCriterion("day_key is not null");
            return this;
        }

        public Criteria andDayKeyEqualTo(String value) {
            addCriterion("day_key =", value, "dayKey");
            return this;
        }

        public Criteria andDayKeyNotEqualTo(String value) {
            addCriterion("day_key <>", value, "dayKey");
            return this;
        }

        public Criteria andDayKeyGreaterThan(String value) {
            addCriterion("day_key >", value, "dayKey");
            return this;
        }

        public Criteria andDayKeyGreaterThanOrEqualTo(String value) {
            addCriterion("day_key >=", value, "dayKey");
            return this;
        }

        public Criteria andDayKeyLessThan(String value) {
            addCriterion("day_key <", value, "dayKey");
            return this;
        }

        public Criteria andDayKeyLessThanOrEqualTo(String value) {
            addCriterion("day_key <=", value, "dayKey");
            return this;
        }

        public Criteria andDayKeyLike(String value) {
            addCriterion("day_key like", value, "dayKey");
            return this;
        }

        public Criteria andDayKeyNotLike(String value) {
            addCriterion("day_key not like", value, "dayKey");
            return this;
        }

        public Criteria andDayKeyIn(List values) {
            addCriterion("day_key in", values, "dayKey");
            return this;
        }

        public Criteria andDayKeyNotIn(List values) {
            addCriterion("day_key not in", values, "dayKey");
            return this;
        }

        public Criteria andDayKeyBetween(String value1, String value2) {
            addCriterion("day_key between", value1, value2, "dayKey");
            return this;
        }

        public Criteria andDayKeyNotBetween(String value1, String value2) {
            addCriterion("day_key not between", value1, value2, "dayKey");
            return this;
        }

        public Criteria andDayNumIsNull() {
            addCriterion("day_num is null");
            return this;
        }

        public Criteria andDayNumIsNotNull() {
            addCriterion("day_num is not null");
            return this;
        }

        public Criteria andDayNumEqualTo(String value) {
            addCriterion("day_num =", value, "dayNum");
            return this;
        }

        public Criteria andDayNumNotEqualTo(String value) {
            addCriterion("day_num <>", value, "dayNum");
            return this;
        }

        public Criteria andDayNumGreaterThan(String value) {
            addCriterion("day_num >", value, "dayNum");
            return this;
        }

        public Criteria andDayNumGreaterThanOrEqualTo(String value) {
            addCriterion("day_num >=", value, "dayNum");
            return this;
        }

        public Criteria andDayNumLessThan(String value) {
            addCriterion("day_num <", value, "dayNum");
            return this;
        }

        public Criteria andDayNumLessThanOrEqualTo(String value) {
            addCriterion("day_num <=", value, "dayNum");
            return this;
        }

        public Criteria andDayNumLike(String value) {
            addCriterion("day_num like", value, "dayNum");
            return this;
        }

        public Criteria andDayNumNotLike(String value) {
            addCriterion("day_num not like", value, "dayNum");
            return this;
        }

        public Criteria andDayNumIn(List values) {
            addCriterion("day_num in", values, "dayNum");
            return this;
        }

        public Criteria andDayNumNotIn(List values) {
            addCriterion("day_num not in", values, "dayNum");
            return this;
        }

        public Criteria andDayNumBetween(String value1, String value2) {
            addCriterion("day_num between", value1, value2, "dayNum");
            return this;
        }

        public Criteria andDayNumNotBetween(String value1, String value2) {
            addCriterion("day_num not between", value1, value2, "dayNum");
            return this;
        }
    }
}