package com.orange.goldgame.domain;

public class NoticeConfig extends BaseObject {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column notice_config.id
     *
     * @ibatorgenerated Thu Jul 11 18:08:21 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column notice_config.name
     *
     * @ibatorgenerated Thu Jul 11 18:08:21 CST 2013
     */
    private String name;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column notice_config.destance
     *
     * @ibatorgenerated Thu Jul 11 18:08:21 CST 2013
     */
    private String destance;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column notice_config.id
     *
     * @return the value of notice_config.id
     *
     * @ibatorgenerated Thu Jul 11 18:08:21 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column notice_config.id
     *
     * @param id the value for notice_config.id
     *
     * @ibatorgenerated Thu Jul 11 18:08:21 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column notice_config.name
     *
     * @return the value of notice_config.name
     *
     * @ibatorgenerated Thu Jul 11 18:08:21 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column notice_config.name
     *
     * @param name the value for notice_config.name
     *
     * @ibatorgenerated Thu Jul 11 18:08:21 CST 2013
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column notice_config.destance
     *
     * @return the value of notice_config.destance
     *
     * @ibatorgenerated Thu Jul 11 18:08:21 CST 2013
     */
    public String getDestance() {
        return destance;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column notice_config.destance
     *
     * @param destance the value for notice_config.destance
     *
     * @ibatorgenerated Thu Jul 11 18:08:21 CST 2013
     */
    public void setDestance(String destance) {
        this.destance = destance;
    }
}