package com.orange.goldgame.domain;

public class PayChannelConfig extends BaseObject {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column pay_channel_config.id
	 * @ibatorgenerated  Tue Nov 19 15:56:33 CST 2013
	 */
	private Integer id;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column pay_channel_config.channel_id
	 * @ibatorgenerated  Tue Nov 19 15:56:33 CST 2013
	 */
	private Integer channelId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column pay_channel_config.type
	 * @ibatorgenerated  Tue Nov 19 15:56:33 CST 2013
	 */
	private Integer type;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column pay_channel_config.is_show
	 * @ibatorgenerated  Tue Nov 19 15:56:33 CST 2013
	 */
	private Byte isShow;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column pay_channel_config.id
	 * @return  the value of pay_channel_config.id
	 * @ibatorgenerated  Tue Nov 19 15:56:33 CST 2013
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column pay_channel_config.id
	 * @param id  the value for pay_channel_config.id
	 * @ibatorgenerated  Tue Nov 19 15:56:33 CST 2013
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column pay_channel_config.channel_id
	 * @return  the value of pay_channel_config.channel_id
	 * @ibatorgenerated  Tue Nov 19 15:56:33 CST 2013
	 */
	public Integer getChannelId() {
		return channelId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column pay_channel_config.channel_id
	 * @param channelId  the value for pay_channel_config.channel_id
	 * @ibatorgenerated  Tue Nov 19 15:56:33 CST 2013
	 */
	public void setChannelId(Integer channelId) {
		this.channelId = channelId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column pay_channel_config.type
	 * @return  the value of pay_channel_config.type
	 * @ibatorgenerated  Tue Nov 19 15:56:33 CST 2013
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column pay_channel_config.type
	 * @param type  the value for pay_channel_config.type
	 * @ibatorgenerated  Tue Nov 19 15:56:33 CST 2013
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column pay_channel_config.is_show
	 * @return  the value of pay_channel_config.is_show
	 * @ibatorgenerated  Tue Nov 19 15:56:33 CST 2013
	 */
	public Byte getIsShow() {
		return isShow;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column pay_channel_config.is_show
	 * @param isShow  the value for pay_channel_config.is_show
	 * @ibatorgenerated  Tue Nov 19 15:56:33 CST 2013
	 */
	public void setIsShow(Byte isShow) {
		this.isShow = isShow;
	}
}