package com.orange.goldgame.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.juice.orange.game.cached.MemcachedResource;
import com.orange.goldgame.core.Constants;

public class Player extends BaseObject{
    /**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column player.id
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	private Integer id;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column player.nickname
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	private String nickname;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column player.account
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	private String account;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column player.password
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	private String password;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column player.sex
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	private Integer sex;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column player.head_Image
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	private String headImage;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column player.age
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	private Integer age;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column player.appellation
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	private String appellation;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column player.wins
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	private Integer wins;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column player.loses
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	private Integer loses;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column player.days
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	private Integer days;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column player.tag
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	private String tag;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column player.connect
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	private String connect;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column player.date
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	private Date date;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column player.is_Get_Award
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	private Integer isGetAward;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column player.copper
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	private Integer copper;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column player.golds
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	private Integer golds;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column player.is_new_player
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	private Byte isNewPlayer;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column player.isLogin
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	private Integer islogin;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column player.last_login_time
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	private Date lastLoginTime;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column player.online_time
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	private Integer onlineTime;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column player.status
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	private Integer status;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column player.share_times
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	private Integer shareTimes;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column player.channel_id
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	private String channelId;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column player.id
	 * @return  the value of player.id
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column player.id
	 * @param id  the value for player.id
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column player.nickname
	 * @return  the value of player.nickname
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	public String getNickname() {
		return nickname;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column player.nickname
	 * @param nickname  the value for player.nickname
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column player.account
	 * @return  the value of player.account
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	public String getAccount() {
		return account;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column player.account
	 * @param account  the value for player.account
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	public void setAccount(String account) {
		this.account = account;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column player.password
	 * @return  the value of player.password
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column player.password
	 * @param password  the value for player.password
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column player.sex
	 * @return  the value of player.sex
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	public Integer getSex() {
		return sex;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column player.sex
	 * @param sex  the value for player.sex
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	public void setSex(Integer sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column player.head_Image
	 * @return  the value of player.head_Image
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	public String getHeadImage() {
		return headImage;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column player.head_Image
	 * @param headImage  the value for player.head_Image
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	public void setHeadImage(String headImage) {
		this.headImage = headImage;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column player.age
	 * @return  the value of player.age
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	public Integer getAge() {
		return age;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column player.age
	 * @param age  the value for player.age
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	public void setAge(Integer age) {
		this.age = age;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column player.appellation
	 * @return  the value of player.appellation
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	public String getAppellation() {
		return appellation;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column player.appellation
	 * @param appellation  the value for player.appellation
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	public void setAppellation(String appellation) {
		this.appellation = appellation;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column player.wins
	 * @return  the value of player.wins
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	public Integer getWins() {
		return wins;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column player.wins
	 * @param wins  the value for player.wins
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	public void setWins(Integer wins) {
		this.wins = wins;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column player.loses
	 * @return  the value of player.loses
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	public Integer getLoses() {
		return loses;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column player.loses
	 * @param loses  the value for player.loses
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	public void setLoses(Integer loses) {
		this.loses = loses;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column player.days
	 * @return  the value of player.days
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	public Integer getDays() {
		return days;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column player.days
	 * @param days  the value for player.days
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	public void setDays(Integer days) {
		this.days = days;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column player.tag
	 * @return  the value of player.tag
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	public String getTag() {
		return tag;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column player.tag
	 * @param tag  the value for player.tag
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	public void setTag(String tag) {
		this.tag = tag;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column player.connect
	 * @return  the value of player.connect
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	public String getConnect() {
		return connect;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column player.connect
	 * @param connect  the value for player.connect
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	public void setConnect(String connect) {
		this.connect = connect;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column player.date
	 * @return  the value of player.date
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	public Date getDate() {
		return date;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column player.date
	 * @param date  the value for player.date
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	public void setDate(Date date) {
		this.date = date;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column player.is_Get_Award
	 * @return  the value of player.is_Get_Award
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	public Integer getIsGetAward() {
		return isGetAward;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column player.is_Get_Award
	 * @param isGetAward  the value for player.is_Get_Award
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	public void setIsGetAward(Integer isGetAward) {
		this.isGetAward = isGetAward;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column player.copper
	 * @return  the value of player.copper
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	public Integer getCopper() {
		return copper;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column player.copper
	 * @param copper  the value for player.copper
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	public void setCopper(Integer copper) {
		this.copper = copper;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column player.golds
	 * @return  the value of player.golds
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	public Integer getGolds() {
		return golds;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column player.golds
	 * @param golds  the value for player.golds
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	public void setGolds(Integer golds) {
		this.golds = golds;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column player.is_new_player
	 * @return  the value of player.is_new_player
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	public Byte getIsNewPlayer() {
		return isNewPlayer;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column player.is_new_player
	 * @param isNewPlayer  the value for player.is_new_player
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	public void setIsNewPlayer(Byte isNewPlayer) {
		this.isNewPlayer = isNewPlayer;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column player.isLogin
	 * @return  the value of player.isLogin
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	public Integer getIslogin() {
		return islogin;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column player.isLogin
	 * @param islogin  the value for player.isLogin
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	public void setIslogin(Integer islogin) {
		this.islogin = islogin;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column player.last_login_time
	 * @return  the value of player.last_login_time
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	public Date getLastLoginTime() {
		return lastLoginTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column player.last_login_time
	 * @param lastLoginTime  the value for player.last_login_time
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	public void setLastLoginTime(Date lastLoginTime) {
		this.lastLoginTime = lastLoginTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column player.online_time
	 * @return  the value of player.online_time
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	public Integer getOnlineTime() {
		return onlineTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column player.online_time
	 * @param onlineTime  the value for player.online_time
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	public void setOnlineTime(Integer onlineTime) {
		this.onlineTime = onlineTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column player.status
	 * @return  the value of player.status
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column player.status
	 * @param status  the value for player.status
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column player.share_times
	 * @return  the value of player.share_times
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	public Integer getShareTimes() {
		return shareTimes;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column player.share_times
	 * @param shareTimes  the value for player.share_times
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	public void setShareTimes(Integer shareTimes) {
		this.shareTimes = shareTimes;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column player.channel_id
	 * @return  the value of player.channel_id
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	public String getChannelId() {
		return channelId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column player.channel_id
	 * @param channelId  the value for player.channel_id
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	public void setChannelId(String channelId) {
		this.channelId = channelId;
	}

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private Map<Integer, PlayerProps> playerProps = null;
	
	public void setPlayerProps(Map<Integer, PlayerProps> playerProps) {
		this.playerProps = playerProps;
	}

	public Map<Integer, PlayerProps> getPlayerProps() {
		return playerProps;
	}
	
	private Map<Integer,Gift> giftMap = null;
	
	private Map<Integer,PlayerFriend> friendMap = null;

	private Map<String, GetOnce> getoncs = new HashMap<String, GetOnce>();
	
	private Long loginTime = 0L;
	
	private List<PlayerInfoCenter> infoCenter = new ArrayList<PlayerInfoCenter>();

	public Map<String, GetOnce> getGetoncs() {
		return getoncs;
	}

	public void setGetoncs(Map<String, GetOnce> getoncs) {
		this.getoncs = getoncs;
	}

    public Map<Integer, Gift> getGiftMap() {
        return giftMap;
    }

    public void setGiftMap(Map<Integer, Gift> giftMap) {
        this.giftMap = giftMap;
    }

    public Map<Integer, PlayerFriend> getFriendMap() {
        return friendMap;
    }

    public void setFriendMap(Map<Integer, PlayerFriend> friendMap) {
        this.friendMap = friendMap;
    }

    public Long getLoginTime() {
        return loginTime;
    }

    public void setLoginTime(Long loginTime) {
        this.loginTime = loginTime;
    }

    public List<PlayerInfoCenter> getInfoCenter() {
        return infoCenter;
    }

    public void setInfoCenter(List<PlayerInfoCenter> infoCenter) {
        this.infoCenter = infoCenter;
    }

    private PlayerShare playerShare;

	public PlayerShare getPlayerShare() {
		return playerShare;
	}

	public void setPlayerShare(PlayerShare playerShare) {
		this.playerShare = playerShare;
	}
	
//	/**首次充**/
//	private ActivityPayRecord firstPayRecord;
	/**累计充**/
	private ActivityPayRecord sumPayRecord;

//	public ActivityPayRecord getFirstPayRecord() {
//		return firstPayRecord;
//	}
//
//	public void setFirstPayRecord(ActivityPayRecord firstPayRecord) {
//		this.firstPayRecord = firstPayRecord;
//	}

	public ActivityPayRecord getSumPayRecord() {
		return sumPayRecord;
	}

	public void setSumPayRecord(ActivityPayRecord sumPayRecord) {
		this.sumPayRecord = sumPayRecord;
	}
	
	private Map<Integer, Task> playeTask = new HashMap<Integer, Task>();

	public Map<Integer, Task> getPlayeTask() {
		return playeTask;
	}

	public void setPlayeTask(Map<Integer, Task> playeTask) {
		this.playeTask = playeTask;
	}
	
}