package com.orange.goldgame.domain;

public class ServerConfig extends BaseObject{

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column server_config.id
	 * @ibatorgenerated  Thu Jul 04 18:10:48 CST 2013
	 */
	private Integer id;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column server_config.server_ip
	 * @ibatorgenerated  Thu Jul 04 18:10:48 CST 2013
	 */
	private String serverIp;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column server_config.server_port
	 * @ibatorgenerated  Thu Jul 04 18:10:48 CST 2013
	 */
	private Integer serverPort;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column server_config.player_num
	 * @ibatorgenerated  Thu Jul 04 18:10:48 CST 2013
	 */
	private Integer playerNum;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column server_config.id
	 * @return  the value of server_config.id
	 * @ibatorgenerated  Thu Jul 04 18:10:48 CST 2013
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column server_config.id
	 * @param id  the value for server_config.id
	 * @ibatorgenerated  Thu Jul 04 18:10:48 CST 2013
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column server_config.server_ip
	 * @return  the value of server_config.server_ip
	 * @ibatorgenerated  Thu Jul 04 18:10:48 CST 2013
	 */
	public String getServerIp() {
		return serverIp;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column server_config.server_ip
	 * @param serverIp  the value for server_config.server_ip
	 * @ibatorgenerated  Thu Jul 04 18:10:48 CST 2013
	 */
	public void setServerIp(String serverIp) {
		this.serverIp = serverIp;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column server_config.server_port
	 * @return  the value of server_config.server_port
	 * @ibatorgenerated  Thu Jul 04 18:10:48 CST 2013
	 */
	public Integer getServerPort() {
		return serverPort;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column server_config.server_port
	 * @param serverPort  the value for server_config.server_port
	 * @ibatorgenerated  Thu Jul 04 18:10:48 CST 2013
	 */
	public void setServerPort(Integer serverPort) {
		this.serverPort = serverPort;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column server_config.player_num
	 * @return  the value of server_config.player_num
	 * @ibatorgenerated  Thu Jul 04 18:10:48 CST 2013
	 */
	public Integer getPlayerNum() {
		return playerNum;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column server_config.player_num
	 * @param playerNum  the value for server_config.player_num
	 * @ibatorgenerated  Thu Jul 04 18:10:48 CST 2013
	 */
	public void setPlayerNum(Integer playerNum) {
		this.playerNum = playerNum;
	}
}