package com.orange.goldgame.system.dao;

import java.sql.SQLException;
import java.util.List;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.orange.goldgame.domain.ActivityConfig;
import com.orange.goldgame.domain.ActivityConfigExample;

public class ActivityConfigDAOImpl implements ActivityConfigDAO {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table activity_config
     *
     * @ibatorgenerated Wed Sep 11 10:53:31 CST 2013
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table activity_config
     *
     * @ibatorgenerated Wed Sep 11 10:53:31 CST 2013
     */
    public ActivityConfigDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table activity_config
     *
     * @ibatorgenerated Wed Sep 11 10:53:31 CST 2013
     */
    public int countByExample(ActivityConfigExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("activity_config.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table activity_config
     *
     * @ibatorgenerated Wed Sep 11 10:53:31 CST 2013
     */
    public int deleteByExample(ActivityConfigExample example) throws SQLException {
        int rows = sqlMapClient.delete("activity_config.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table activity_config
     *
     * @ibatorgenerated Wed Sep 11 10:53:31 CST 2013
     */
    public int deleteByPrimaryKey(Integer id) throws SQLException {
        ActivityConfig key = new ActivityConfig();
        key.setId(id);
        int rows = sqlMapClient.delete("activity_config.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table activity_config
     *
     * @ibatorgenerated Wed Sep 11 10:53:31 CST 2013
     */
    public Integer insert(ActivityConfig record) throws SQLException {
        Object newKey = sqlMapClient.insert("activity_config.ibatorgenerated_insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table activity_config
     *
     * @ibatorgenerated Wed Sep 11 10:53:31 CST 2013
     */
    public Integer insertSelective(ActivityConfig record) throws SQLException {
        Object newKey = sqlMapClient.insert("activity_config.ibatorgenerated_insertSelective", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table activity_config
     *
     * @ibatorgenerated Wed Sep 11 10:53:31 CST 2013
     */
    public List selectByExample(ActivityConfigExample example) throws SQLException {
        List list = sqlMapClient.queryForList("activity_config.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table activity_config
     *
     * @ibatorgenerated Wed Sep 11 10:53:31 CST 2013
     */
    public ActivityConfig selectByPrimaryKey(Integer id) throws SQLException {
        ActivityConfig key = new ActivityConfig();
        key.setId(id);
        ActivityConfig record = (ActivityConfig) sqlMapClient.queryForObject("activity_config.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table activity_config
     *
     * @ibatorgenerated Wed Sep 11 10:53:31 CST 2013
     */
    public int updateByExampleSelective(ActivityConfig record, ActivityConfigExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("activity_config.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table activity_config
     *
     * @ibatorgenerated Wed Sep 11 10:53:31 CST 2013
     */
    public int updateByExample(ActivityConfig record, ActivityConfigExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("activity_config.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table activity_config
     *
     * @ibatorgenerated Wed Sep 11 10:53:31 CST 2013
     */
    public int updateByPrimaryKeySelective(ActivityConfig record) throws SQLException {
        int rows = sqlMapClient.update("activity_config.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table activity_config
     *
     * @ibatorgenerated Wed Sep 11 10:53:31 CST 2013
     */
    public int updateByPrimaryKey(ActivityConfig record) throws SQLException {
        int rows = sqlMapClient.update("activity_config.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table activity_config
     *
     * @ibatorgenerated Wed Sep 11 10:53:31 CST 2013
     */
    private static class UpdateByExampleParms extends ActivityConfigExample {
        private Object record;

        public UpdateByExampleParms(Object record, ActivityConfigExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}