package com.orange.goldgame.system.dao;

import java.sql.SQLException;
import java.util.List;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.orange.goldgame.domain.AreaConfig;
import com.orange.goldgame.domain.AreaConfigExample;

public class AreaConfigDAOImpl implements AreaConfigDAO {

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database table area_config
     * @ibatorgenerated  Tue Sep 24 10:33:39 CST 2013
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table area_config
     * @ibatorgenerated  Tue Sep 24 10:33:39 CST 2013
     */
    public AreaConfigDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table area_config
     * @ibatorgenerated  Tue Sep 24 10:33:39 CST 2013
     */
    public int countByExample(AreaConfigExample example) throws SQLException {
        Integer count = (Integer) sqlMapClient.queryForObject(
                "area_config.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table area_config
     * @ibatorgenerated  Tue Sep 24 10:33:39 CST 2013
     */
    public int deleteByExample(AreaConfigExample example) throws SQLException {
        int rows = sqlMapClient.delete(
                "area_config.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table area_config
     * @ibatorgenerated  Tue Sep 24 10:33:39 CST 2013
     */
    public int deleteByPrimaryKey(Integer id) throws SQLException {
        AreaConfig key = new AreaConfig();
        key.setId(id);
        int rows = sqlMapClient.delete(
                "area_config.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table area_config
     * @ibatorgenerated  Tue Sep 24 10:33:39 CST 2013
     */
    public Integer insert(AreaConfig record) throws SQLException {
        Object newKey = sqlMapClient.insert(
                "area_config.ibatorgenerated_insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table area_config
     * @ibatorgenerated  Tue Sep 24 10:33:39 CST 2013
     */
    public Integer insertSelective(AreaConfig record) throws SQLException {
        Object newKey = sqlMapClient.insert(
                "area_config.ibatorgenerated_insertSelective", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table area_config
     * @ibatorgenerated  Tue Sep 24 10:33:39 CST 2013
     */
    public List selectByExample(AreaConfigExample example) throws SQLException {
        List list = sqlMapClient.queryForList(
                "area_config.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table area_config
     * @ibatorgenerated  Tue Sep 24 10:33:39 CST 2013
     */
    public AreaConfig selectByPrimaryKey(Integer id) throws SQLException {
        AreaConfig key = new AreaConfig();
        key.setId(id);
        AreaConfig record = (AreaConfig) sqlMapClient.queryForObject(
                "area_config.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table area_config
     * @ibatorgenerated  Tue Sep 24 10:33:39 CST 2013
     */
    public int updateByExampleSelective(AreaConfig record,
            AreaConfigExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update(
                "area_config.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table area_config
     * @ibatorgenerated  Tue Sep 24 10:33:39 CST 2013
     */
    public int updateByExample(AreaConfig record, AreaConfigExample example)
            throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update(
                "area_config.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table area_config
     * @ibatorgenerated  Tue Sep 24 10:33:39 CST 2013
     */
    public int updateByPrimaryKeySelective(AreaConfig record)
            throws SQLException {
        int rows = sqlMapClient.update(
                "area_config.ibatorgenerated_updateByPrimaryKeySelective",
                record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table area_config
     * @ibatorgenerated  Tue Sep 24 10:33:39 CST 2013
     */
    public int updateByPrimaryKey(AreaConfig record) throws SQLException {
        int rows = sqlMapClient.update(
                "area_config.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator. This class corresponds to the database table area_config
     * @ibatorgenerated  Tue Sep 24 10:33:39 CST 2013
     */
    private static class UpdateByExampleParms extends AreaConfigExample {
        private Object record;

        public UpdateByExampleParms(Object record, AreaConfigExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}