package com.orange.goldgame.system.dao;

import java.sql.SQLException;
import java.util.List;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.orange.goldgame.domain.GetPrize;
import com.orange.goldgame.domain.GetPrizeExample;

public class GetPrizeDAOImpl implements GetPrizeDAO {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table get_prize
     *
     * @ibatorgenerated Mon Jul 15 09:59:23 CST 2013
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table get_prize
     *
     * @ibatorgenerated Mon Jul 15 09:59:23 CST 2013
     */
    public GetPrizeDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table get_prize
     *
     * @ibatorgenerated Mon Jul 15 09:59:23 CST 2013
     */
    public int countByExample(GetPrizeExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("get_prize.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table get_prize
     *
     * @ibatorgenerated Mon Jul 15 09:59:23 CST 2013
     */
    public int deleteByExample(GetPrizeExample example) throws SQLException {
        int rows = sqlMapClient.delete("get_prize.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table get_prize
     *
     * @ibatorgenerated Mon Jul 15 09:59:23 CST 2013
     */
    public int deleteByPrimaryKey(Integer id) throws SQLException {
        GetPrize key = new GetPrize();
        key.setId(id);
        int rows = sqlMapClient.delete("get_prize.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table get_prize
     *
     * @ibatorgenerated Mon Jul 15 09:59:23 CST 2013
     */
    public Integer insert(GetPrize record) throws SQLException {
        Object newKey = sqlMapClient.insert("get_prize.ibatorgenerated_insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table get_prize
     *
     * @ibatorgenerated Mon Jul 15 09:59:23 CST 2013
     */
    public Integer insertSelective(GetPrize record) throws SQLException {
        Object newKey = sqlMapClient.insert("get_prize.ibatorgenerated_insertSelective", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table get_prize
     *
     * @ibatorgenerated Mon Jul 15 09:59:23 CST 2013
     */
    public List selectByExample(GetPrizeExample example) throws SQLException {
        List list = sqlMapClient.queryForList("get_prize.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table get_prize
     *
     * @ibatorgenerated Mon Jul 15 09:59:23 CST 2013
     */
    public GetPrize selectByPrimaryKey(Integer id) throws SQLException {
        GetPrize key = new GetPrize();
        key.setId(id);
        GetPrize record = (GetPrize) sqlMapClient.queryForObject("get_prize.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table get_prize
     *
     * @ibatorgenerated Mon Jul 15 09:59:23 CST 2013
     */
    public int updateByExampleSelective(GetPrize record, GetPrizeExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("get_prize.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table get_prize
     *
     * @ibatorgenerated Mon Jul 15 09:59:23 CST 2013
     */
    public int updateByExample(GetPrize record, GetPrizeExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("get_prize.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table get_prize
     *
     * @ibatorgenerated Mon Jul 15 09:59:23 CST 2013
     */
    public int updateByPrimaryKeySelective(GetPrize record) throws SQLException {
        int rows = sqlMapClient.update("get_prize.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table get_prize
     *
     * @ibatorgenerated Mon Jul 15 09:59:23 CST 2013
     */
    public int updateByPrimaryKey(GetPrize record) throws SQLException {
        int rows = sqlMapClient.update("get_prize.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table get_prize
     *
     * @ibatorgenerated Mon Jul 15 09:59:23 CST 2013
     */
    private static class UpdateByExampleParms extends GetPrizeExample {
        private Object record;

        public UpdateByExampleParms(Object record, GetPrizeExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}