package com.orange.goldgame.system.dao;

import java.sql.SQLException;
import java.util.List;

import com.orange.goldgame.domain.GetPrize;
import com.orange.goldgame.domain.GetPrizeExample;

public interface GetPrizeDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table get_prize
     *
     * @ibatorgenerated Mon Jul 15 09:59:23 CST 2013
     */
    int countByExample(GetPrizeExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table get_prize
     *
     * @ibatorgenerated Mon Jul 15 09:59:23 CST 2013
     */
    int deleteByExample(GetPrizeExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table get_prize
     *
     * @ibatorgenerated Mon Jul 15 09:59:23 CST 2013
     */
    int deleteByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table get_prize
     *
     * @ibatorgenerated Mon Jul 15 09:59:23 CST 2013
     */
    Integer insert(GetPrize record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table get_prize
     *
     * @ibatorgenerated Mon Jul 15 09:59:23 CST 2013
     */
    Integer insertSelective(GetPrize record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table get_prize
     *
     * @ibatorgenerated Mon Jul 15 09:59:23 CST 2013
     */
    List selectByExample(GetPrizeExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table get_prize
     *
     * @ibatorgenerated Mon Jul 15 09:59:23 CST 2013
     */
    GetPrize selectByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table get_prize
     *
     * @ibatorgenerated Mon Jul 15 09:59:23 CST 2013
     */
    int updateByExampleSelective(GetPrize record, GetPrizeExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table get_prize
     *
     * @ibatorgenerated Mon Jul 15 09:59:23 CST 2013
     */
    int updateByExample(GetPrize record, GetPrizeExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table get_prize
     *
     * @ibatorgenerated Mon Jul 15 09:59:23 CST 2013
     */
    int updateByPrimaryKeySelective(GetPrize record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table get_prize
     *
     * @ibatorgenerated Mon Jul 15 09:59:23 CST 2013
     */
    int updateByPrimaryKey(GetPrize record) throws SQLException;
}