package com.orange.goldgame.system.dao;

import java.sql.SQLException;
import java.util.List;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.orange.goldgame.domain.Gift;
import com.orange.goldgame.domain.GiftExample;

public class GiftDAOImpl implements GiftDAO {

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database table gift
     * @ibatorgenerated  Wed Jul 24 16:28:11 CST 2013
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table gift
     * @ibatorgenerated  Wed Jul 24 16:28:11 CST 2013
     */
    public GiftDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table gift
     * @ibatorgenerated  Wed Jul 24 16:28:11 CST 2013
     */
    public int countByExample(GiftExample example) throws SQLException {
        Integer count = (Integer) sqlMapClient.queryForObject(
                "gift.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table gift
     * @ibatorgenerated  Wed Jul 24 16:28:11 CST 2013
     */
    public int deleteByExample(GiftExample example) throws SQLException {
        int rows = sqlMapClient.delete("gift.ibatorgenerated_deleteByExample",
                example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table gift
     * @ibatorgenerated  Wed Jul 24 16:28:11 CST 2013
     */
    public int deleteByPrimaryKey(Integer id) throws SQLException {
        Gift key = new Gift();
        key.setId(id);
        int rows = sqlMapClient.delete(
                "gift.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table gift
     * @ibatorgenerated  Wed Jul 24 16:28:11 CST 2013
     */
    public Integer insert(Gift record) throws SQLException {
        Object newKey = sqlMapClient.insert("gift.ibatorgenerated_insert",
                record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table gift
     * @ibatorgenerated  Wed Jul 24 16:28:11 CST 2013
     */
    public Integer insertSelective(Gift record) throws SQLException {
        Object newKey = sqlMapClient.insert(
                "gift.ibatorgenerated_insertSelective", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table gift
     * @ibatorgenerated  Wed Jul 24 16:28:11 CST 2013
     */
    public List selectByExample(GiftExample example) throws SQLException {
        List list = sqlMapClient.queryForList(
                "gift.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table gift
     * @ibatorgenerated  Wed Jul 24 16:28:11 CST 2013
     */
    public Gift selectByPrimaryKey(Integer id) throws SQLException {
        Gift key = new Gift();
        key.setId(id);
        Gift record = (Gift) sqlMapClient.queryForObject(
                "gift.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table gift
     * @ibatorgenerated  Wed Jul 24 16:28:11 CST 2013
     */
    public int updateByExampleSelective(Gift record, GiftExample example)
            throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update(
                "gift.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table gift
     * @ibatorgenerated  Wed Jul 24 16:28:11 CST 2013
     */
    public int updateByExample(Gift record, GiftExample example)
            throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("gift.ibatorgenerated_updateByExample",
                parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table gift
     * @ibatorgenerated  Wed Jul 24 16:28:11 CST 2013
     */
    public int updateByPrimaryKeySelective(Gift record) throws SQLException {
        int rows = sqlMapClient.update(
                "gift.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table gift
     * @ibatorgenerated  Wed Jul 24 16:28:11 CST 2013
     */
    public int updateByPrimaryKey(Gift record) throws SQLException {
        int rows = sqlMapClient.update(
                "gift.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator. This class corresponds to the database table gift
     * @ibatorgenerated  Wed Jul 24 16:28:11 CST 2013
     */
    private static class UpdateByExampleParms extends GiftExample {
        private Object record;

        public UpdateByExampleParms(Object record, GiftExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}