package com.orange.goldgame.system.dao;

import java.sql.SQLException;
import java.util.List;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.orange.goldgame.domain.HelpType;
import com.orange.goldgame.domain.HelpTypeExample;

public class HelpTypeDAOImpl implements HelpTypeDAO {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table help_type
     *
     * @ibatorgenerated Wed Jul 24 10:23:54 CST 2013
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table help_type
     *
     * @ibatorgenerated Wed Jul 24 10:23:54 CST 2013
     */
    public HelpTypeDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table help_type
     *
     * @ibatorgenerated Wed Jul 24 10:23:54 CST 2013
     */
    public int countByExample(HelpTypeExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("help_type.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table help_type
     *
     * @ibatorgenerated Wed Jul 24 10:23:54 CST 2013
     */
    public int deleteByExample(HelpTypeExample example) throws SQLException {
        int rows = sqlMapClient.delete("help_type.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table help_type
     *
     * @ibatorgenerated Wed Jul 24 10:23:54 CST 2013
     */
    public int deleteByPrimaryKey(Integer id) throws SQLException {
        HelpType key = new HelpType();
        key.setId(id);
        int rows = sqlMapClient.delete("help_type.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table help_type
     *
     * @ibatorgenerated Wed Jul 24 10:23:54 CST 2013
     */
    public Integer insert(HelpType record) throws SQLException {
        Object newKey = sqlMapClient.insert("help_type.ibatorgenerated_insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table help_type
     *
     * @ibatorgenerated Wed Jul 24 10:23:54 CST 2013
     */
    public Integer insertSelective(HelpType record) throws SQLException {
        Object newKey = sqlMapClient.insert("help_type.ibatorgenerated_insertSelective", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table help_type
     *
     * @ibatorgenerated Wed Jul 24 10:23:54 CST 2013
     */
    public List selectByExample(HelpTypeExample example) throws SQLException {
        List list = sqlMapClient.queryForList("help_type.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table help_type
     *
     * @ibatorgenerated Wed Jul 24 10:23:54 CST 2013
     */
    public HelpType selectByPrimaryKey(Integer id) throws SQLException {
        HelpType key = new HelpType();
        key.setId(id);
        HelpType record = (HelpType) sqlMapClient.queryForObject("help_type.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table help_type
     *
     * @ibatorgenerated Wed Jul 24 10:23:54 CST 2013
     */
    public int updateByExampleSelective(HelpType record, HelpTypeExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("help_type.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table help_type
     *
     * @ibatorgenerated Wed Jul 24 10:23:54 CST 2013
     */
    public int updateByExample(HelpType record, HelpTypeExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("help_type.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table help_type
     *
     * @ibatorgenerated Wed Jul 24 10:23:54 CST 2013
     */
    public int updateByPrimaryKeySelective(HelpType record) throws SQLException {
        int rows = sqlMapClient.update("help_type.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table help_type
     *
     * @ibatorgenerated Wed Jul 24 10:23:54 CST 2013
     */
    public int updateByPrimaryKey(HelpType record) throws SQLException {
        int rows = sqlMapClient.update("help_type.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table help_type
     *
     * @ibatorgenerated Wed Jul 24 10:23:54 CST 2013
     */
    private static class UpdateByExampleParms extends HelpTypeExample {
        private Object record;

        public UpdateByExampleParms(Object record, HelpTypeExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}