package com.orange.goldgame.system.dao;

import java.sql.SQLException;
import java.util.List;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.orange.goldgame.domain.NoticeConfig;
import com.orange.goldgame.domain.NoticeConfigExample;

public class NoticeConfigDAOImpl implements NoticeConfigDAO {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table notice_config
     *
     * @ibatorgenerated Thu Jul 11 18:08:21 CST 2013
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table notice_config
     *
     * @ibatorgenerated Thu Jul 11 18:08:21 CST 2013
     */
    public NoticeConfigDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table notice_config
     *
     * @ibatorgenerated Thu Jul 11 18:08:21 CST 2013
     */
    public int countByExample(NoticeConfigExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("notice_config.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table notice_config
     *
     * @ibatorgenerated Thu Jul 11 18:08:21 CST 2013
     */
    public int deleteByExample(NoticeConfigExample example) throws SQLException {
        int rows = sqlMapClient.delete("notice_config.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table notice_config
     *
     * @ibatorgenerated Thu Jul 11 18:08:21 CST 2013
     */
    public int deleteByPrimaryKey(Integer id) throws SQLException {
        NoticeConfig key = new NoticeConfig();
        key.setId(id);
        int rows = sqlMapClient.delete("notice_config.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table notice_config
     *
     * @ibatorgenerated Thu Jul 11 18:08:21 CST 2013
     */
    public Integer insert(NoticeConfig record) throws SQLException {
        Object newKey = sqlMapClient.insert("notice_config.ibatorgenerated_insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table notice_config
     *
     * @ibatorgenerated Thu Jul 11 18:08:21 CST 2013
     */
    public Integer insertSelective(NoticeConfig record) throws SQLException {
        Object newKey = sqlMapClient.insert("notice_config.ibatorgenerated_insertSelective", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table notice_config
     *
     * @ibatorgenerated Thu Jul 11 18:08:21 CST 2013
     */
    public List selectByExample(NoticeConfigExample example) throws SQLException {
        List list = sqlMapClient.queryForList("notice_config.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table notice_config
     *
     * @ibatorgenerated Thu Jul 11 18:08:21 CST 2013
     */
    public NoticeConfig selectByPrimaryKey(Integer id) throws SQLException {
        NoticeConfig key = new NoticeConfig();
        key.setId(id);
        NoticeConfig record = (NoticeConfig) sqlMapClient.queryForObject("notice_config.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table notice_config
     *
     * @ibatorgenerated Thu Jul 11 18:08:21 CST 2013
     */
    public int updateByExampleSelective(NoticeConfig record, NoticeConfigExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("notice_config.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table notice_config
     *
     * @ibatorgenerated Thu Jul 11 18:08:21 CST 2013
     */
    public int updateByExample(NoticeConfig record, NoticeConfigExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("notice_config.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table notice_config
     *
     * @ibatorgenerated Thu Jul 11 18:08:21 CST 2013
     */
    public int updateByPrimaryKeySelective(NoticeConfig record) throws SQLException {
        int rows = sqlMapClient.update("notice_config.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table notice_config
     *
     * @ibatorgenerated Thu Jul 11 18:08:21 CST 2013
     */
    public int updateByPrimaryKey(NoticeConfig record) throws SQLException {
        int rows = sqlMapClient.update("notice_config.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table notice_config
     *
     * @ibatorgenerated Thu Jul 11 18:08:21 CST 2013
     */
    private static class UpdateByExampleParms extends NoticeConfigExample {
        private Object record;

        public UpdateByExampleParms(Object record, NoticeConfigExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}