package com.orange.goldgame.system.dao;

import java.sql.SQLException;
import java.util.List;

import com.orange.goldgame.domain.NoticeConfig;
import com.orange.goldgame.domain.NoticeConfigExample;

public interface NoticeConfigDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table notice_config
     *
     * @ibatorgenerated Thu Jul 11 18:08:21 CST 2013
     */
    int countByExample(NoticeConfigExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table notice_config
     *
     * @ibatorgenerated Thu Jul 11 18:08:21 CST 2013
     */
    int deleteByExample(NoticeConfigExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table notice_config
     *
     * @ibatorgenerated Thu Jul 11 18:08:21 CST 2013
     */
    int deleteByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table notice_config
     *
     * @ibatorgenerated Thu Jul 11 18:08:21 CST 2013
     */
    Integer insert(NoticeConfig record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table notice_config
     *
     * @ibatorgenerated Thu Jul 11 18:08:21 CST 2013
     */
    Integer insertSelective(NoticeConfig record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table notice_config
     *
     * @ibatorgenerated Thu Jul 11 18:08:21 CST 2013
     */
    List selectByExample(NoticeConfigExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table notice_config
     *
     * @ibatorgenerated Thu Jul 11 18:08:21 CST 2013
     */
    NoticeConfig selectByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table notice_config
     *
     * @ibatorgenerated Thu Jul 11 18:08:21 CST 2013
     */
    int updateByExampleSelective(NoticeConfig record, NoticeConfigExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table notice_config
     *
     * @ibatorgenerated Thu Jul 11 18:08:21 CST 2013
     */
    int updateByExample(NoticeConfig record, NoticeConfigExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table notice_config
     *
     * @ibatorgenerated Thu Jul 11 18:08:21 CST 2013
     */
    int updateByPrimaryKeySelective(NoticeConfig record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table notice_config
     *
     * @ibatorgenerated Thu Jul 11 18:08:21 CST 2013
     */
    int updateByPrimaryKey(NoticeConfig record) throws SQLException;
}