package com.orange.goldgame.system.dao;

import java.sql.SQLException;
import java.util.List;

import com.orange.goldgame.domain.PayChannelConfig;
import com.orange.goldgame.domain.PayChannelConfigExample;

public interface PayChannelConfigDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table pay_channel_config
	 * @ibatorgenerated  Tue Nov 19 15:56:33 CST 2013
	 */
	int countByExample(PayChannelConfigExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table pay_channel_config
	 * @ibatorgenerated  Tue Nov 19 15:56:33 CST 2013
	 */
	int deleteByExample(PayChannelConfigExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table pay_channel_config
	 * @ibatorgenerated  Tue Nov 19 15:56:33 CST 2013
	 */
	int deleteByPrimaryKey(Integer id) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table pay_channel_config
	 * @ibatorgenerated  Tue Nov 19 15:56:33 CST 2013
	 */
	Integer insert(PayChannelConfig record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table pay_channel_config
	 * @ibatorgenerated  Tue Nov 19 15:56:33 CST 2013
	 */
	Integer insertSelective(PayChannelConfig record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table pay_channel_config
	 * @ibatorgenerated  Tue Nov 19 15:56:33 CST 2013
	 */
	List selectByExample(PayChannelConfigExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table pay_channel_config
	 * @ibatorgenerated  Tue Nov 19 15:56:33 CST 2013
	 */
	PayChannelConfig selectByPrimaryKey(Integer id) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table pay_channel_config
	 * @ibatorgenerated  Tue Nov 19 15:56:33 CST 2013
	 */
	int updateByExampleSelective(PayChannelConfig record,
			PayChannelConfigExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table pay_channel_config
	 * @ibatorgenerated  Tue Nov 19 15:56:33 CST 2013
	 */
	int updateByExample(PayChannelConfig record, PayChannelConfigExample example)
			throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table pay_channel_config
	 * @ibatorgenerated  Tue Nov 19 15:56:33 CST 2013
	 */
	int updateByPrimaryKeySelective(PayChannelConfig record)
			throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table pay_channel_config
	 * @ibatorgenerated  Tue Nov 19 15:56:33 CST 2013
	 */
	int updateByPrimaryKey(PayChannelConfig record) throws SQLException;
}