package com.orange.goldgame.system.dao;

import java.sql.SQLException;
import java.util.List;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.orange.goldgame.domain.PayInfo;
import com.orange.goldgame.domain.PayInfoExample;

public class PayInfoDAOImpl implements PayInfoDAO {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table pay_info
	 * @ibatorgenerated  Sun Sep 15 11:15:20 CST 2013
	 */
	private SqlMapClient sqlMapClient;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table pay_info
	 * @ibatorgenerated  Sun Sep 15 11:15:20 CST 2013
	 */
	public PayInfoDAOImpl(SqlMapClient sqlMapClient) {
		super();
		this.sqlMapClient = sqlMapClient;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table pay_info
	 * @ibatorgenerated  Sun Sep 15 11:15:20 CST 2013
	 */
	public int countByExample(PayInfoExample example) throws SQLException {
		Integer count = (Integer) sqlMapClient.queryForObject(
				"pay_info.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table pay_info
	 * @ibatorgenerated  Sun Sep 15 11:15:20 CST 2013
	 */
	public int deleteByExample(PayInfoExample example) throws SQLException {
		int rows = sqlMapClient.delete(
				"pay_info.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table pay_info
	 * @ibatorgenerated  Sun Sep 15 11:15:20 CST 2013
	 */
	public int deleteByPrimaryKey(Integer id) throws SQLException {
		PayInfo key = new PayInfo();
		key.setId(id);
		int rows = sqlMapClient.delete(
				"pay_info.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table pay_info
	 * @ibatorgenerated  Sun Sep 15 11:15:20 CST 2013
	 */
	public Integer insert(PayInfo record) throws SQLException {
		Object newKey = sqlMapClient.insert("pay_info.ibatorgenerated_insert",
				record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table pay_info
	 * @ibatorgenerated  Sun Sep 15 11:15:20 CST 2013
	 */
	public Integer insertSelective(PayInfo record) throws SQLException {
		Object newKey = sqlMapClient.insert(
				"pay_info.ibatorgenerated_insertSelective", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table pay_info
	 * @ibatorgenerated  Sun Sep 15 11:15:20 CST 2013
	 */
	public List selectByExample(PayInfoExample example) throws SQLException {
		List list = sqlMapClient.queryForList(
				"pay_info.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table pay_info
	 * @ibatorgenerated  Sun Sep 15 11:15:20 CST 2013
	 */
	public PayInfo selectByPrimaryKey(Integer id) throws SQLException {
		PayInfo key = new PayInfo();
		key.setId(id);
		PayInfo record = (PayInfo) sqlMapClient.queryForObject(
				"pay_info.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table pay_info
	 * @ibatorgenerated  Sun Sep 15 11:15:20 CST 2013
	 */
	public int updateByExampleSelective(PayInfo record, PayInfoExample example)
			throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"pay_info.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table pay_info
	 * @ibatorgenerated  Sun Sep 15 11:15:20 CST 2013
	 */
	public int updateByExample(PayInfo record, PayInfoExample example)
			throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"pay_info.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table pay_info
	 * @ibatorgenerated  Sun Sep 15 11:15:20 CST 2013
	 */
	public int updateByPrimaryKeySelective(PayInfo record) throws SQLException {
		int rows = sqlMapClient.update(
				"pay_info.ibatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table pay_info
	 * @ibatorgenerated  Sun Sep 15 11:15:20 CST 2013
	 */
	public int updateByPrimaryKey(PayInfo record) throws SQLException {
		int rows = sqlMapClient.update(
				"pay_info.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table pay_info
	 * @ibatorgenerated  Sun Sep 15 11:15:20 CST 2013
	 */
	private static class UpdateByExampleParms extends PayInfoExample {
		private Object record;

		public UpdateByExampleParms(Object record, PayInfoExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}