package com.orange.goldgame.system.dao;

import java.sql.SQLException;
import java.util.List;

import com.orange.goldgame.domain.PayInfo;
import com.orange.goldgame.domain.PayInfoExample;

public interface PayInfoDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table pay_info
	 * @ibatorgenerated  Sun Sep 15 11:15:20 CST 2013
	 */
	int countByExample(PayInfoExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table pay_info
	 * @ibatorgenerated  Sun Sep 15 11:15:20 CST 2013
	 */
	int deleteByExample(PayInfoExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table pay_info
	 * @ibatorgenerated  Sun Sep 15 11:15:20 CST 2013
	 */
	int deleteByPrimaryKey(Integer id) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table pay_info
	 * @ibatorgenerated  Sun Sep 15 11:15:20 CST 2013
	 */
	Integer insert(PayInfo record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table pay_info
	 * @ibatorgenerated  Sun Sep 15 11:15:20 CST 2013
	 */
	Integer insertSelective(PayInfo record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table pay_info
	 * @ibatorgenerated  Sun Sep 15 11:15:20 CST 2013
	 */
	List selectByExample(PayInfoExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table pay_info
	 * @ibatorgenerated  Sun Sep 15 11:15:20 CST 2013
	 */
	PayInfo selectByPrimaryKey(Integer id) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table pay_info
	 * @ibatorgenerated  Sun Sep 15 11:15:20 CST 2013
	 */
	int updateByExampleSelective(PayInfo record, PayInfoExample example)
			throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table pay_info
	 * @ibatorgenerated  Sun Sep 15 11:15:20 CST 2013
	 */
	int updateByExample(PayInfo record, PayInfoExample example)
			throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table pay_info
	 * @ibatorgenerated  Sun Sep 15 11:15:20 CST 2013
	 */
	int updateByPrimaryKeySelective(PayInfo record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table pay_info
	 * @ibatorgenerated  Sun Sep 15 11:15:20 CST 2013
	 */
	int updateByPrimaryKey(PayInfo record) throws SQLException;
}