package com.orange.goldgame.system.dao;

import java.sql.SQLException;
import java.util.List;

import com.orange.goldgame.domain.PlayerInfoCenter;
import com.orange.goldgame.domain.PlayerInfoCenterExample;

public interface PlayerInfoCenterDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_info_center
	 * @ibatorgenerated  Fri Sep 13 20:23:44 CST 2013
	 */
	int countByExample(PlayerInfoCenterExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_info_center
	 * @ibatorgenerated  Fri Sep 13 20:23:44 CST 2013
	 */
	int deleteByExample(PlayerInfoCenterExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_info_center
	 * @ibatorgenerated  Fri Sep 13 20:23:44 CST 2013
	 */
	int deleteByPrimaryKey(Integer id) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_info_center
	 * @ibatorgenerated  Fri Sep 13 20:23:44 CST 2013
	 */
	Integer insert(PlayerInfoCenter record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_info_center
	 * @ibatorgenerated  Fri Sep 13 20:23:44 CST 2013
	 */
	Integer insertSelective(PlayerInfoCenter record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_info_center
	 * @ibatorgenerated  Fri Sep 13 20:23:44 CST 2013
	 */
	List selectByExample(PlayerInfoCenterExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_info_center
	 * @ibatorgenerated  Fri Sep 13 20:23:44 CST 2013
	 */
	PlayerInfoCenter selectByPrimaryKey(Integer id) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_info_center
	 * @ibatorgenerated  Fri Sep 13 20:23:44 CST 2013
	 */
	int updateByExampleSelective(PlayerInfoCenter record,
			PlayerInfoCenterExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_info_center
	 * @ibatorgenerated  Fri Sep 13 20:23:44 CST 2013
	 */
	int updateByExample(PlayerInfoCenter record, PlayerInfoCenterExample example)
			throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_info_center
	 * @ibatorgenerated  Fri Sep 13 20:23:44 CST 2013
	 */
	int updateByPrimaryKeySelective(PlayerInfoCenter record)
			throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_info_center
	 * @ibatorgenerated  Fri Sep 13 20:23:44 CST 2013
	 */
	int updateByPrimaryKey(PlayerInfoCenter record) throws SQLException;
}