package com.orange.goldgame.system.dao;

import com.orange.goldgame.domain.PlayerShareInfo;
import com.orange.goldgame.domain.PlayerShareInfoExample;
import java.sql.SQLException;
import java.util.List;

public interface PlayerShareInfoDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_share_info
     *
     * @ibatorgenerated Fri Oct 25 09:38:45 CST 2013
     */
    int countByExample(PlayerShareInfoExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_share_info
     *
     * @ibatorgenerated Fri Oct 25 09:38:45 CST 2013
     */
    int deleteByExample(PlayerShareInfoExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_share_info
     *
     * @ibatorgenerated Fri Oct 25 09:38:45 CST 2013
     */
    int deleteByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_share_info
     *
     * @ibatorgenerated Fri Oct 25 09:38:45 CST 2013
     */
    Integer insert(PlayerShareInfo record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_share_info
     *
     * @ibatorgenerated Fri Oct 25 09:38:45 CST 2013
     */
    Integer insertSelective(PlayerShareInfo record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_share_info
     *
     * @ibatorgenerated Fri Oct 25 09:38:45 CST 2013
     */
    List selectByExample(PlayerShareInfoExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_share_info
     *
     * @ibatorgenerated Fri Oct 25 09:38:45 CST 2013
     */
    PlayerShareInfo selectByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_share_info
     *
     * @ibatorgenerated Fri Oct 25 09:38:45 CST 2013
     */
    int updateByExampleSelective(PlayerShareInfo record, PlayerShareInfoExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_share_info
     *
     * @ibatorgenerated Fri Oct 25 09:38:45 CST 2013
     */
    int updateByExample(PlayerShareInfo record, PlayerShareInfoExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_share_info
     *
     * @ibatorgenerated Fri Oct 25 09:38:45 CST 2013
     */
    int updateByPrimaryKeySelective(PlayerShareInfo record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_share_info
     *
     * @ibatorgenerated Fri Oct 25 09:38:45 CST 2013
     */
    int updateByPrimaryKey(PlayerShareInfo record) throws SQLException;
}