package com.orange.goldgame.system.dao;

import java.sql.SQLException;
import java.util.List;

import com.orange.goldgame.domain.Player;
import com.orange.goldgame.domain.PlayerExample;

public interface PlayerDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	int countByExample(PlayerExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	int deleteByExample(PlayerExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	int deleteByPrimaryKey(Integer id) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	Integer insert(Player record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	Integer insertSelective(Player record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	List selectByExample(PlayerExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	Player selectByPrimaryKey(Integer id) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	int updateByExampleSelective(Player record, PlayerExample example)
			throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	int updateByExample(Player record, PlayerExample example)
			throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	int updateByPrimaryKeySelective(Player record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player
	 * @ibatorgenerated  Fri Dec 20 10:50:44 CST 2013
	 */
	int updateByPrimaryKey(Player record) throws SQLException;
}