package com.orange.goldgame.system.dao;

import java.sql.SQLException;
import java.util.List;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.orange.goldgame.domain.PlayerFriend;
import com.orange.goldgame.domain.PlayerFriendExample;

public class PlayerFriendDAOImpl implements PlayerFriendDAO {

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database table player_friend
     * @ibatorgenerated  Wed Jul 17 17:16:01 CST 2013
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_friend
     * @ibatorgenerated  Wed Jul 17 17:16:01 CST 2013
     */
    public PlayerFriendDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_friend
     * @ibatorgenerated  Wed Jul 17 17:16:01 CST 2013
     */
    public int countByExample(PlayerFriendExample example) throws SQLException {
        Integer count = (Integer) sqlMapClient.queryForObject(
                "player_friend.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_friend
     * @ibatorgenerated  Wed Jul 17 17:16:01 CST 2013
     */
    public int deleteByExample(PlayerFriendExample example) throws SQLException {
        int rows = sqlMapClient.delete(
                "player_friend.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_friend
     * @ibatorgenerated  Wed Jul 17 17:16:01 CST 2013
     */
    public int deleteByPrimaryKey(Integer id) throws SQLException {
        PlayerFriend key = new PlayerFriend();
        key.setId(id);
        int rows = sqlMapClient.delete(
                "player_friend.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_friend
     * @ibatorgenerated  Wed Jul 17 17:16:01 CST 2013
     */
    public Integer insert(PlayerFriend record) throws SQLException {
        Object newKey = sqlMapClient.insert(
                "player_friend.ibatorgenerated_insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_friend
     * @ibatorgenerated  Wed Jul 17 17:16:01 CST 2013
     */
    public Integer insertSelective(PlayerFriend record) throws SQLException {
        Object newKey = sqlMapClient.insert(
                "player_friend.ibatorgenerated_insertSelective", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_friend
     * @ibatorgenerated  Wed Jul 17 17:16:01 CST 2013
     */
    public List selectByExample(PlayerFriendExample example)
            throws SQLException {
        List list = sqlMapClient.queryForList(
                "player_friend.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_friend
     * @ibatorgenerated  Wed Jul 17 17:16:01 CST 2013
     */
    public PlayerFriend selectByPrimaryKey(Integer id) throws SQLException {
        PlayerFriend key = new PlayerFriend();
        key.setId(id);
        PlayerFriend record = (PlayerFriend) sqlMapClient.queryForObject(
                "player_friend.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_friend
     * @ibatorgenerated  Wed Jul 17 17:16:01 CST 2013
     */
    public int updateByExampleSelective(PlayerFriend record,
            PlayerFriendExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient
                .update("player_friend.ibatorgenerated_updateByExampleSelective",
                        parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_friend
     * @ibatorgenerated  Wed Jul 17 17:16:01 CST 2013
     */
    public int updateByExample(PlayerFriend record, PlayerFriendExample example)
            throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update(
                "player_friend.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_friend
     * @ibatorgenerated  Wed Jul 17 17:16:01 CST 2013
     */
    public int updateByPrimaryKeySelective(PlayerFriend record)
            throws SQLException {
        int rows = sqlMapClient.update(
                "player_friend.ibatorgenerated_updateByPrimaryKeySelective",
                record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_friend
     * @ibatorgenerated  Wed Jul 17 17:16:01 CST 2013
     */
    public int updateByPrimaryKey(PlayerFriend record) throws SQLException {
        int rows = sqlMapClient.update(
                "player_friend.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator. This class corresponds to the database table player_friend
     * @ibatorgenerated  Wed Jul 17 17:16:01 CST 2013
     */
    private static class UpdateByExampleParms extends PlayerFriendExample {
        private Object record;

        public UpdateByExampleParms(Object record, PlayerFriendExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}