package com.orange.goldgame.system.dao;

import java.sql.SQLException;
import java.util.List;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.orange.goldgame.domain.PlayerProps;
import com.orange.goldgame.domain.PlayerPropsExample;

public class PlayerPropsDAOImpl implements PlayerPropsDAO {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table player_props
	 * @ibatorgenerated  Mon Jul 15 16:36:18 CST 2013
	 */
	private SqlMapClient sqlMapClient;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_props
	 * @ibatorgenerated  Mon Jul 15 16:36:18 CST 2013
	 */
	public PlayerPropsDAOImpl(SqlMapClient sqlMapClient) {
		super();
		this.sqlMapClient = sqlMapClient;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_props
	 * @ibatorgenerated  Mon Jul 15 16:36:18 CST 2013
	 */
	public int countByExample(PlayerPropsExample example) throws SQLException {
		Integer count = (Integer) sqlMapClient.queryForObject(
				"player_props.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_props
	 * @ibatorgenerated  Mon Jul 15 16:36:18 CST 2013
	 */
	public int deleteByExample(PlayerPropsExample example) throws SQLException {
		int rows = sqlMapClient.delete(
				"player_props.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_props
	 * @ibatorgenerated  Mon Jul 15 16:36:18 CST 2013
	 */
	public int deleteByPrimaryKey(Integer id) throws SQLException {
		PlayerProps key = new PlayerProps();
		key.setId(id);
		int rows = sqlMapClient.delete(
				"player_props.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_props
	 * @ibatorgenerated  Mon Jul 15 16:36:18 CST 2013
	 */
	public Integer insert(PlayerProps record) throws SQLException {
		Object newKey = sqlMapClient.insert(
				"player_props.ibatorgenerated_insert", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_props
	 * @ibatorgenerated  Mon Jul 15 16:36:18 CST 2013
	 */
	public Integer insertSelective(PlayerProps record) throws SQLException {
		Object newKey = sqlMapClient.insert(
				"player_props.ibatorgenerated_insertSelective", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_props
	 * @ibatorgenerated  Mon Jul 15 16:36:18 CST 2013
	 */
	public List selectByExample(PlayerPropsExample example) throws SQLException {
		List list = sqlMapClient.queryForList(
				"player_props.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_props
	 * @ibatorgenerated  Mon Jul 15 16:36:18 CST 2013
	 */
	public PlayerProps selectByPrimaryKey(Integer id) throws SQLException {
		PlayerProps key = new PlayerProps();
		key.setId(id);
		PlayerProps record = (PlayerProps) sqlMapClient.queryForObject(
				"player_props.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_props
	 * @ibatorgenerated  Mon Jul 15 16:36:18 CST 2013
	 */
	public int updateByExampleSelective(PlayerProps record,
			PlayerPropsExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"player_props.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_props
	 * @ibatorgenerated  Mon Jul 15 16:36:18 CST 2013
	 */
	public int updateByExample(PlayerProps record, PlayerPropsExample example)
			throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"player_props.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_props
	 * @ibatorgenerated  Mon Jul 15 16:36:18 CST 2013
	 */
	public int updateByPrimaryKeySelective(PlayerProps record)
			throws SQLException {
		int rows = sqlMapClient.update(
				"player_props.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_props
	 * @ibatorgenerated  Mon Jul 15 16:36:18 CST 2013
	 */
	public int updateByPrimaryKey(PlayerProps record) throws SQLException {
		int rows = sqlMapClient.update(
				"player_props.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table player_props
	 * @ibatorgenerated  Mon Jul 15 16:36:18 CST 2013
	 */
	private static class UpdateByExampleParms extends PlayerPropsExample {
		private Object record;

		public UpdateByExampleParms(Object record, PlayerPropsExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}