package com.orange.goldgame.system.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.orange.goldgame.domain.PlayerTalk;
import com.orange.goldgame.domain.PlayerTalkExample;
import java.sql.SQLException;
import java.util.List;

public class PlayerTalkDAOImpl implements PlayerTalkDAO {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table player_talk
	 * @ibatorgenerated  Fri Nov 15 14:06:05 CST 2013
	 */
	private SqlMapClient sqlMapClient;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_talk
	 * @ibatorgenerated  Fri Nov 15 14:06:05 CST 2013
	 */
	public PlayerTalkDAOImpl(SqlMapClient sqlMapClient) {
		super();
		this.sqlMapClient = sqlMapClient;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_talk
	 * @ibatorgenerated  Fri Nov 15 14:06:05 CST 2013
	 */
	public int countByExample(PlayerTalkExample example) throws SQLException {
		Integer count = (Integer) sqlMapClient.queryForObject(
				"player_talk.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_talk
	 * @ibatorgenerated  Fri Nov 15 14:06:05 CST 2013
	 */
	public int deleteByExample(PlayerTalkExample example) throws SQLException {
		int rows = sqlMapClient.delete(
				"player_talk.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_talk
	 * @ibatorgenerated  Fri Nov 15 14:06:05 CST 2013
	 */
	public int deleteByPrimaryKey(Integer id) throws SQLException {
		PlayerTalk key = new PlayerTalk();
		key.setId(id);
		int rows = sqlMapClient.delete(
				"player_talk.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_talk
	 * @ibatorgenerated  Fri Nov 15 14:06:05 CST 2013
	 */
	public Integer insert(PlayerTalk record) throws SQLException {
		Object newKey = sqlMapClient.insert(
				"player_talk.ibatorgenerated_insert", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_talk
	 * @ibatorgenerated  Fri Nov 15 14:06:05 CST 2013
	 */
	public Integer insertSelective(PlayerTalk record) throws SQLException {
		Object newKey = sqlMapClient.insert(
				"player_talk.ibatorgenerated_insertSelective", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_talk
	 * @ibatorgenerated  Fri Nov 15 14:06:05 CST 2013
	 */
	public List selectByExample(PlayerTalkExample example) throws SQLException {
		List list = sqlMapClient.queryForList(
				"player_talk.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_talk
	 * @ibatorgenerated  Fri Nov 15 14:06:05 CST 2013
	 */
	public PlayerTalk selectByPrimaryKey(Integer id) throws SQLException {
		PlayerTalk key = new PlayerTalk();
		key.setId(id);
		PlayerTalk record = (PlayerTalk) sqlMapClient.queryForObject(
				"player_talk.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_talk
	 * @ibatorgenerated  Fri Nov 15 14:06:05 CST 2013
	 */
	public int updateByExampleSelective(PlayerTalk record,
			PlayerTalkExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"player_talk.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_talk
	 * @ibatorgenerated  Fri Nov 15 14:06:05 CST 2013
	 */
	public int updateByExample(PlayerTalk record, PlayerTalkExample example)
			throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"player_talk.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_talk
	 * @ibatorgenerated  Fri Nov 15 14:06:05 CST 2013
	 */
	public int updateByPrimaryKeySelective(PlayerTalk record)
			throws SQLException {
		int rows = sqlMapClient.update(
				"player_talk.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_talk
	 * @ibatorgenerated  Fri Nov 15 14:06:05 CST 2013
	 */
	public int updateByPrimaryKey(PlayerTalk record) throws SQLException {
		int rows = sqlMapClient.update(
				"player_talk.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table player_talk
	 * @ibatorgenerated  Fri Nov 15 14:06:05 CST 2013
	 */
	private static class UpdateByExampleParms extends PlayerTalkExample {
		private Object record;

		public UpdateByExampleParms(Object record, PlayerTalkExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}