package com.orange.goldgame.system.dao;

import java.sql.SQLException;
import java.util.List;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.orange.goldgame.domain.PropsConfig;
import com.orange.goldgame.domain.PropsConfigExample;

public class PropsConfigDAOImpl implements PropsConfigDAO {

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database table props_config
     * @ibatorgenerated  Wed Jul 31 11:43:32 CST 2013
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table props_config
     * @ibatorgenerated  Wed Jul 31 11:43:32 CST 2013
     */
    public PropsConfigDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table props_config
     * @ibatorgenerated  Wed Jul 31 11:43:32 CST 2013
     */
    public int countByExample(PropsConfigExample example) throws SQLException {
        Integer count = (Integer) sqlMapClient.queryForObject(
                "props_config.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table props_config
     * @ibatorgenerated  Wed Jul 31 11:43:32 CST 2013
     */
    public int deleteByExample(PropsConfigExample example) throws SQLException {
        int rows = sqlMapClient.delete(
                "props_config.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table props_config
     * @ibatorgenerated  Wed Jul 31 11:43:32 CST 2013
     */
    public int deleteByPrimaryKey(Integer id) throws SQLException {
        PropsConfig key = new PropsConfig();
        key.setId(id);
        int rows = sqlMapClient.delete(
                "props_config.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table props_config
     * @ibatorgenerated  Wed Jul 31 11:43:32 CST 2013
     */
    public Integer insert(PropsConfig record) throws SQLException {
        Object newKey = sqlMapClient.insert(
                "props_config.ibatorgenerated_insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table props_config
     * @ibatorgenerated  Wed Jul 31 11:43:32 CST 2013
     */
    public Integer insertSelective(PropsConfig record) throws SQLException {
        Object newKey = sqlMapClient.insert(
                "props_config.ibatorgenerated_insertSelective", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table props_config
     * @ibatorgenerated  Wed Jul 31 11:43:32 CST 2013
     */
    public List selectByExample(PropsConfigExample example) throws SQLException {
        List list = sqlMapClient.queryForList(
                "props_config.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table props_config
     * @ibatorgenerated  Wed Jul 31 11:43:32 CST 2013
     */
    public PropsConfig selectByPrimaryKey(Integer id) throws SQLException {
        PropsConfig key = new PropsConfig();
        key.setId(id);
        PropsConfig record = (PropsConfig) sqlMapClient.queryForObject(
                "props_config.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table props_config
     * @ibatorgenerated  Wed Jul 31 11:43:32 CST 2013
     */
    public int updateByExampleSelective(PropsConfig record,
            PropsConfigExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update(
                "props_config.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table props_config
     * @ibatorgenerated  Wed Jul 31 11:43:32 CST 2013
     */
    public int updateByExample(PropsConfig record, PropsConfigExample example)
            throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update(
                "props_config.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table props_config
     * @ibatorgenerated  Wed Jul 31 11:43:32 CST 2013
     */
    public int updateByPrimaryKeySelective(PropsConfig record)
            throws SQLException {
        int rows = sqlMapClient.update(
                "props_config.ibatorgenerated_updateByPrimaryKeySelective",
                record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table props_config
     * @ibatorgenerated  Wed Jul 31 11:43:32 CST 2013
     */
    public int updateByPrimaryKey(PropsConfig record) throws SQLException {
        int rows = sqlMapClient.update(
                "props_config.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator. This class corresponds to the database table props_config
     * @ibatorgenerated  Wed Jul 31 11:43:32 CST 2013
     */
    private static class UpdateByExampleParms extends PropsConfigExample {
        private Object record;

        public UpdateByExampleParms(Object record, PropsConfigExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}