package com.orange.goldgame.system.dao;

import java.sql.SQLException;
import java.util.List;

import com.orange.goldgame.domain.PropsConfig;
import com.orange.goldgame.domain.PropsConfigExample;

public interface PropsConfigDAO {

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table props_config
     * @ibatorgenerated  Wed Jul 31 11:43:32 CST 2013
     */
    int countByExample(PropsConfigExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table props_config
     * @ibatorgenerated  Wed Jul 31 11:43:32 CST 2013
     */
    int deleteByExample(PropsConfigExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table props_config
     * @ibatorgenerated  Wed Jul 31 11:43:32 CST 2013
     */
    int deleteByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table props_config
     * @ibatorgenerated  Wed Jul 31 11:43:32 CST 2013
     */
    Integer insert(PropsConfig record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table props_config
     * @ibatorgenerated  Wed Jul 31 11:43:32 CST 2013
     */
    Integer insertSelective(PropsConfig record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table props_config
     * @ibatorgenerated  Wed Jul 31 11:43:32 CST 2013
     */
    List selectByExample(PropsConfigExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table props_config
     * @ibatorgenerated  Wed Jul 31 11:43:32 CST 2013
     */
    PropsConfig selectByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table props_config
     * @ibatorgenerated  Wed Jul 31 11:43:32 CST 2013
     */
    int updateByExampleSelective(PropsConfig record, PropsConfigExample example)
            throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table props_config
     * @ibatorgenerated  Wed Jul 31 11:43:32 CST 2013
     */
    int updateByExample(PropsConfig record, PropsConfigExample example)
            throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table props_config
     * @ibatorgenerated  Wed Jul 31 11:43:32 CST 2013
     */
    int updateByPrimaryKeySelective(PropsConfig record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table props_config
     * @ibatorgenerated  Wed Jul 31 11:43:32 CST 2013
     */
    int updateByPrimaryKey(PropsConfig record) throws SQLException;
}