package com.orange.goldgame.system.dao;

import java.sql.SQLException;
import java.util.List;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.orange.goldgame.domain.Ranking;
import com.orange.goldgame.domain.RankingExample;

public class RankingDAOImpl implements RankingDAO {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table ranking
	 * @ibatorgenerated  Wed Aug 21 17:03:36 CST 2013
	 */
	private SqlMapClient sqlMapClient;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ranking
	 * @ibatorgenerated  Wed Aug 21 17:03:36 CST 2013
	 */
	public RankingDAOImpl(SqlMapClient sqlMapClient) {
		super();
		this.sqlMapClient = sqlMapClient;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ranking
	 * @ibatorgenerated  Wed Aug 21 17:03:36 CST 2013
	 */
	public int countByExample(RankingExample example) throws SQLException {
		Integer count = (Integer) sqlMapClient.queryForObject(
				"ranking.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ranking
	 * @ibatorgenerated  Wed Aug 21 17:03:36 CST 2013
	 */
	public int deleteByExample(RankingExample example) throws SQLException {
		int rows = sqlMapClient.delete(
				"ranking.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ranking
	 * @ibatorgenerated  Wed Aug 21 17:03:36 CST 2013
	 */
	public int deleteByPrimaryKey(Integer id) throws SQLException {
		Ranking key = new Ranking();
		key.setId(id);
		int rows = sqlMapClient.delete(
				"ranking.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ranking
	 * @ibatorgenerated  Wed Aug 21 17:03:36 CST 2013
	 */
	public Integer insert(Ranking record) throws SQLException {
		Object newKey = sqlMapClient.insert("ranking.ibatorgenerated_insert",
				record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ranking
	 * @ibatorgenerated  Wed Aug 21 17:03:36 CST 2013
	 */
	public Integer insertSelective(Ranking record) throws SQLException {
		Object newKey = sqlMapClient.insert(
				"ranking.ibatorgenerated_insertSelective", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ranking
	 * @ibatorgenerated  Wed Aug 21 17:03:36 CST 2013
	 */
	public List selectByExample(RankingExample example) throws SQLException {
		List list = sqlMapClient.queryForList(
				"ranking.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ranking
	 * @ibatorgenerated  Wed Aug 21 17:03:36 CST 2013
	 */
	public Ranking selectByPrimaryKey(Integer id) throws SQLException {
		Ranking key = new Ranking();
		key.setId(id);
		Ranking record = (Ranking) sqlMapClient.queryForObject(
				"ranking.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ranking
	 * @ibatorgenerated  Wed Aug 21 17:03:36 CST 2013
	 */
	public int updateByExampleSelective(Ranking record, RankingExample example)
			throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"ranking.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ranking
	 * @ibatorgenerated  Wed Aug 21 17:03:36 CST 2013
	 */
	public int updateByExample(Ranking record, RankingExample example)
			throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"ranking.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ranking
	 * @ibatorgenerated  Wed Aug 21 17:03:36 CST 2013
	 */
	public int updateByPrimaryKeySelective(Ranking record) throws SQLException {
		int rows = sqlMapClient.update(
				"ranking.ibatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ranking
	 * @ibatorgenerated  Wed Aug 21 17:03:36 CST 2013
	 */
	public int updateByPrimaryKey(Ranking record) throws SQLException {
		int rows = sqlMapClient.update(
				"ranking.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table ranking
	 * @ibatorgenerated  Wed Aug 21 17:03:36 CST 2013
	 */
	private static class UpdateByExampleParms extends RankingExample {
		private Object record;

		public UpdateByExampleParms(Object record, RankingExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}