package com.orange.goldgame.system.dao;

import java.sql.SQLException;
import java.util.List;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.orange.goldgame.domain.RobotPre;
import com.orange.goldgame.domain.RobotPreExample;

public class RobotPreDAOImpl implements RobotPreDAO {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table robot_pre
	 * @ibatorgenerated  Wed Jul 17 17:51:47 CST 2013
	 */
	private SqlMapClient sqlMapClient;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table robot_pre
	 * @ibatorgenerated  Wed Jul 17 17:51:47 CST 2013
	 */
	public RobotPreDAOImpl(SqlMapClient sqlMapClient) {
		super();
		this.sqlMapClient = sqlMapClient;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table robot_pre
	 * @ibatorgenerated  Wed Jul 17 17:51:47 CST 2013
	 */
	public int countByExample(RobotPreExample example) throws SQLException {
		Integer count = (Integer) sqlMapClient.queryForObject(
				"robot_pre.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table robot_pre
	 * @ibatorgenerated  Wed Jul 17 17:51:47 CST 2013
	 */
	public int deleteByExample(RobotPreExample example) throws SQLException {
		int rows = sqlMapClient.delete(
				"robot_pre.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table robot_pre
	 * @ibatorgenerated  Wed Jul 17 17:51:47 CST 2013
	 */
	public int deleteByPrimaryKey(Integer id) throws SQLException {
		RobotPre key = new RobotPre();
		key.setId(id);
		int rows = sqlMapClient.delete(
				"robot_pre.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table robot_pre
	 * @ibatorgenerated  Wed Jul 17 17:51:47 CST 2013
	 */
	public Integer insert(RobotPre record) throws SQLException {
		Object newKey = sqlMapClient.insert("robot_pre.ibatorgenerated_insert",
				record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table robot_pre
	 * @ibatorgenerated  Wed Jul 17 17:51:47 CST 2013
	 */
	public Integer insertSelective(RobotPre record) throws SQLException {
		Object newKey = sqlMapClient.insert(
				"robot_pre.ibatorgenerated_insertSelective", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table robot_pre
	 * @ibatorgenerated  Wed Jul 17 17:51:47 CST 2013
	 */
	public List selectByExample(RobotPreExample example) throws SQLException {
		List list = sqlMapClient.queryForList(
				"robot_pre.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table robot_pre
	 * @ibatorgenerated  Wed Jul 17 17:51:47 CST 2013
	 */
	public RobotPre selectByPrimaryKey(Integer id) throws SQLException {
		RobotPre key = new RobotPre();
		key.setId(id);
		RobotPre record = (RobotPre) sqlMapClient.queryForObject(
				"robot_pre.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table robot_pre
	 * @ibatorgenerated  Wed Jul 17 17:51:47 CST 2013
	 */
	public int updateByExampleSelective(RobotPre record, RobotPreExample example)
			throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"robot_pre.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table robot_pre
	 * @ibatorgenerated  Wed Jul 17 17:51:47 CST 2013
	 */
	public int updateByExample(RobotPre record, RobotPreExample example)
			throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"robot_pre.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table robot_pre
	 * @ibatorgenerated  Wed Jul 17 17:51:47 CST 2013
	 */
	public int updateByPrimaryKeySelective(RobotPre record) throws SQLException {
		int rows = sqlMapClient
				.update("robot_pre.ibatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table robot_pre
	 * @ibatorgenerated  Wed Jul 17 17:51:47 CST 2013
	 */
	public int updateByPrimaryKey(RobotPre record) throws SQLException {
		int rows = sqlMapClient.update(
				"robot_pre.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table robot_pre
	 * @ibatorgenerated  Wed Jul 17 17:51:47 CST 2013
	 */
	private static class UpdateByExampleParms extends RobotPreExample {
		private Object record;

		public UpdateByExampleParms(Object record, RobotPreExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}