package com.orange.goldgame.system.dao;

import java.sql.SQLException;
import java.util.List;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.orange.goldgame.domain.ServerConfig;
import com.orange.goldgame.domain.ServerConfigExample;

public class ServerConfigDAOImpl implements ServerConfigDAO {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table server_config
	 * @ibatorgenerated  Thu Jul 04 18:10:48 CST 2013
	 */
	private SqlMapClient sqlMapClient;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table server_config
	 * @ibatorgenerated  Thu Jul 04 18:10:48 CST 2013
	 */
	public ServerConfigDAOImpl(SqlMapClient sqlMapClient) {
		super();
		this.sqlMapClient = sqlMapClient;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table server_config
	 * @ibatorgenerated  Thu Jul 04 18:10:48 CST 2013
	 */
	public int countByExample(ServerConfigExample example) throws SQLException {
		Integer count = (Integer) sqlMapClient.queryForObject(
				"server_config.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table server_config
	 * @ibatorgenerated  Thu Jul 04 18:10:48 CST 2013
	 */
	public int deleteByExample(ServerConfigExample example) throws SQLException {
		int rows = sqlMapClient.delete(
				"server_config.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table server_config
	 * @ibatorgenerated  Thu Jul 04 18:10:48 CST 2013
	 */
	public int deleteByPrimaryKey(Integer id) throws SQLException {
		ServerConfig key = new ServerConfig();
		key.setId(id);
		int rows = sqlMapClient.delete(
				"server_config.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table server_config
	 * @ibatorgenerated  Thu Jul 04 18:10:48 CST 2013
	 */
	public Integer insert(ServerConfig record) throws SQLException {
		Object newKey = sqlMapClient.insert(
				"server_config.ibatorgenerated_insert", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table server_config
	 * @ibatorgenerated  Thu Jul 04 18:10:48 CST 2013
	 */
	public Integer insertSelective(ServerConfig record) throws SQLException {
		Object newKey = sqlMapClient.insert(
				"server_config.ibatorgenerated_insertSelective", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table server_config
	 * @ibatorgenerated  Thu Jul 04 18:10:48 CST 2013
	 */
	public List selectByExample(ServerConfigExample example)
			throws SQLException {
		List list = sqlMapClient.queryForList(
				"server_config.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table server_config
	 * @ibatorgenerated  Thu Jul 04 18:10:48 CST 2013
	 */
	public ServerConfig selectByPrimaryKey(Integer id) throws SQLException {
		ServerConfig key = new ServerConfig();
		key.setId(id);
		ServerConfig record = (ServerConfig) sqlMapClient.queryForObject(
				"server_config.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table server_config
	 * @ibatorgenerated  Thu Jul 04 18:10:48 CST 2013
	 */
	public int updateByExampleSelective(ServerConfig record,
			ServerConfigExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient
				.update("server_config.ibatorgenerated_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table server_config
	 * @ibatorgenerated  Thu Jul 04 18:10:48 CST 2013
	 */
	public int updateByExample(ServerConfig record, ServerConfigExample example)
			throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"server_config.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table server_config
	 * @ibatorgenerated  Thu Jul 04 18:10:48 CST 2013
	 */
	public int updateByPrimaryKeySelective(ServerConfig record)
			throws SQLException {
		int rows = sqlMapClient.update(
				"server_config.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table server_config
	 * @ibatorgenerated  Thu Jul 04 18:10:48 CST 2013
	 */
	public int updateByPrimaryKey(ServerConfig record) throws SQLException {
		int rows = sqlMapClient.update(
				"server_config.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table server_config
	 * @ibatorgenerated  Thu Jul 04 18:10:48 CST 2013
	 */
	private static class UpdateByExampleParms extends ServerConfigExample {
		private Object record;

		public UpdateByExampleParms(Object record, ServerConfigExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}