package com.orange.goldgame.system.dao;

import java.sql.SQLException;
import java.util.List;

import com.orange.goldgame.domain.TaskConfig;
import com.orange.goldgame.domain.TaskConfigExample;

public interface TaskConfigDAO {

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table task_config
     * @ibatorgenerated  Mon Jul 22 14:30:59 CST 2013
     */
    int countByExample(TaskConfigExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table task_config
     * @ibatorgenerated  Mon Jul 22 14:30:59 CST 2013
     */
    int deleteByExample(TaskConfigExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table task_config
     * @ibatorgenerated  Mon Jul 22 14:30:59 CST 2013
     */
    int deleteByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table task_config
     * @ibatorgenerated  Mon Jul 22 14:30:59 CST 2013
     */
    Integer insert(TaskConfig record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table task_config
     * @ibatorgenerated  Mon Jul 22 14:30:59 CST 2013
     */
    Integer insertSelective(TaskConfig record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table task_config
     * @ibatorgenerated  Mon Jul 22 14:30:59 CST 2013
     */
    List selectByExample(TaskConfigExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table task_config
     * @ibatorgenerated  Mon Jul 22 14:30:59 CST 2013
     */
    TaskConfig selectByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table task_config
     * @ibatorgenerated  Mon Jul 22 14:30:59 CST 2013
     */
    int updateByExampleSelective(TaskConfig record, TaskConfigExample example)
            throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table task_config
     * @ibatorgenerated  Mon Jul 22 14:30:59 CST 2013
     */
    int updateByExample(TaskConfig record, TaskConfigExample example)
            throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table task_config
     * @ibatorgenerated  Mon Jul 22 14:30:59 CST 2013
     */
    int updateByPrimaryKeySelective(TaskConfig record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table task_config
     * @ibatorgenerated  Mon Jul 22 14:30:59 CST 2013
     */
    int updateByPrimaryKey(TaskConfig record) throws SQLException;
}