package com.orange.goldgame.core.dao;

import java.sql.SQLException;
import java.util.List;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.orange.goldgame.core.model.Consum;
import com.orange.goldgame.core.model.ConsumExample;

public class ConsumDAOImpl implements ConsumDAO {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table consum
     *
     * @abatorgenerated Tue Apr 15 17:30:03 CST 2014
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table consum
     *
     * @abatorgenerated Tue Apr 15 17:30:03 CST 2014
     */
    public ConsumDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table consum
     *
     * @abatorgenerated Tue Apr 15 17:30:03 CST 2014
     */
    public Integer insert(Consum record) throws SQLException {
        Object newKey = sqlMapClient.insert("consum.abatorgenerated_insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table consum
     *
     * @abatorgenerated Tue Apr 15 17:30:03 CST 2014
     */
    public int updateByPrimaryKey(Consum record) throws SQLException {
        int rows = sqlMapClient.update("consum.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table consum
     *
     * @abatorgenerated Tue Apr 15 17:30:03 CST 2014
     */
    public int updateByPrimaryKeySelective(Consum record) throws SQLException {
        int rows = sqlMapClient.update("consum.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table consum
     *
     * @abatorgenerated Tue Apr 15 17:30:03 CST 2014
     */
    @SuppressWarnings("unchecked")
    public List<Consum> selectByExample(ConsumExample example) throws SQLException {
        List<Consum> list = (List<Consum>) sqlMapClient.queryForList("consum.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table consum
     *
     * @abatorgenerated Tue Apr 15 17:30:03 CST 2014
     */
    public Consum selectByPrimaryKey(Integer id) throws SQLException {
        Consum key = new Consum();
        key.setId(id);
        Consum record = (Consum) sqlMapClient.queryForObject("consum.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table consum
     *
     * @abatorgenerated Tue Apr 15 17:30:03 CST 2014
     */
    public int deleteByExample(ConsumExample example) throws SQLException {
        int rows = sqlMapClient.delete("consum.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table consum
     *
     * @abatorgenerated Tue Apr 15 17:30:03 CST 2014
     */
    public int deleteByPrimaryKey(Integer id) throws SQLException {
        Consum key = new Consum();
        key.setId(id);
        int rows = sqlMapClient.delete("consum.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table consum
     *
     * @abatorgenerated Tue Apr 15 17:30:03 CST 2014
     */
    public int countByExample(ConsumExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("consum.abatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table consum
     *
     * @abatorgenerated Tue Apr 15 17:30:03 CST 2014
     */
    public int updateByExampleSelective(Consum record, ConsumExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("consum.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table consum
     *
     * @abatorgenerated Tue Apr 15 17:30:03 CST 2014
     */
    public int updateByExample(Consum record, ConsumExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("consum.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table consum
     *
     * @abatorgenerated Tue Apr 15 17:30:03 CST 2014
     */
    private static class UpdateByExampleParms extends ConsumExample {
        private Object record;

        public UpdateByExampleParms(Object record, ConsumExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}